// English content for cups-08-14 (produced by content agents).
// name/nameEn/ids MUST mirror the zh files and registry; verdicts MUST match zh.
import type { TarotCard } from '../types'

export const cups0814: TarotCard[] = [
  {
    id: 'cups-08',
    name: '聖杯八',
    nameEn: 'Eight of Cups',
    arcana: 'minor',
    suit: 'cups',
    rank: 8,
    number: 8,
    scene: 'Eight golden cups stand stacked in two rows in the foreground, one gap in the upper row; a figure in a red cloak, leaning on a staff, walks away across the marsh toward distant mountains while a moon with a profiled face looks down.',
    upright: {
      keywords: ['walking away', 'letting go', 'seeking meaning', 'farewell'],
      core: "Eight cups stacked neatly — and their owner turns and walks away. This card is not about failure. It's about a voice inside you growing clearer: everything here may be complete, but it no longer feeds you. Leaving takes more courage than staying. Admit that the answer you need isn't here anymore, hand your steps over to the deeper longing, and the next chapter waits on the far side of the mountain.",
      daily: "Set aside some quiet time today and ask yourself: of the things filling your days, which one stopped nourishing you a while ago? You don't have to quit or cut ties right now — just write down that feeling of \"it's about time to go\" and give it a name.",
      love: "If a relationship has long run on form alone, this card backs you in facing that honestly. If you're single, you may be releasing an old flame — finish the goodbye, and new love can get in.",
      career: "That weariness of \"I can keep doing this, I just don't want to anymore\" deserves real attention. Do the homework for a proper transition rather than pushing until you burn out and bolt in a panic.",
      money: "You may need to release a sunk cost you've poured a lot into. Money can be earned back; doubling down on the wrong direction is the loss that really costs you.",
      advice: 'Be honest with the voice that says "time to go" — close things out gracefully, then set off.',
      past: 'The turning point was that turn of the back: you set down something that looked complete and set out after a deeper longing.',
      present: 'The voice saying "this no longer feeds me" is getting clearer by the day; your attention belongs on how to close this chapter with grace.',
      other: 'Their heart is already heading for the door: everything in front of them looks complete, yet it can no longer hold them — the wish to leave is serious.',
      verdict: 'leanNo',
      verdictReason: "This card's energy is departure and release; for most questions the answer points to not lingering, so it leans against the current state continuing.",
    },
    reversed: {
      keywords: ['unable to leave', 'wavering', 'false detachment', 'stuck in place'],
      core: "Reversed, the leaving is stuck halfway. Maybe you keep saying you'll go while your feet never move; maybe you did go, but your heart glances back every day; or maybe you bolted just to escape and carried the problem, untouched, to the next stop. First sort out whether you can't bear to leave or don't dare to — those are different answers, and the homework for each is completely different.",
      daily: "Don't rush the stay-or-go decision today. Take a sheet of paper and make two columns: on the left, \"what staying actually gives me\"; on the right, \"what leaving actually costs me.\" Once it's written down, you may find some of those boxes are empty.",
      love: "The tug-of-war of can't-break-up, can't-make-up is the most draining kind. Instead of testing them again and again, first get clear on \"am I staying out of love, or out of fear\" — then decide how to act.",
      career: "Your dissatisfaction with the job is stalled at the complaining stage, with no next step in sight. Update the résumé, test the market — once the options turn concrete, the wavering finally has an exit.",
      money: "A position that should be cut keeps sitting there, or you sell and then can't resist chasing back in. Set yourself one clear exit rule, write it down, and follow it.",
      advice: "First figure out whether you can't bear to go or don't dare to — then decide your next step.",
      past: "When it was time to go, you didn't quite manage it — or you left while your heart stayed behind. That long delay has been smothering things ever since.",
      present: "Right now you're pacing back and forth between staying and going; sort out whether it's reluctance or fear, and your feet will find their direction.",
      other: "They can neither stay nor leave: they talk about letting go, yet keep looking back — for now they can't summon the resolve to truly walk away.",
      verdict: 'neutral',
      verdictReason: "Reversed, the stay-or-go question hangs unresolved; forcing a yes-or-no now is premature — get clear on what's stuck first, and the question will answer truer.",
    },
  },
  {
    id: 'cups-09',
    name: '聖杯九',
    nameEn: 'Nine of Cups',
    arcana: 'minor',
    suit: 'cups',
    rank: 9,
    number: 9,
    scene: 'A man in a red hat sits on a wooden bench with his arms crossed, looking thoroughly satisfied; behind him a curved high shelf draped in blue cloth holds nine golden cups arranged in a single row, arching around him like a gateway.',
    upright: {
      keywords: ['wish granted', 'contentment', 'enjoying the harvest', 'satisfaction'],
      core: "Tradition calls this the wish card: nine cups arrayed behind him, the man sits with folded arms and a well-fed smile. What you're asking about is moving in a direction that will make you happy — earlier efforts are starting to pay back, and a wish made now carries extra weight. The one thing to notice: the satisfaction in this picture is his alone. Share the good news, and the joy doubles.",
      daily: "Treat yourself today. Book that restaurant you've been thinking about, buy the small thing that's been sitting in your cart, or simply get a proper night's sleep. Your recent efforts have earned one round of being treated well — by you.",
      love: "Romance is running sweet: an ambiguous connection has a chance to turn clear, and settled couples should plan a long-overdue date and say the thank-yous that usually go unsaid.",
      career: "Projects are bearing fruit and your work is being seen. It's a good moment to step forward or make the request you've been sitting on — the odds of it landing are better than usual.",
      money: "Happy news arrives around income or investments, and things feel comfortable. Enjoy it — and set a portion aside, so the good luck settles into solid ground under your feet.",
      advice: 'Accept this good fortune graciously — and remember to share the joy with someone.',
      past: "Beneath all this lies a stretch of things going right: earlier efforts bloomed as hoped, and that satisfaction is what props up the present.",
      present: "Good things are cashing in right now — you're standing at the moment a wish takes shape. Receive it graciously, and pass some of it along.",
      other: "That person is content right now, savoring the sweetness of things going their way. The pleasure is real — they just mostly keep it to themselves.",
      verdict: 'yes',
      verdictReason: "Wish fulfillment is the very essence of this card; for a yes-or-no question, it's about as clear an affirmative signal as the deck can give.",
    },
    reversed: {
      keywords: ['hollow success', 'vanity', 'overindulgence', 'the gap'],
      core: "The cups are all still there, but the taste has changed. Reversed, this card usually shows one of two things: the wish came true and you discovered it wasn't what you really wanted, or you're spending all your energy making sure everyone can see how well you're doing. Ask inward: if nobody ever hit \"like,\" would you still want this goal? The answer will steer you back on course.",
      daily: "Scroll a little less of other people's highlight reels today and take back the energy you spend comparing. List three things you'd do purely for the joy of it, with no one watching — then pick one and quietly go do it.",
      love: "The relationship looks presentable from outside but feels a little hollow within. Spend less effort curating the \"we're doing great\" image and more on real conversation — that's what actually fills it.",
      career: "The satisfaction from titles and applause is ebbing — achievement and meaning may have come uncoupled. Ask again whether what you want to leave behind is a body of work, or just a record.",
      money: "Watch out for spending to keep up appearances: treating, upgrading, label-chasing beyond what you actually need. Go back to \"buy it only if you'll use it\" — your account will thank you.",
      advice: 'Set down "how it looks to others" and first confirm what you actually want.',
      past: "What you chased and caught tasted less sweet than imagined, or appearances mattered too much — that gap became the seed of today's lesson.",
      present: "You're sitting with the hollow feeling of \"I got it, and I'm still not satisfied.\" Move your gaze from other people's applause back to what you truly want.",
      other: "They look like they're doing fine, yet inside there's an emptiness they can't quite name; what they've gotten and what they truly want may not be the same thing.",
      verdict: 'leanNo',
      verdictReason: "Reversed, the satisfaction comes discounted: the thing may still take shape, but it won't taste the way you hoped — so the answer leans toward reservation.",
    },
  },
  {
    id: 'cups-10',
    name: '聖杯十',
    nameEn: 'Ten of Cups',
    arcana: 'minor',
    suit: 'cups',
    rank: 10,
    number: 10,
    scene: 'A man and woman stand side by side with arms flung open toward the sky, where a rainbow arcs overhead holding ten golden cups; beside them two children dance hand in hand, and in the distance sit a small house, trees and a winding river.',
    upright: {
      keywords: ['fulfillment', 'family harmony', 'belonging', 'happiness'],
      core: "A family under a rainbow, arms wide, children dancing beside them — the Ten of Cups paints the emotional world's happy ending. It cares less about any single win or loss than about the whole-life feeling of coming home and being at ease. What you're asking about is gathering toward completion — and the benefit won't be yours alone; the people close to you get a share of this warmth too.",
      daily: "Give your time to the people who matter first today: go home for dinner, call a family member with no clock running, or simply be present without a phone in hand. Happiness is saved up exactly this way — a little at a time.",
      love: "The relationship heads toward commitment and stability: meeting the family, moving in, talking futures — all blessed. Single? You may meet someone in the \"I could build a home with them\" league.",
      career: "Team spirit is warm and collaboration flows, and your work-life balance is improving too. This is a moment for cultivating long-term partnerships rather than going it alone.",
      money: "Household finances are steadying — a good time for long-range family arrangements: insurance, an education fund, or one savings goal the whole family shares.",
      advice: 'Put the definition of happiness back on people — tending your relationships is tending your luck.',
      past: "All of this stands on a foundation of emotional security: the support family or loved ones once gave is the deepest reserve you draw on now.",
      present: "The lesson right now is cherishing: things are gathering toward completion, and giving your time to the people who matter is the best investment there is.",
      other: "Their heart is settled; what they want is belonging and something lasting. They've placed this relationship inside their picture of the future — the warmth is solid.",
      verdict: 'yes',
      verdictReason: "The Ten of Cups is the emotional suit's fulfilled ending, its energy wholly positive — for a yes-or-no question it gives a clear and warm affirmative.",
    },
    reversed: {
      keywords: ['drifting apart', 'ideal vs. reality', 'family friction', 'discord'],
      core: "Reversed, the rainbow still hangs there, but the air under the roof has gone stale: family or partner keep the surface calm while each nurses a private grievance. Or you're gripping the image of a perfect family so tightly you can't see the real one. Happiness isn't the absence of friction — it's the willingness to repair. Bring expectations back to human scale; mending one conversation is visible progress.",
      daily: "If friction flares with someone close today, don't rush to settle who's right. Pick one small thing they did for you recently and thank them for it, specifically. Once the air softens, the conversation you actually want to have can finally get in.",
      love: "There's a gap between the relationship you imagined and the one you have. The disappointment is real — but no death sentence yet. Saying \"here's what I hope we become\" beats a cold war.",
      career: "Discontent is simmering under the surface of the team or the family business. Rather than straining to keep the peace, take the initiative to arrange one honest clear-the-air conversation.",
      money: "Household expenses, support for parents, shared costs — all easy sparks for argument. Lay the accounts open on the table; when the numbers are clear, money stops grinding away at the affection.",
      advice: 'Turn down the perfection filter — start by repairing one concrete conversation.',
      past: "At the start there was a quiet drifting-apart: grievances under one roof that never got aired, silently piling up into the standoff you have now.",
      present: "You're facing the gap between the ideal family and the real one. Don't rush to assign blame — begin by mending a single conversation.",
      other: "They keep the peace on the surface while unspoken grievances collect inside. They still care about this relationship — just somewhat disappointed in how it stands.",
      verdict: 'leanNo',
      verdictReason: "Reversed, the picture of harmony shows a crack; fulfillment still owes a stretch of repair work, so the answer leans toward reservation.",
    },
  },
  {
    id: 'cups-11',
    name: '聖杯侍者',
    nameEn: 'Page of Cups',
    arcana: 'minor',
    suit: 'cups',
    rank: 11,
    number: 11,
    scene: 'A young page stands at the shore in a blue tunic printed with flowers and a hat with a trailing scarf, holding a single golden cup in one hand; a fish pokes out of the cup and meets his gaze, with rolling waves behind him.',
    upright: {
      keywords: ['intuitive message', 'budding creativity', 'curiosity', 'sincerity'],
      core: "A fish pokes out of the cup, and the page isn't startled — he looks right back at it. This is the energy of being willing to catch the whimsical when it arrives. It might be someone around you: a sincere, head-in-the-clouds young soul. Or it might be a side of yourself — a creative impulse just surfacing, a first flutter of feeling. Don't smother it with \"that's not realistic\"; let the idea finish its sentence first.",
      daily: "Watch for the small uninvited sparks today: the idea that flashes by in the shower, the old friend you suddenly want to reach, the dream still with you when you wake. Pick one, write it down, and take the smallest possible step — send one message.",
      love: "A green but genuine gesture of affection may arrive — or you may be the one wanting to make it. The feeling doesn't need sophisticated wrapping; honesty is charming all by itself.",
      career: "The newcomer's eye is a gift: the questions asked by the least experienced person often land right on target. Speak up when you have an idea, and give the younger voices on the team some stage.",
      money: "Curiosity about new financial tools is healthy. Practice with small amounts first and count the lessons as tuition — don't put your whole stake in at once.",
      advice: 'Take the seemingly childish idea seriously — give it fifteen minutes.',
      past: "Looking back, it was one naive idea, one tender unpolished gesture, that quietly opened the thread you're following now.",
      present: "A still-green spark of inspiration or attraction is waving at you. Don't rush to dismiss it — let it finish saying what it came to say.",
      other: "That person carries a tender, sincere fondness or curiosity — still young at heart about it, and possibly working up the courage to offer you a little something.",
      verdict: 'leanYes',
      verdictReason: "The Page brings fresh news and a budding opportunity; the direction is affirmative — it's just still tender, and needs your patience to grow.",
    },
    reversed: {
      keywords: ['sulking', 'escapism', 'creative block', 'easily bruised'],
      core: "Reversed, the page claps the lid back over the fish: inspiration stalls, feelings go unspoken, or sulking stands in for saying things properly. It may be someone near you — or a side of yourself — whose moods shift like weather, wearing everyone out. The inner child doesn't need to be scolded for being childish; it needs to be heard. First find out what all that fussing underneath actually wants.",
      daily: "Emotions run amplified today, so don't fire back at the first sharp word. Type the retort into your notes app and let it sit an hour. When you come back, odds are you'll delete half of it, soften the rest, and only then hit send.",
      love: "Hints, sulking and leaving messages on read only let the misunderstanding snowball. Practice translating feelings into grown-up language — and say them out loud, directly.",
      career: "Wanting to slack off after a proposal gets shot down is only human — just don't stay there. Pick up the useful twenty percent of the feedback and let the rest float off downstream.",
      money: "Beware the loop of opening the shopping app whenever your mood dips; retail therapy doesn't treat the root. Settle the feelings first, then touch the wallet.",
      advice: 'Translate the sulk into one clear need, and say it to the right person.',
      past: "Some feelings back then never got properly said — sulking stood in for speaking, and the undelivered messages have been piling up ever since.",
      present: "You, or someone close, is trapped in amplified emotion right now. Translate the sulk into a clear need first, then open the conversation.",
      other: "Their moods shift like weather; some things weigh on them that they can't say aloud, so sulking does the talking. Underneath, what they really want is to be heard.",
      verdict: 'leanNo',
      verdictReason: "Reversed, both the emotions and the message are out of sorts; judgment made now is easily distorted — letting things breathe first is the steadier move.",
    },
  },
  {
    id: 'cups-12',
    name: '聖杯騎士',
    nameEn: 'Knight of Cups',
    arcana: 'minor',
    suit: 'cups',
    rank: 12,
    number: 12,
    scene: 'A knight rides a white horse at a slow walk, holding a golden cup level in both hands; wings adorn his helmet and heels, and red fish patterns mark his robe. Ahead of him lie a river and bare rocky hills.',
    upright: {
      keywords: ['romantic invitation', "heart's calling", 'gentle action', 'a proposal'],
      core: "The white horse slows to a walk, and the knight holds the cup level — he hasn't come to charge; he's come to deliver his heart. A romantic invitation or moving proposal may be on its way — or it's your turn to act gently for someone, or some dream: someone around you, or a side of yourself stepping forward. The energy is graceful and sincere, worth answering. Just remember: a steady cup matters more than a fast ride.",
      daily: "Today favors offering your own cup: invite the person you've been meaning to see, send out the proposal that's been brewing, or add one overdue word of affection to a relationship. Soften the posture, and the sincerity will be caught.",
      love: "A confession, a date invitation, a long-absent romantic message — something is on its way. If you're partnered, add a little ceremony: make one small thing with your own hands that makes their heart skip.",
      career: "A good moment to wrap professionalism in feeling: a proposal that tells a story moves people more than bare numbers. Cross-field collaborations and creative work run especially smooth.",
      money: "An appealing offer or partnership may arrive, and the direction deserves a nod — but before signing, take off the romantic filter and check the terms line by line.",
      advice: 'When your heart moves, act with grace — carry your feelings right up to them.',
      past: "The story began with a romantic invitation or a moving proposal; that offering, carried carefully forward, paved the road to where you stand.",
      present: "A cup is being carried toward you: the invitation or proposal is right in front of you. Answer it with grace — don't let it go cold.",
      other: "That person is being carried along by real attraction, wanting to present their feelings to you properly. The romance is sincere, and the posture gentle.",
      verdict: 'leanYes',
      verdictReason: "The Knight arrives bearing goodwill and invitation; things are drawing near in a good way — the outcome turns only on whether you accept and follow.",
    },
    reversed: {
      keywords: ['empty promises', 'disillusionment', 'moody swings', 'stalling'],
      core: "Reversed, the knight can't keep the cup level anymore: the words are lovely, the follow-through patchy, and promises evaporate like perfume. He may be the person in your life who's forever \"still thinking about it\" — or a side of yourself, swept along by feeling into commitments you can't keep. Shift the weight of your judgment from what they say to what they do, and everything gets much clearer.",
      daily: "A good day for a promise audit: list what others have promised you, and what you've promised others. For the ones already overdue, speak up — confirm or renegotiate — before they quietly ferment into resentment.",
      love: "When sweet words and actual behavior don't line up, believe the behavior. And if you're the one who can't offer commitment, saying so honestly is far kinder than stringing someone along.",
      career: "Beware the collaboration that's all vision and no timeline. Taking on work yourself, don't promise delivery dates just to please — bounce one, and your credibility drops three notches.",
      money: "An investment story that sounds too lovely demands verification from every side. Look at cash flow and exit terms — not how moving the pitch deck is.",
      advice: 'Judge by actions, not words — a promise only counts once it has a date on it.',
      past: "A promise back then went unkept: fine words, scattered follow-through — and the fall from that height ground out the distrust you carry now.",
      present: "You're facing a gap between what's said and what's done — in someone else, or in yourself. Right now, count only the actions.",
      other: "Their words are lovely but their steps are scattered; their heart is still drifting. Right now they can't give you a promise with a date on it.",
      verdict: 'leanNo',
      verdictReason: "The reversed Knight's promises tend to fall through; the pretty words in front of you can't carry the weight a yes answer needs.",
    },
  },
  {
    id: 'cups-13',
    name: '聖杯王后',
    nameEn: 'Queen of Cups',
    arcana: 'minor',
    suit: 'cups',
    rank: 13,
    number: 13,
    scene: 'A woman sits on a throne at the sea\'s edge, gazing at an ornate lidded golden cup with angel-figure handles held in both hands; the throne is carved with shells and mermaid figures, and colorful pebbles and shallow water lie at her feet.',
    upright: {
      keywords: ['empathy', 'keen intuition', 'holding space', 'emotional maturity'],
      core: "She holds the only lidded cup in the deck, and studies it with full attention — feeling kept safe, neither flooding over nor going cold. This may be someone around you who always catches other people's emotions — or a side of yourself being called on now. Either way: your strongest tools at this moment are empathy and intuition. Set the analysis aside for now; what you feel is more accurate than you think.",
      daily: "Practice being a true listener today. When a friend or colleague hesitates mid-sentence, pour them a glass of water, sit down, and hear them out — advice can wait. The people you catch will one day circle back and catch you.",
      love: "What the relationship needs now is empathy, not solutions. Let them know \"I understand why this hurts\" before you discuss what to do. If you're single, your gentleness is unusually magnetic right now.",
      career: "Well suited to the caretaking roles: mentoring new hires, calming clients, tending team morale. Your soft skills are worth more than technical muscle at this moment.",
      money: "Your gut sense about money is worth consulting — if something feels off, look twice before you move. It's also a good time to spend on the well-being of yourself and your family.",
      advice: 'Trust your intuition, and catch people with gentleness that keeps its boundaries.',
      past: "Someone once caught you gently, or you followed your gut and chose right — that experience of being understood is what feeds the present.",
      present: "Your best tools right now are empathy and intuition: catch the feeling first, sort right and wrong later. What you sense is truer than what you reason.",
      other: "Their feelings run mature and fine-grained; they're quietly sensing where you are. They understand more than they say, and there's real heart inside the gentleness.",
      verdict: 'leanYes',
      verdictReason: "This card rests on mature feeling and accurate intuition; things are flowing in a gentle, positive direction.",
    },
    reversed: {
      keywords: ['emotional overflow', 'blurred boundaries', 'oversensitivity', 'empathy overload'],
      core: "Reversed, the lid has come loose: other people's emotions pour in, your own spill out, and slowly you can't tell which feelings are actually yours. You may be over-managing someone else's life, or wrapping control in \"it's for your own good\" — or someone near you speaks in tears, leaving you unable to step closer or away. Empathy needs boundaries to go with it; otherwise the rescuer drowns alongside.",
      daily: "Run an emotion audit today: when your mood suddenly sinks, pause three seconds and ask, \"is this mine, or did I pick it up somewhere?\" The loads that don't belong to you — practice setting them gently back where they came from.",
      love: "Over-giving in love won't buy the security you're after; it only hollows you out. Take two-tenths of the energy you spend caring for them and route it back to caring for yourself.",
      career: "Saying yes to every colleague's request keeps squeezing out your own work. Practice \"I can help, but it'll be next week\" — the sky will not fall.",
      money: "Be careful with loan requests wrapped in emotional pressure. Before your heart softens, think it through: if this money never comes back, will the relationship still be standing?",
      advice: "Put the lid back on your own cup before deciding how much of other people's rain to catch.",
      past: "The boundaries ran too loose back then: you, or someone close, carried too many feelings and gave past the limit, slowly hollowing out.",
      present: "You're being flooded — by your own emotions or someone else's. Sort out which feelings you merely picked up, and set the lid gently back on the cup.",
      other: "They're awash in emotion: their own feelings tangled up with burdens carried for others. They're tender-hearted right now, and their boundaries have gone blurry.",
      verdict: 'neutral',
      verdictReason: "Reversed, emotion has flooded over judgment; any answer now comes tinted by feeling — let the water clear, then ask again, and it will read truer.",
    },
  },
  {
    id: 'cups-14',
    name: '聖杯國王',
    nameEn: 'King of Cups',
    arcana: 'minor',
    suit: 'cups',
    rank: 14,
    number: 14,
    scene: 'A bearded king sits on a stone throne afloat on the sea, a golden cup in his right hand, a short scepter in his left, a fish pendant on his chest; waves swell around him, a ship sailing on one side and a fish leaping on the other.',
    upright: {
      keywords: ['emotional mastery', 'steady compassion', 'mature wisdom', 'holding steady'],
      core: "The sea heaves, and the king on his stone throne doesn't stir. It's not that he has no feelings — he has learned to live alongside them. This might be an elder or manager near you who only gets calmer as things get messier, or the role you're being asked to play: the one who steadies everyone when the waves come up. Compassion plus self-command — the weightiest kind of authority right now.",
      daily: "When something maddening lands today, breathe first and answer half a beat late. You don't need to suppress what you feel — just leave one small gap between the feeling and the reaction, and the whole course of events will change.",
      love: "The relationship needs an emotionally steady anchor. Choose acceptance over lecturing, everyday reliability over grand passionate promises, and trust will thicken slowly.",
      career: "Suited to the mediator's and leader's chair: departments clashing, a client mid-fury — the messier the scene, the more your value shows.",
      money: "Holding steady through market swings is your edge. Execute the plan you already made, with discipline — no panic selling, no greedy doubling down.",
      advice: 'Leave a gap between feeling and reaction — steady yourself first, then steady the room.',
      past: "When the storm came, someone held the situation steady — that quiet, unshowy maturity laid the solid ground you're standing on now.",
      present: "It's your turn to be the anchor: leave a gap between feeling and reaction, and by steadying yourself you steady the whole scene.",
      other: "They look unruffled, but that's mastery, not suppression. They care about this — they're simply in the habit of tucking feeling underneath composure.",
      verdict: 'leanYes',
      verdictReason: "This king stands for mature, steady hands on the helm; things are moving in a good direction within control — favor steadiness over haste.",
    },
    reversed: {
      keywords: ['emotional manipulation', 'slow burn', 'cold treatment', 'false calm'],
      core: "Reversed, dark currents churn beneath the throne: the surface stays breezy while unprocessed hurt and anger smolder inside, surfacing as cold silence, barbed remarks, or steering people by their guilt. This person might be near you — or it might be you, saying \"I'm fine\" for far too long. Emotion doesn't vanish because you put a lid on it; it just comes back in a more expensive form.",
      daily: "Find a safe outlet for the feelings to move through today: write them down, talk to someone you trust, or sweat them out with exercise. Bottled up too long, the body protests — if chest tightness or insomnia has become chronic, see a doctor early.",
      love: "Watch for soft manipulation in the relationship: dredging up old scores, sour faces, punishing with silence. Whether you're giving it or taking it, call a stop to the cycle first — then talk becomes possible.",
      career: "A boss who shows nothing but keeps score in the dark makes the air unbreathable. Keep important communication in writing — it protects you and protects the work.",
      money: "Beware money pressure dressed up as friendship or family duty, and don't use money as a bargaining chip in emotional disputes. Keep accounts and affection on separate books, and both stay clean.",
      advice: 'Admit you do have feelings — then find them a safe way out.',
      past: "Emotion smoldered too long underneath this: fine on the surface, keeping score inside — accumulating into the undertow you're feeling today.",
      present: "What you're facing is a pot of false calm: your own \"I'm fine,\" or theirs, has run too long. Find the feelings an outlet first.",
      other: "They're calm on the surface while emotion moves underneath. What they say aloud and what they feel inside may not be the same thing.",
      verdict: 'leanNo',
      verdictReason: "Reversed, emotions and manipulation are churning below the table; things are less calm than they look — nod too quickly and you'll pay for it.",
    },
  },
]
