// English content: cups-01 … cups-07 (7 cards).
// name/nameEn/ids MUST mirror the zh files and registry; verdicts MUST match zh.
import type { TarotCard } from '../types'

export const cups0107: TarotCard[] = [
  {
    id: 'cups-01',
    name: '聖杯一',
    nameEn: 'Ace of Cups',
    arcana: 'minor',
    suit: 'cups',
    rank: 1,
    number: 1,
    scene: 'A hand reaches out of a cloud holding a golden cup that overflows, five streams of water spilling into a pool of lotus blossoms below, while a white dove carrying a small wafer descends toward the rim and droplets scatter through the air.',
    upright: {
      keywords: ['new feelings', 'love overflowing', 'intuition', 'a full heart'],
      core: "A cup so full it spills over — that is this card's whole picture. A feeling, a connection, a creative spark is welling up from inside you on its own. You don't have to squeeze anything out; you only have to open your heart and catch it. Whether it's a new romance, a relationship on the mend, or falling back in love with life itself, right now you have the capacity to love — and you deserve to be loved back.",
      daily: "Let feeling walk ahead of thinking today, just once. If there's someone you've been meaning to thank or check in on, don't keep it in your head — say it out loud or send the message. One sincere sentence can soften your whole day.",
      love: "If you're single, your heart is opening again and a flutter-worthy meeting may be near. If you're together, say the tender things you're usually too shy to say — let the feeling flow between you again.",
      career: 'Work you genuinely love may land in your lap — a project or collaboration that lights you up. Creative and people-facing roles are especially favored; work done with real warmth shows in the result.',
      money: 'Money flows more generously now — a gift or an unexpected windfall is possible. Spending on what nourishes you and your family will repay you better than hoarding it.',
      advice: 'Open your heart and offer something sincere first — it will flow back sooner than you think.',
      past: 'It all began with a moment of genuine feeling — a spark, an honest exchange. What welled up naturally back then is the water that grew this into what it is now.',
      present: "Love and inspiration are flowing toward you. The task right now is to open up and receive them — not to question whether you deserve them.",
      other: "Their heart is stirring: real feelings are surfacing, and they're willing to open up — just with the slight shyness of something newly sprouted.",
      verdict: 'yes',
      verdictReason: 'The Ace of Cups is a wellspring of feeling and opportunity at once — clear, abundant energy that answers most questions with a firm yes.',
    },
    reversed: {
      keywords: ['blocked feelings', 'an empty cup', 'suppression', 'love left unsaid'],
      core: "Reversed, the cup tips downward — whatever pours in won't stay. You may have been giving until you feel hollow, or feeling things deeply but unable to say them, packing it all away inside. What's blocked isn't love itself; it's the channel for expressing it. Tend to your own cup first: rest, admit what has hurt, talk to someone you trust. Once the cup stands upright again, feeling will have somewhere to go.",
      daily: "Don't force yourself to be gracious with everyone today. Take ten minutes alone and ask yourself where you've been feeling empty lately — write it down. Settling your own feelings matters more than holding a smile in place.",
      love: "You may feel your giving goes unanswered — or you may not actually be ready to invest. First figure out which it is: are they failing to receive it, or have you never truly sent your heart out?",
      career: "The spark for your current work has drained away. Rather than white-knuckling it, go find the thing that made you choose this field in the first place, or talk to your manager about reshaping the role.",
      money: "It's easy right now to fill an inner emptiness with shopping — and feel emptier afterward. Before you buy, ask one question: do I need this, or do I need comforting?",
      advice: 'Set your own cup upright and fill it first — then decide whose cup you want to pour for.',
      past: 'For a while you tucked all your feelings away, and the things left unsaid — affection and grievance alike — quietly clogged everything that came after.',
      present: "Your cup is empty or overturned right now. Settle your own emotions and clear the channel for expressing them — don't rush to pour yourself out for anyone else yet.",
      other: "Their feelings are dammed up inside. It's not that they don't care — they can't get the words out, and their own emotions are still in a tangle.",
      verdict: 'leanNo',
      verdictReason: "The emotional flow is blocked; forcing things forward now just spins the wheels. Clear your own heart first, and the answer has a chance to turn.",
    },
  },
  {
    id: 'cups-02',
    name: '聖杯二',
    nameEn: 'Two of Cups',
    arcana: 'minor',
    suit: 'cups',
    rank: 2,
    number: 2,
    scene: 'A man and a woman stand face to face, each raising a cup toward the other in greeting; between them rises a staff entwined by two serpents, crowned with a winged red lion\'s head, with green hills and a small house in the distance.',
    upright: {
      keywords: ['mutual affection', 'alliance', 'mutual respect', 'hearts in accord'],
      core: "Two people walk toward each other, each holding a cup, neither standing above the other — this is a card about being equals. In love, it's affection that runs both ways and a willingness to open up; in work, it's mutual respect and terms both can agree on. The point isn't fireworks — it's that every gesture gets an answer. This connection deserves real care: say what you mean, and it takes its next step.",
      daily: 'Today favors anything that happens "between two people": meet the person you\'ve been wanting to see, settle the division of work with a colleague, extend an olive branch to a friend after a misunderstanding. Offer a little goodwill first — odds are it will be received.',
      love: "If you're single, the attraction you're sensing is likely mutual — don't get suspicious because it feels easy. If you're together, plan time for just the two of you and reaffirm what you mean to each other.",
      career: "One-on-one collaborations, negotiations and interviews are all favored — the key is laying each other's expectations on the table. A complementary partner beats going it alone.",
      money: "Joint ventures, splitting bills, negotiating pay — the terms come out fair now. Put money matters in writing, clearly, and the relationship will be stronger for it, not weaker.",
      advice: 'Spell out both your feelings and your terms — a relationship between equals is the kind that lasts.',
      past: 'This situation began with a meeting of equals: affection or collaboration that flowed both ways, laying the foundation for everything that followed.',
      present: 'There is a connection in front of you worth investing in. Now lay your feelings and expectations on the table, and let the relationship move a step forward.',
      other: "They are serious about this connection: their feelings match yours, they're willing to give and take, and they're waiting for a moment to talk things through.",
      verdict: 'yes',
      verdictReason: 'The Two of Cups is an image of hearts in accord and terms met as equals — every gesture answered. For questions of love or partnership, this is a good answer.',
    },
    reversed: {
      keywords: ['imbalance', 'together but apart', 'communication breakdown', 'one-sided giving'],
      core: "Tip one cup and the scales tilt: one side gives everything, the other only receives — or both stay polite while keeping private ledgers. This is imbalance and broken communication: small misunderstandings hardening into a knot, expectations never aligned. Don't pronounce the relationship dead yet. Say the thing you've been holding back — if talking works, repair; if not, put your weight back on yourself.",
      daily: 'Pay attention today to the relationship that\'s been quietly bothering you. Instead of keeping up the act, pick one small thing and open with: "That thing last time — it actually got to me." The odds of clearing the air are higher than you think.',
      love: "There may be a chase-and-retreat pattern, or a reconciliation in words that never reached the heart. First confirm you both want the same kind of relationship — then decide whether to repair or release.",
      career: "A crack has opened in a working relationship — uneven credit, perhaps, or information not flowing both ways. Put the grievance on the table; left to drag on, a small knot becomes a deep rift.",
      money: "In money matters you're prone to losing out because it feels awkward to speak up. Payments you're owed, bills to be split — settle them early, before money sours the relationship.",
      advice: "An unbalanced relationship needs an honest talk or a clean cut — don't stall in place, wearing yourself down.",
      past: 'The seed was an early imbalance: one side gave more, the other answered less, and expectations that never lined up slowly hardened into the knot you have now.',
      present: "You're at the tipping point of an unbalanced relationship. Focus on the sentence you've never said — talk it through and repair, or cut your losses.",
      other: "The scales in their heart have tipped: giving and receiving no longer match, or something's gone unsaid — courteous on the surface, a knot underneath.",
      verdict: 'leanNo',
      verdictReason: "The connection has cracked and expectations aren't aligned; keeping things as they are won't end well. Repair the communication first, and the answer may turn.",
    },
  },
  {
    id: 'cups-03',
    name: '聖杯三',
    nameEn: 'Three of Cups',
    arcana: 'minor',
    suit: 'cups',
    rank: 3,
    number: 3,
    scene: 'Three women dance in a circle, each raising a cup high, garlands of flowers in their hair, grapes and gourds scattered at their feet, with a bountiful harvest field behind them.',
    upright: {
      keywords: ['celebration', 'friendship', 'reunion', 'harvest time'],
      core: "Time to raise a glass. The Three of Cups paints the festival after the harvest: something has come to a good close, worth celebrating with the people you care about. And good news isn't complete until it's shared — friends, companions, community are this card's real treasure. Don't grind away alone. Step into the crowd: joy doubles there, and opportunity often hides in the moment the glasses clink.",
      daily: "Don't eat lunch alone today. Gather friends or colleagues — celebrating something small still counts — and if someone helped you recently, thank them in person while you're at it. The chemistry of people coming together is today's source of luck.",
      love: "If you're single, your chances are hiding in gatherings and friends' introductions — get out more. If you're together, bring your partner into your circle and let more blessings surround the relationship.",
      career: 'Team spirit is running high — a smooth project wrap-up, a celebration, public recognition are all in reach. Share the credit generously; goodwill is your next opportunity.',
      money: "Expect some spending on treats, dinners and gifts for occasions — money spent on people is an investment right now. A friend's introduction could also bring income your way.",
      advice: "Tell people your good news and celebrate together — don't keep the joy to yourself.",
      past: 'An earlier stretch of good harvest, plus the support of friends and companions, built up the goodwill and confidence you now stand on.',
      present: "Something good is coming to a close. Don't hoard it behind a shut door — carry the win into the crowd and celebrate; joy and opportunity will both multiply.",
      other: "They've been in bright spirits lately, happy to share the fun — and you're on the list of people they want to celebrate with. The mood is easy and friendly.",
      verdict: 'leanYes',
      verdictReason: "This is a card of celebration and harvest — things are wrapping up well. As long as you don't shut yourself away, the outcome is worth looking forward to.",
    },
    reversed: {
      keywords: ['overindulgence', 'clique gossip', 'lonely in a crowd', 'a third party'],
      core: "The emptiness after the party ends — that's the undertone of the reversed Three of Cups. Maybe too much socializing has your body and wallet protesting. Maybe whispers and cliques have formed in the group, leaving you lonelier in the crowd than out of it. In love, watch for the shadow of a third person. Step back and curate the relationships that truly nourish you — fewer gatherings is fine; false closeness is not.",
      daily: "Decline one take-it-or-leave-it invitation today. Give the reclaimed time to yourself, or to the one or two people you actually want to see. And if gossip about someone reaches you, let it stop with you — don't be the megaphone.",
      love: "Outside interference may be reaching this relationship — over-eager friends and family, or a third person with blurry intentions. Set the boundary yourself; what's between two people shouldn't be put to a vote.",
      career: "Office rumors and factions are exhausting — keep your distance from the whirlpool. Be selective about the social rounds, and save your energy for the work that actually shows.",
      money: "Spending on food, drink and fun is slipping out of control — the bills will tell the story. Cap the entertainment budget this week; a friendship won't thin out because you skipped one round.",
      advice: 'Curate your gatherings and your circle — keep your time for the people you can truly open up to.',
      past: "The old festivities left a hangover: too many obligations, whispers inside the circle, or a third person's shadow stirring up what used to be simple.",
      present: "You feel lonelier in the crowd than out of it right now. The task is to filter your gatherings and relationships, and save your time for genuine connection.",
      other: "They're wrapped in noise and bustle — present in the crowd, a little hollow inside — and the attention they had for this relationship is being pulled away.",
      verdict: 'leanNo',
      verdictReason: "Beneath the liveliness sit waste and static — gossip and overindulgence are diluting your energy, and the current setup works against the answer you want.",
    },
  },
  {
    id: 'cups-04',
    name: '聖杯四',
    nameEn: 'Four of Cups',
    arcana: 'minor',
    suit: 'cups',
    rank: 4,
    number: 4,
    scene: 'A young man sits cross-legged beneath a tree, arms folded and eyes cast down, three cups standing on the grass before him while a hand reaches out of a cloud offering a fourth cup he does not see.',
    upright: {
      keywords: ['apathy', 'numbness', 're-evaluation', 'the unseen cup'],
      core: "Three cups sit in plain view, a fourth is offered from the clouds — yet the figure folds his arms, refusing to look. The Four of Cups is the heart's off-season. It isn't that you lack options — nothing on offer stirs you. That numbness is a signal: stop and re-evaluate what you truly want. Just don't keep your eyes closed too long. The new cup is already at arm's reach — look up before deciding whether to take it.",
      daily: "If everything feels sluggish today, allow yourself a stretch of blank time — but set an alarm. When it rings, take an honest look at the invitations and opportunities you've been leaving on read lately. One of them might deserve a yes.",
      love: "The relationship feels flat — maybe the routine has gone stale, or maybe your attention is fixed on some ache inside you. Try noticing what's good about the person in front of you, right now.",
      career: "Work has entered the numb zone, and the sameness of the days has you questioning the point. Don't rush to quit. First list three things this job can still give you — then decide whether to stay or go.",
      money: "You can't summon any interest in your finances, so the money just sits. Stability isn't bad, but don't let sheer inertia make you miss a position that needs adjusting or a better option.",
      advice: "Look up at the cup being offered from the clouds — opportunities don't wait forever.",
      past: "The weariness didn't happen in a day: a long stretch of sameness and low spark led you to leave cup after cup on read.",
      present: "You're in the trough of numbness right now. The lesson is not to keep your eyes closed too long — the new cup in the clouds is already at arm's reach. Look up at it.",
      other: "They're in an off-season of their own — nothing in front of them holds any appeal, and their heart has closed temporarily to take stock. It isn't aimed at anyone.",
      verdict: 'leanNo',
      verdictReason: "This card's keynote is numbness and stalling — when the heart isn't in it, things naturally don't move. Unless you're willing to look up, the answer leans toward holding off.",
    },
    reversed: {
      keywords: ['awakening', 'out of the slump', 'motivation returning', 'accepting the new'],
      core: "The figure under the tree finally opens his eyes. The reversed Four of Cups is the moment of waking from weariness: a heart long shut in wants to move again, things that felt dull have their flavor back, or you've at last noticed the cup that's been held out in front of you all along. This urge to change is precious — while it's still warm, arrange one small fresh thing for yourself and let the energy flow again.",
      daily: "Today is made for breaking routine: take a different route to work, message a friend you haven't talked to in ages, sign up for the class you've been eyeing forever. The slump is on its way out — greet the returning momentum with one concrete new attempt.",
      love: "The numbness around love is loosening. If you're single, the willingness to meet people is back; if you're together, you feel like putting effort into the relationship again. Tell them about this awakening.",
      career: "You've finally worked out what was jamming you, and motivation is flowing back. The shelved proposal, the idea of a change — now is the time to bring them back out and evaluate them seriously.",
      money: "Your money mindset is shifting from 'whatever' to 'let's sort this out.' While the momentum is good, take inventory — accounts, insurance, subscriptions — and you'll find plenty worth adjusting.",
      advice: 'While the momentum is back, line up one small fresh thing and do it right away.',
      past: 'You sat under that tree for quite a while — and that stretch of blankness and re-evaluation quietly clarified what you truly want.',
      present: 'A heart long shut in is waking up. While the urge to change is still warm, arrange one small fresh thing and let the energy flow again.',
      other: "After a long stretch of shutting down, they're waking up — interested in the world again, and starting to notice the cup that's been offered to them all along.",
      verdict: 'leanYes',
      verdictReason: 'The weariness is receding and drive is flowing back. As long as you actually get moving, things will loosen in a good direction — this leans toward yes.',
    },
  },
  {
    id: 'cups-05',
    name: '聖杯五',
    nameEn: 'Five of Cups',
    arcana: 'minor',
    suit: 'cups',
    rank: 5,
    number: 5,
    scene: 'A figure in a black cloak stands with head bowed before three overturned cups, their contents spilled across the ground, while two cups still stand intact behind him; a bridge crosses the river toward a tower on the far bank.',
    upright: {
      keywords: ['loss', 'grief', 'the cups that remain', 'an unfinished road'],
      core: "Three cups really did fall, and grieving is right — the Five of Cups won't ask you to pretend otherwise. It paints the mourning that follows loss: a relationship, a chance, a trust spilled on the ground, and you need time to stand there and be sad a while. But two cups still stand behind you, and there is a bridge across the river. When the tears are done, turn around, hold close what remains, and the road goes on.",
      daily: "If low feelings visit today, don't rush to chase them off — give yourself a quiet half hour to properly feel them. Then take a sheet of paper: on the left, write what you've lost; on the right, what you still have. The right-hand column is tomorrow's starting point.",
      love: "You may be in the aftermath of disappointment, a fight, or a parting. Let yourself grieve — but don't condemn the whole relationship. Look back: the parts still standing may yet be mendable.",
      career: "A project fell through, or your effort went unseen — the sting is real. Review what happened, yes; write yourself off entirely, no. This lesson is exactly the two cups you carry into the next round.",
      money: "There may be a loss, or money spent for nothing, and it stings. After cutting the loss, don't rush to win it back — first take stock of the resources still in hand, steady yourself, then set out again.",
      advice: 'Grieve the spilled cups for a while — then turn around and hold the two that remain.',
      past: "The cause was a real loss: some cups truly fell and spilled. But the two still standing have walked with you all the way to now.",
      present: "You're standing before the spilled cups in mourning, and rightly so. When the crying is done, turn around — two cups still stand behind you.",
      other: "They're still submerged in some loss of their own — eyes fixed on the spilled cups, unable for now to see the good still standing behind them.",
      verdict: 'leanNo',
      verdictReason: "This card points honestly to loss and regret — things are unlikely to go as hoped. But the two intact cups remind you: it is not a total defeat.",
    },
    reversed: {
      keywords: ['letting go', 'out of the shadow', 'acceptance', 'back on the road'],
      core: "The figure in the cloak finally turns around — and sees the two cups still standing. The reversed Five of Cups is the tail end of mourning: the tears are mostly spent, you're starting to accept that it happened, and discovering you still have things, people, a road. Forgiving others counts; so does forgiving yourself. Cross the bridge — ahead lies not forgetting, but living on with what you've learned.",
      daily: "Today suits one small act of facing forward: let go of one old keepsake you've been unable to part with, answer the message you've put off forever, or simply tell yourself, 'I've set that down.' A lighter heart travels farther.",
      love: "The old wound is starting to scab over. If you're single, you're ready to meet people again; between partners who once fought, a window for reconciliation and drawing close again has opened.",
      career: "You're stepping out of failure's shadow, and the place you fell has become your strength. Plans for a fresh start carry experience this time — the odds are far better.",
      money: "The financial slump has bottomed out and steadied. The earlier losses taught you what risk actually looks like; replan with that maturity, and the money will come back, slowly.",
      advice: 'Forgive what needs forgiving — including yourself — then cross the bridge and keep walking.',
      past: "You walked the mourning honestly: the tears flowed, the facts were slowly accepted, and that healing laid the bridge across the river you stand on now.",
      present: "The task now is to finish the farewell: forgive who needs forgiving, yourself included, then carry what you've learned across the bridge.",
      other: "They're emerging from a period of grief — the tears mostly spent, the past being accepted, and slowly, room is opening up to draw close again.",
      verdict: 'leanYes',
      verdictReason: 'Release and recovery are underway — the low point has passed and the energy has turned toward rebuilding. Things have a real chance to open up well again.',
    },
  },
  {
    id: 'cups-06',
    name: '聖杯六',
    nameEn: 'Six of Cups',
    arcana: 'minor',
    suit: 'cups',
    rank: 6,
    number: 6,
    scene: 'In the courtyard of an old manor, a boy hands a cup filled with white flowers to a little girl; five more cups holding the same white blossoms stand around them, and in the distance a figure with a spear is walking away.',
    upright: {
      keywords: ['nostalgia', 'innocence', 'kindness', 'reunion with old friends'],
      core: "A child handing over a cup of white flowers — that is the heart of this card: kindness that asks nothing back, and the softest part of memory. An old friend may resurface, or a familiar place call you back; the warmth of the past is coming back to nourish you now. Receive it — and like that child, pass the kindness along. Good memories aren't for hiding in. They're here to remind you: you've always known how to love.",
      daily: "Let memory be your guide today: flip through old photos, eat something you loved as a kid, message a friend you haven't seen in far too long. The simple happiness you fish up from the past will make today feel softer.",
      love: "An old acquaintance or a first love may reappear — or your current partner may remind you of how the flutter first felt. Try being together with that old, unguarded sincerity.",
      career: "Old colleagues, old clients, connections from your school days bring opportunity. A familiar field is knocking again — the craft you've built up over years is worth more than you think.",
      money: "A gift or a hand from an elder or an old acquaintance may come your way. Nostalgia can pay, too — an old collection, an old skill, might be exactly what someone is looking for.",
      advice: 'Reach out to an old friend, and carry the warmth of memory back into the present.',
      past: "The root of this is old tenderness: a kindness given freely, an old bond, planted the sweet seed of what's happening now — long ago.",
      present: "The warmth of the past is coming back for you. Old friends, old places, old crafts are all worth receiving — and remember to pass the kindness onward.",
      other: "A nostalgic warmth is glowing in them: they remember the good moments you shared, carry a simple goodwill, and are open to drawing close again.",
      verdict: 'leanYes',
      verdictReason: 'Kindness, reunion, old bonds rekindled — all gentle, favorable signs. Things tend to come true in a warm way here, just not at a fast pace.',
    },
    reversed: {
      keywords: ['stuck in the past', 'gilded memories', 'refusing to grow up', 'time to say goodbye'],
      core: "Live in a memory too long and it turns from gift to cage. This may be the ex you can't put down, measuring today against 'back then,' or a childhood grievance made to explain every unhappiness now. The past did shape you — but life can only be lived forward. Give thanks where thanks are due, grieve what needs grieving, then give your eyes back to the present. It, too, holds people and things worth your care.",
      daily: 'Practice catching yourself once today in a "back in the day" spiral. The moment you notice the comparing start, take a breath and name three good things that actually exist in front of you — pull your attention back to now.',
      love: "Measuring your partner against an ex, or pining for an old love, will drain the warmth from what's in front of you. Put the old template away — this person deserves to be met fresh.",
      career: '"This is how we\'ve always done it" is what\'s tripping you now — old methods don\'t always fit a new game. Set down the baggage of past success, and you become able to learn again.',
      money: "Watch for financial arrangements kept out of pure sentiment — the account that's sat untouched for years, the old plan that stopped being a good deal long ago. If it needs reviewing, review it.",
      advice: 'Thank the past properly and say goodbye — then spend your strength on the present.',
      past: "It began with a past you couldn't put down: comparing now to then, polishing the memories ever brighter, while the present got left out in the cold.",
      present: "Your task now is moving out of the memory: thank the past, say goodbye, and give your eyes back to the people and things here that deserve your attention.",
      other: "Their heart still lives in the past: measuring now against the old days, unable to focus on the relationship in front of them — body here, heart in yesterday.",
      verdict: 'neutral',
      verdictReason: "The energy is caught in the past and the matter itself is undecided — it hinges on whether you'll bring your gaze back to the present. No clear yes or no right now.",
    },
  },
  {
    id: 'cups-07',
    name: '聖杯七',
    nameEn: 'Seven of Cups',
    arcana: 'minor',
    suit: 'cups',
    rank: 7,
    number: 7,
    scene: 'A dark silhouette gazes up at seven cups floating in the clouds, each holding a vision — a head, a shrouded glowing figure, a snake, a castle, jewels, a laurel wreath, a dragon — and a skull shows faintly on the cup bearing the wreath.',
    upright: {
      keywords: ['fantasy', 'too many choices', 'castles in the air', 'look before you choose'],
      core: "Seven cups drift on the clouds, each one glittering: love, wealth, glory, thrills… you want them all — and each is still just a mirage. The Seven of Cups is about being paralyzed by too many choices, and about the gap between imagining and living. Dreams are worth having, but a cup on a cloud can't be held. Pick one, carry it down to the ground, write out the first step — and set the rest aside for now.",
      daily: 'No new to-dos, no new daydreams today. Write down every option that "seems pretty good," cut the list until one remains, then do fifteen minutes of real homework on it. One round of doing beats ten rounds of imagining.',
      love: "Your picture of this relationship may be running ahead of what you actually know — casting them as the ideal in your head. However dreamy the blueprint, it has to be tested in real time spent together.",
      career: "Ideas and opportunities everywhere, and you want to grab them all — so nothing lands. Filter by feasibility and cost, commit to one, and produce something visible before entertaining the rest.",
      money: "Beware the too-beautiful investment story — cloud castles promising high returns usually hide a skull at the bottom of the cup. Verify any opportunity's source before you put anything in.",
      advice: 'Out of all the options swirling overhead, choose one — and take a real first step on the ground.',
      past: "Too many options were opened at the start: every cup wanted, every dream too dear to cut — that's how the matter has hung in mid-air until now.",
      present: 'A skyful of cups is still floating on the clouds. What to do now is choose one and carry it down to earth: write out the first step, and set the rest aside.',
      other: "Their head is full of ideas, all still up in the clouds: many imaginings about this relationship, and too many options to settle on any one.",
      verdict: 'neutral',
      verdictReason: "Everything is still at the stage of visions and options — nothing is settled. The answer depends on whether you choose and act; right now it can't be called either way.",
    },
    reversed: {
      keywords: ['illusions dissolving', 'resolve', 'back to reality', 'clear aim'],
      core: "The clouds part, and one by one the cups show their true shapes — which ones you truly want, and which were only pretty bubbles, you can finally tell apart. This card moves from fog into clarity: a long-hesitated choice finally lands, or an illusion that kept tempting you is seen through at last. While your head is clear, write the decision down and tell someone — let the commitment hold you on reality's track.",
      daily: "Today is right for making the decision you've long postponed. Write three pros and three cons for each of two or three options, choose one with your eyes open, then announce it to a friend. Said out loud, it's already half real.",
      love: "The filter falling off isn't necessarily bad: you see who they really are, and you know more clearly what kind of relationship you want. A decision built on what's real is the kind that stands.",
      career: "The direction has sharpened from blur to focus — you know which patch to cultivate now. Cut the extra side projects, concentrate your fire, and progress will suddenly speed up.",
      money: "You've seen the truth of some investment or expense — if it's time to exit, exit cleanly. Gather your funds back into the things you genuinely understand.",
      advice: 'While your head is clear, lock the decision in — and say it out loud to someone.',
      past: 'That earlier fog served a purpose: the detours taken and the bubbles seen through washed out what you truly want.',
      present: "The clouds are parting and the cups show their true shapes. While your mind is clear, nail down the long-circled decision — spoken aloud, it's already half real.",
      other: "Their fog is lifting: they've seen what they truly want, the decision has taken shape inside — all that's left is the step of saying it out loud.",
      verdict: 'leanYes',
      verdictReason: 'The fog is lifting and the direction has turned clear — conditions for deciding are ripe. Act with that clarity, and the outcome tilts in your favor.',
    },
  },
]
