// English content: major-11 … major-21 (11 cards).
// Meaning source: the zh file src/content/major-11-21.ts — natural English rewrite, not literal translation.
// name/nameEn/ids MUST mirror the zh files and registry; verdicts MUST match zh.
import type { TarotCard } from '../types'

export const major1121: TarotCard[] = [
  {
    id: 'major-11',
    name: '正義',
    nameEn: 'Justice',
    arcana: 'major',
    number: 11,
    scene: 'A red-robed figure sits squarely between two stone pillars in a square crown, right hand raising an unsheathed sword, left hand holding a set of scales, a purple veil hung between the pillars and a white shoe tip showing beneath the robe.',
    upright: {
      keywords: ['fairness', 'cause and effect', 'truth', 'accountability'],
      core: "The sword and the scales spell out the rule: see the facts clearly first, then pass judgment. Justice points to a moment of reckoning — what you've given and what you've promised are all going on the scale now. If you've acted in good faith, scrutiny holds no fear for you. If there's something on your conscience, this is the best possible moment to face it honestly and settle the account.",
      daily: "Handle things on the merits today — set feelings aside and let the numbers, records and facts do the talking. If there's an unresolved agreement or an unsettled bill hanging around, pick the smallest one and close it out before the day ends.",
      love: "Love asks for an even exchange: effort and response, freedom and commitment all go on the scale. If single, look past the résumé to their integrity; if together, air the imbalance you've been carrying.",
      career: "Contracts, reviews, negotiations — rule-bound arenas favor you now, provided your documents and data can survive inspection. Do your homework in full before you argue your case.",
      money: 'Keep the books clean, not fuzzy: get loans in writing and read every clause before signing. What you sowed financially in the past is coming back to you now as profit or loss.',
      advice: 'Lay the facts out plainly and make a decision you would be willing to answer for later, in full.',
      past: "Looking back, there's a paper trail to how things got here: every choice and promise made then was quietly recorded, and now the accounts are being reconciled.",
      present: "You're the one being weighed right now, and emotion won't help. Lay out the facts and records, make sure your own footing is solid, and only then talk about winning.",
      other: "They're in a measuring frame of mind — a scale in their head, weighing what each side has given and received here, and they take keeping one's word seriously.",
      verdict: 'neutral',
      verdictReason: "Justice favors no one; the answer depends on the causes you've already set in motion. If your record is clean, the ruling helps you — if there's a debt, settle it first.",
    },
    reversed: {
      keywords: ['unfairness', 'bias', 'dodged responsibility', 'imbalance'],
      core: "Reversed, the scales are tilted: you may be on the receiving end of unfair treatment, or your own judgment may have a thumb on the scale. Someone doesn't want to face the consequences, so the blame goes to luck or to other people. Before you rush to demand justice, check whether your evidence and your standing actually hold up — and if there's a fault to admit, admitting it early costs the least.",
      daily: "You may run into double standards today; don't rush to fight it on emotion. Document what happens, keep the receipts, and file your case only once the information is complete — your odds improve enormously.",
      love: "The giving in this relationship may have been lopsided for a long time — one side always yielding, the other taking it as normal. Stop buying peace with quiet resentment; say your real bottom line out loud.",
      career: 'Unfair reviews or stolen credit may play out. Keep records of your work and use formal channels when needed — that protects you far better than private complaining.',
      money: "Watch for contract traps and vague verbal promises; any 'just sign first' deserves suspicion. If a dispute arises, professional advice beats swallowing the loss alone.",
      advice: 'Gather your evidence and clarify who owns what first — then decide whether to fight or to let go.',
      past: 'A ruling back there was not fair — maybe you were shortchanged, maybe your own heart tipped the scale — and that crooked balance has carried through to now.',
      present: 'The scale before you is visibly tilted; demanding justice in a hurry will cost you. Keep evidence, clarify responsibility, and set the balance straight first.',
      other: 'That person feels something is unfair — maybe wronged, maybe dodging a responsibility they should face. Either way, their scale is still crooked.',
      verdict: 'leanNo',
      verdictReason: 'Reversed Justice shows a tilted field — dishonesty or a flawed process is in play. Forcing an outcome now invites loss; correct the imbalance first.',
    },
  },
  {
    id: 'major-12',
    name: '吊人',
    nameEn: 'The Hanged Man',
    arcana: 'major',
    number: 12,
    scene: 'A man hangs upside down from a T-shaped living gallows, bound by his right foot, his left leg crossed to form a figure four, hands held behind his back, his head ringed in a golden halo, his face serene.',
    upright: {
      keywords: ['pause', 'new perspective', 'surrender', 'waiting'],
      core: "The Hanged Man chose to hang there — his face is calm and there's light around his head. This card isn't about being trapped; it's about pressing pause on purpose. Some answers simply can't be seen while you're charging forward; you have to turn the world upside down once to find them. The standstill you're in has a point: what you're letting go of is buying you a deeper way of seeing.",
      daily: "Whatever won't budge today, stop forcing it. Spend that energy on changing your angle instead — ask yourself, 'if I were them, how would this look?' Until the answer arrives, give yourself permission to hang quietly.",
      love: "A slowdown isn't necessarily bad news; the relationship needs time to settle. Rather than pressing for an outcome, try to understand why the other person is stuck. Waiting is a form of giving too.",
      career: "A stalled project or blocked promotion isn't your cue to jump ship. Use the lull to study and take stock — you'll spot problems from your blind spot, and things will loosen when the timing comes.",
      money: "Defend rather than attack: this stalemate is not the place to double down. Park your money somewhere safe and act once the view clears — there's no penalty for waiting.",
      advice: 'Staying still is also a choice. Use this stretch of time to trade your old angle for a new one.',
      past: "That stretch of apparent standstill wasn't wasted: you changed your angle while you waited, and the understanding you carry now grew out of exactly that pause.",
      present: "Things won't move right now — not because you should push harder, but because you should look at them upside down. Hang calmly; a new perspective is taking shape.",
      other: "They're in a voluntary pause: not wanting to move things forward for now, taking time to see it from another angle. That quietness is not the same as coldness.",
      verdict: 'neutral',
      verdictReason: "The Hanged Man's energy is suspension and waiting — nothing can be decided yet. Ask the question from a different angle and you'll get closer to the answer.",
    },
    reversed: {
      keywords: ['pointless sacrifice', 'stalling', 'refusing to let go', 'stagnation'],
      core: "Hang upside down too long and you go numb. The reversed Hanged Man usually means one of two traps: sacrifice has become a habit — you keep giving and get no recognition at all — or a decision that needs making has been shelved indefinitely, with 'just a bit longer' standing in for a choice. The pause was meant to be a means; it has quietly become the end. Ask yourself: what is this indecision actually protecting?",
      daily: "Audit the things you've been 'waiting on' for ages: which one is not actually waiting, but stalling? Pick one, give it a hard deadline, and then act on that deadline.",
      love: "One-sided forbearance is near its limit, and the other person may not even have noticed your hurt. Stop proving love through sacrifice — state your needs plainly, and the relationship gets a chance to move.",
      career: "You've given your all and the payoff never arrives — time to ask whether this waiting is worth it. Write your stop-loss point down in black and white, and when the clock runs out, start the next move.",
      money: "Stop soothing an underwater position with 'it'll come back' — go re-check the fundamentals. Taking the loss is sometimes how you stop the bleeding; move the resources somewhere with real prospects.",
      advice: 'Learn to tell waiting from stalling — and stop pushing back the decision you already know you need to make.',
      past: 'The deadlock was stalled into being: decisions kept getting postponed, effort kept going unrecognized, and hanging in limbo slowly hardened into a habit.',
      present: "You're stuck in a wait that lost its meaning long ago, letting 'just a bit longer' stand in for a choice. Give the thing left hanging a firm deadline.",
      other: "That person has been suspended in place for a while — decisions postponed again and again. It's not that they don't care; inertia and hesitation have them pinned.",
      verdict: 'leanNo',
      verdictReason: 'The reversed Hanged Man shows a standstill that no longer serves you — the sacrifice buys no progress, and dragging it out only drains. The status quo is not worth extending.',
    },
  },
  {
    id: 'major-13',
    name: '死神',
    nameEn: 'Death',
    arcana: 'major',
    number: 13,
    scene: 'A skeleton knight in black armor rides a white horse, bearing a black banner with a white rose; a king lies fallen, a bishop stands with pressed hands, a maiden turns away, a child offers flowers, and the sun rises between two far towers.',
    upright: {
      keywords: ['ending', 'transformation', 'letting go', 'rebirth'],
      core: "Death doesn't negotiate — but look behind him: between the two towers, the sun is rising. This card announces that a chapter has truly ended — a relationship, a job, or an old version of you. Resisting only stretches out the pain. The real work is a proper goodbye: gather what should be kept, thank what deserves thanks, and then turn around. The space an ending clears is the ground the new thing is built on.",
      daily: "Today is made for clearing out: delete the contacts you'll never message, get rid of things you stopped using long ago, or formally close something that's been dragging on. Each thing you release buys a little more lightness for the road ahead.",
      love: "A relationship may be reaching its end, or an old way of being together needs to be allowed to die. Be honest about where things truly stand — ending it cleanly is how you honor what was once real.",
      career: 'A role, a project, or the whole track may be closing down. Rather than guarding a door that is swinging shut, pack up the experience and take it with you — your next chapter will need exactly that nourishment.',
      money: "An income stream or an investment may have run its course — if it's time to cut the loss, cut it. Pull your money out of what has withered and redeploy it into something with life in it.",
      advice: 'A good ending matters more than a forced continuation. Let go, and the road will appear.',
      past: "A chapter truly closed back there — a relationship, or an old self, ran its course. That ending is what cleared the ground you're standing on now.",
      present: 'A farewell is underway, and resisting only prolongs the ache. Gather what should be kept, thank what deserves thanks — nothing matters more right now.',
      other: "A chapter is closing inside them: they're busy saying goodbye to something old, their attention on sorting and releasing rather than on opening anything new.",
      verdict: 'no',
      verdictReason: 'Death points to a definite ending — things cannot continue in their old form. The ending itself is the answer to this question, and it is also where the new chapter begins.',
    },
    reversed: {
      keywords: ['stalled ending', 'resisting change', 'unresolved', 'lingering ties'],
      core: "The reversed Death is a farewell that has dragged on far too long: everyone knows it's over, but no one is willing to say it first. You may be clinging to a relationship that soured long ago or a job that's been ground down to nothing, letting inertia stand in for a choice. Change doesn't get cancelled because you close your eyes — it just comes back knocking, each time more exhausting than the last.",
      daily: "Ask yourself honestly, just once today: is there something in your life you've known for a while should end? You don't have to act on it yet. Write it down, admit that it exists — that alone is where the loosening starts.",
      love: "An old flame never fully put out, a relationship in name only — these drain the energy you'd need to welcome someone new. Turn that page inside yourself first; only then can you truly walk out.",
      career: "You know it's time to go, yet you can't make yourself move — the fear looms larger than the reality. Start small: refresh the résumé, test the market. Give the change a ramp to walk down.",
      money: "A loss you refuse to look at won't dissolve on its own, and the longer you wait, the more it costs. Set yourself a review deadline and settle the old financial accounts in one sitting.",
      advice: 'Admit that what should have ended already has — and start loosening your grip in small steps.',
      past: 'Something that should have ended long ago was left dragging, unresolved. That lingering, half-severed tie has seeped all the way into the present situation.',
      present: "You're wedged between the old unfinished and the new unborn, and inertia still holds you. Admit the ending has already happened — letting go unlocks the next step.",
      other: "Something in their heart should have been laid to rest long ago, and they can't quite put it down. They know the page needs turning, yet it stays unturned.",
      verdict: 'neutral',
      verdictReason: 'Reversed Death is suspended: the old unfinished, the new unborn. Asking for an outcome now is premature — the answer depends on when you become willing to let go.',
    },
  },
  {
    id: 'major-14',
    name: '節制',
    nameEn: 'Temperance',
    arcana: 'major',
    number: 14,
    scene: "A red-winged angel stands at the water's edge, one foot in the pool and one on land, pouring water between two golden cups, an orange triangle on its chest, irises blooming, and a path leading toward a glowing gap in distant mountains.",
    upright: {
      keywords: ['balance', 'blending', 'patience', 'right pace'],
      core: "The angel stands with one foot in the water and one on land, and the stream between the two cups never breaks — Temperance is the art of just enough. What you need right now is neither flooring the accelerator nor slamming the brakes, but finding your own cruising speed: work and rest, head and heart, giving and holding back. Adjust slowly, without hurry. When the proportions are right, everything starts to flow.",
      daily: "Tune the recipe of your day: if the schedule is overstuffed, cut one thing; if you've drifted too long, add one solid task back in. Eat, walk and speak at half a beat slower — get the rhythm right and the efficiency follows on its own.",
      love: "The relationship is in its calibration phase: one quick, one slow — neither is wrong; refusing to adjust is what's wrong. Listen more, yield half a step, and your frequencies will gradually come into tune.",
      career: 'Coordinating across teams and pooling resources is your strength right now — playing the bridge will pay off. Take steady small steps on progress; that carries you farther than sprinting.',
      money: 'Your finances are finding their balance again — keep the slow-and-steady discipline: regular contributions, living within your means. Avoid extreme moves; a middle-of-the-road allocation suits this moment best.',
      advice: 'Find the pace that is genuinely yours, and adjust the proportions without rushing or stopping.',
      past: 'A patient, unhurried period of blending laid the foundation: proportions dialed in drop by drop back then are precisely why you can stand steady now.',
      present: "The task of the moment is pacing: work and rest, giving and holding back all need re-mixing. Don't sprint and don't stall — the job is getting your rhythm back.",
      other: "They're calm and even right now, gently adjusting the rhythm between you — willing to compromise, willing to wait, in no hurry to promise more than they can hold.",
      verdict: 'leanYes',
      verdictReason: "Temperance is the energy of blending and flow — things are merging in a steady direction. As long as you don't force the pace, this tends to come together naturally.",
    },
    reversed: {
      keywords: ['imbalance', 'excess', 'impatience', 'extremes'],
      core: "The water has sloshed over the rim. Reversed Temperance flags a part of your life that's out of proportion: work swallowing rest, appetite overriding restraint, or moods swinging between two extremes. You're not blind to the problem — you've just kept telling yourself you can still hold on. Fix the recipe now, before the imbalance hardens into real damage.",
      daily: "Notice where you're running over the line today — coffee, overtime, doomscrolling, or promises you shouldn't have made. Pick the most obvious one and cut it by thirty percent on purpose; your body and mood will give you the verdict immediately.",
      love: 'The scale between you has tipped: one side managing too much or burning too hot, and the friction shows. Step back inside your own boundaries and catch your breath first — then talk about redividing the load.',
      career: "Too many horses pulling different directions, resources misplaced — grinding on only stockpiles mistakes. Stop, re-rank the priorities, cut what's overloading you, and then get back on the road.",
      money: 'Spending and investing both drift toward extremes now — bingeing and crash-austerity are equally damaging. If stress has taught you to shop on impulse, install a cooling-off period before you check out.',
      advice: 'Admit the overload for what it is: reduce the volume first, then rebuild the rhythm.',
      past: "The imbalance began with 'I can still hold on': one part of life ran past its limit too long, building drop by drop into the exhaustion you feel now.",
      present: "Something in excess is dragging you along — hours, emotions, or appetite. The honest first move is admitting you're overloaded; cutting back beats gutting it out.",
      other: "They've been off balance lately — burning too hard here, unable to keep up there, running hot and cold. It's almost certainly overload, not something aimed at you.",
      verdict: 'leanNo',
      verdictReason: 'Reversed Temperance shows proportions gone wrong and energy leaking away — on the current course, a good result is unlikely. Restore the balance first, then ask again.',
    },
  },
  {
    id: 'major-15',
    name: '惡魔',
    nameEn: 'The Devil',
    arcana: 'major',
    number: 15,
    scene: 'A horned devil squats on a black pedestal beneath an inverted pentagram, right hand raised, left hand pointing a torch downward; before him a naked man and woman wear loose chains, small horns on their heads and tails behind them.',
    upright: {
      keywords: ['bondage', 'addiction', 'desire', 'dependency'],
      core: "Look closely: those chains are loose, and the collars could be lifted off at any time. The Devil stands for the thing you know is bad for you and still can't leave — a draining relationship, a habit you're hooked on, a job that's only about the money now. The bondage holds precisely because it keeps paying you something sweet. Naming the reason you're choosing to stay is the first turn of the key.",
      daily: "Watch what hooks you today: the app that opens itself, the yes you gave while knowing better. No need to quit cold — just notice the moment the hook lands, and count three full seconds before you act.",
      love: "The passion is intense, but control or dependency may be mixed in — hard to tell love from inability to leave. Ask honestly whether this relationship makes you bigger or smaller. You already know the answer.",
      career: 'A high salary or comfortable stability can be golden handcuffs, keeping you tolerant of an unhealthy environment. Price out what the chain costs you first — then decide whether the trade is still worth it.',
      money: 'Beware traps baited with desire: too-good yields, mindless swiping, bets dressed as strategy. If a debt or habit has snowballed, getting professional help early is far wiser than toughing it out alone.',
      advice: 'Name the chain that binds you — and remember the key has been in your hand the whole time.',
      past: 'This situation began as a trade of sweetness for cost: an attachment that looked like a bargain at the time has quietly hardened into the chain you feel now.',
      present: "What binds you keeps paying you something sweet — that's why leaving is hard. See why you're choosing to stay, and you'll find the key is already in your hand.",
      other: "That person is caught on a powerful hook — desire, habit, or plain material interest. They know it's draining them, yet for the moment they can't quite walk away.",
      verdict: 'no',
      verdictReason: 'The Devil points to unhealthy attachment and a bad trade: following the craving feels good short-term and corrodes long-term. The direction of this question is not in your favor.',
    },
    reversed: {
      keywords: ['breaking free', 'awareness', 'withdrawal', 'reclaimed freedom'],
      core: "The chain is coming loose. The reversed Devil is the moment of waking up: you start to see that relationship, habit or obsession for what it really is, and the thought of leaving takes root. Withdrawal will be uncomfortable — the old inertia pulls, the sweetness keeps waving you back. Hold through the relapses and the freedom is yours; and bring someone along, because company beats white-knuckling it alone.",
      daily: 'A small detox suits today: cancel one subscription, delete one shopping app, or bow out of a dinner you never wanted to attend. Every little hook you shake off is practice for the bigger freedom.',
      love: "You've seen the entanglement clearly, and the strength to say no is growing in you. Leaving someone who drains you takes time and relapses — don't let one soft moment erase all the progress you've made.",
      career: "You've finally dared to look the toxicity in the eye and started mapping the exit. Job-hunting while employed is fair — the point is getting the leaving plan onto paper instead of rehearsing it in your head.",
      money: "Paying down the debt, breaking the bad spending habit — you're off to a strong start. Make the progress visible: track it, draw the progress bar. Nothing sustains resolve like improvement you can see.",
      advice: 'While the momentum of waking up is still warm, take the first real step out — and make it stick.',
      past: "You'd already sensed something was wrong and made attempts to loosen the knot. Those earlier tries at breaking free are exactly why you can see the exit now.",
      present: "The chain is loosening; withdrawal discomfort and the old habit's tug will both come. Hold through the relapses — don't let one soft moment undo it all.",
      other: "They're trying to break free of an entanglement, seeing what's been draining them. Their resolve still swings, but the direction is toward loosening the knot.",
      verdict: 'leanYes',
      verdictReason: 'The reversed Devil signals shackles coming loose: keep pulling free and things move toward liberation. Just stay alert to the old habit tugging you back.',
    },
  },
  {
    id: 'major-16',
    name: '塔',
    nameEn: 'The Tower',
    arcana: 'major',
    number: 16,
    scene: 'Against a grey-black night sky, lightning strikes a tower on a mountain peak, blasting the crown from its top; flames burst from the windows as two figures fall headfirst, and sparks of fire drift through the air around them.',
    upright: {
      keywords: ['sudden upheaval', 'collapse', 'exposed truth', 'rebuilding'],
      core: "Notice what the lightning strikes: the crown on top — what gets destroyed is usually a false order. The Tower arrives fast and hard: a sudden reversal, a truth that can't stay hidden, a structure that gives way overnight. The shock hurts, but what collapsed was never standing soundly. Crouch low, protect what matters most, and when the dust settles you may be glad the real foundation is finally showing.",
      daily: 'If something blows up today, deal with safety and damage control first — assigning blame can wait. Back up your important data, secure your key documents, give yourself ten minutes to breathe, and then come back to face the scene.',
      love: "Something hidden may suddenly land in the open, and the relationship takes a hard shock. Don't make any permanent decisions yet — let the emotional tide go out first, then look at what genuinely remains.",
      career: 'Reorgs and derailed projects can arrive with zero warning. What matters more than your title right now is the skill you can carry out the door — take stock of it, and be ready to stand back up anywhere.',
      money: "A sudden hole may open in your finances: a fine, a repair, an emergency. Don't begrudge tapping the emergency fund — this is exactly what it exists for. After the storm, rebuild the buffer thicker than before.",
      advice: 'Stop the losses and protect the essentials first. Rebuilding can wait until the dust has settled.',
      past: "The collapse already happened: a sudden upheaval tore down the old structure, and the situation you're in now started from exactly that pile of rubble.",
      present: "The shaking is happening now — don't rush to assign blame. Stop the losses and guard the essentials; what's falling was never standing soundly anyway.",
      other: 'That person has just been through — or is still inside — a violent upheaval. Barely holding together, what they say right now may not be their considered truth.',
      verdict: 'no',
      verdictReason: "The Tower means the existing structure is coming down — things won't go as planned. This no is the demolition of an unsafe building, clearing the way to rebuild on solid ground.",
    },
    reversed: {
      keywords: ['propping it up', 'delayed collapse', 'fear of change', 'aftershocks'],
      core: "The reversed Tower is still standing, but cracks have spread across every wall. You may be taping together something that needs rebuilding from scratch — a teetering relationship, a project riddled with problems — out of dread of the crash it would make. But delay doesn't cancel the earthquake; it only lets it pick a worse time. A deliberate dismantling is always gentler than a collapse you didn't choose.",
      daily: 'Look hard at one thing you keep patching — the kind that breaks after every fix, collapses after every talk. Honestly assess whether it deserves another round of propping up. If the answer is no, start planning an orderly exit today.',
      love: "You both feel that something's wrong, and you've silently agreed not to poke at it. Dodging the conversation only puts the pain on an installment plan — find a calm moment and say the true thing gently.",
      career: "The crisis has been tamped down but the root cause is still there — don't mistake quiet for peace. While you still have slack, propose the fix yourself; it's far more dignified than waiting for the blowup.",
      money: 'Books that barely balance may be hiding a structural problem. Stop robbing one wall to patch another — face the real gap between income and spending, and bring in professional help if you need it.',
      advice: "Don't wait for it to fall on you — take it down yourself, deliberately and in good order.",
      past: 'The cracks appeared long ago; they just kept getting patched over and painted out. The root problems nobody treated are what propped up the wobble you now stand in.',
      present: "You're propping up a structure you know is unsound, dreading the crash. While it still stands, plan the orderly dismantling — and the exit — on your own terms.",
      other: "Inside, they know some things are barely holding together. They're keeping the surface calm out of habit, not daring to be the one who points at the cracks first.",
      verdict: 'leanNo',
      verdictReason: 'The reversed Tower means the crisis is postponed, not resolved — the propped-up structure is still unsound. The direction is against you, but you still have time to act first.',
    },
  },
  {
    id: 'major-17',
    name: '星星',
    nameEn: 'The Star',
    arcana: 'major',
    number: 17,
    scene: "One great star ringed by seven smaller stars shines in the night sky; a naked woman kneels at a pool's edge, one foot on the water, pouring from two pitchers — one into the pool, one onto the land — while a bird perches in a distant tree.",
    upright: {
      keywords: ['hope', 'healing', 'inspiration', 'guidance'],
      core: "After the storm, the stars come out. The Star follows the Tower like a balm from the universe: wounds are starting to close, and water is flowing again where things had gone dry. It doesn't promise instant success — it gives you a direction worth following and the strength to keep walking. The wishes you make now, the intentions you set, will brighten the way starlight does: slowly, and surely.",
      daily: "Do one nourishing thing for yourself today: a long bath, a walk somewhere green, or writing a wish into your notebook. Don't force yourself to bounce back — healing keeps its own schedule. Your only job is to keep topping up the water.",
      love: "The forecast for love is warming: a heart that was hurt is willing to trust again. If you're single, stay open to what's ahead; if you're together, sketch a longer-range picture of the future side by side.",
      career: "Your ideals and vision are coming back into focus — a good time to invest in work with long-term meaning. The returns may not show yet, but the seeds you're planting are germinating in the right soil.",
      money: 'Financial pressure is gradually easing — a good moment to rebuild the plan. Set one long-term goal and save toward it steadily; that fits this season far better than chasing fast money.',
      advice: 'Turn your hope into one concrete long-term goal — then move a little closer to it every day.',
      past: "That slow recovery after the wound was not wasted: the wish you made then, the faith you managed to keep — that's exactly the light shining on you now.",
      present: "Healing is underway — don't rush it. The work now is steady watering: take care of yourself, and move a little closer each day to the direction that's worth it.",
      other: 'Their heart is in recovery: slowly becoming willing to trust again, holding a gentle, honest hope about what the future might bring.',
      verdict: 'leanYes',
      verdictReason: 'The Star signals hope and recovery: the direction is right and the outcome trends good — it simply needs time to steep, and cannot be hurried.',
    },
    reversed: {
      keywords: ['lost faith', 'pessimism', 'running on empty', 'dimmed hope'],
      core: "The pitchers are empty — nothing left to pour. The reversed Star describes soul-tiredness: not a disaster, but hope leaking away drop by drop — effort feels useless, the future unmoored. The star is still up there; clouds are just blocking it. Don't force optimism: hold the baseline of self-care, and if the low mood drags on and disrupts your life, seek professional mental health support or counseling early.",
      daily: "Stop scrolling the feeds that spike your anxiety today. Shrink your attention to three small things: eat one proper meal, get a full night's sleep, and talk with one person you trust. Recharge first — hope needs somewhere to live.",
      love: 'You may feel disheartened about love, or unnourished inside the relationship. Lower your expectations to an honest level, take care of yourself first — then decide whether to repair or to rest.',
      career: "Enthusiasm for the work is low, and it's easy to suspect you chose the wrong road. Hold off on major turns. Treat the burnout as a signal: schedule real rest, and try small experiments to get your feel back.",
      money: "Excessive gloom about your finances could make you miss opportunities — or spiral into careless spending. Come back to the actual numbers and judge from there; don't let your mood keep the books.",
      advice: 'Tend to your energy before demanding a comeback — and if the low stretch drags on, get professional help.',
      past: 'Hope leaked away slowly: a string of letdowns and steady depletion emptied the pitchers back then, and that weariness of heart has carried all the way into now.',
      present: "Your tank is near empty and the light is hard to see. Don't force optimism — secure food, sleep and a trusted ear first; if the low runs long, get professional help.",
      other: "Their energy is running low, and it's hard for them to summon faith in much of anything. It isn't that they don't care — their own pitcher emptied out first.",
      verdict: 'leanNo',
      verdictReason: 'The reversed Star shows confidence and energy both running low — pushing now yields half the result for double the effort. Refill the inner well first; the timing will come back.',
    },
  },
  {
    id: 'major-18',
    name: '月亮',
    nameEn: 'The Moon',
    arcana: 'major',
    number: 18,
    scene: 'A moon with a face hangs in the night sky, drops of light falling like dew; below, a dog and a wolf howl up at it, twin towers stand to either side, a crayfish crawls out of a pool, and a winding path stretches toward distant hills.',
    upright: {
      keywords: ['unease', 'fog', 'intuition', 'the subconscious'],
      core: "Moonlight lies: it turns rocks into beasts and hides beasts in shadow. The Moon marks a stretch where you can't see clearly — information is murky, something is being kept from you, or your own fear is amplifying every rustle in the grass. Don't rush to conclusions; daylight always comes. Treat intuition as a hint, not a verdict, and walk the winding path one verified step at a time.",
      daily: "Don't take today's news at face value, especially versions that reached you secondhand. Sleep on any major decision at least one night. If your thoughts churn after dark, write the worries down — by morning light they're rarely as fearsome.",
      love: "Ambiguity or suspicion has fogged the relationship: you can't read their mind, and your imagination keeps running further ahead. Instead of playing detective in your head, ask once — directly and gently.",
      career: 'Information at work is murky, and the rumors you hear are unlikely to be the whole picture. Take fewer sides, pass along fewer whispers, do your own work solidly — declare yourself after things clear.',
      money: "If you can't understand an investment, don't touch it — however tempting. Sales patter and information gaps abound right now; verify everything twice and protect what you have until the fog lifts.",
      advice: "Don't settle on conclusions before the fog lifts — replace imagination with verification.",
      past: 'This began in a stretch of poor visibility: information was murky then, things went unsaid, and that layer of fog has drifted all the way into the current situation.',
      present: "The moonlit path is an anxious walk — fear inflates every rustle along the way. Verify before you judge right now, and don't be hasty about drawing conclusions.",
      other: 'Their mind sits behind a layer of fog: some things unsaid, some anxieties quietly inflating inside — and even they may not see themselves clearly at the moment.',
      verdict: 'leanNo',
      verdictReason: 'The Moon is wrapped in uncertainty and hidden factors — what you see now may not be the truth, and a confident answer risks misjudgment. It leans toward wait and verify.',
    },
    reversed: {
      keywords: ['fog lifting', 'truth surfacing', 'relief', 'easing fears'],
      core: "The night is on its way out. The reversed Moon is usually the prelude to clearing skies: hidden things surface one by one, the suspicion that gripped you for so long starts to loosen, and you discover some of your fears were creatures you'd been feeding yourself. The truth may not be pretty, but knowing beats guessing. While the light improves, take out the judgments you'd shelved and recalibrate them one at a time.",
      daily: "Today is right for checking your open questions against reality: verify a rumor, or finally ask about the thing you've been holding in. You'll likely find the truth is much simpler than what you imagined — and feel your heart settle.",
      love: 'A misunderstanding can finally dissolve, and hidden words can be said properly. When the truth comes out, thank them for the honesty — going forward, transparency matters more than perfection.',
      career: 'The murky politics or unclear direction is resolving, and you can finally judge whether to stay or go. Update your plans with the new information — the watching and waiting can be wrapped up now.',
      money: "A financial blind spot has come into view — perhaps a hidden fee or a clause you'd misread. Once you understand it, adjust promptly; the allocation you didn't dare touch before can be moved now.",
      advice: 'While the view is clear, take out the decision you shelved long ago and finally call it.',
      past: 'The fog began lifting a while back: truths surfacing one after another loosened the old suspicions and carried you to this clearer vantage point you stand at now.',
      present: 'The light is improving, and questions that hung unanswered can finally be checked against reality. Take the judgments you shelved and recalibrate them one at a time.',
      other: "The fog inside them is thinning: words and doubts they'd bottled up are things they now want to lay on the table. Their posture is clearer than it was before.",
      verdict: 'leanYes',
      verdictReason: 'The reversed Moon means the fog is dispersing and the facts are surfacing — uncertainty is falling, and things are more solid than they previously appeared.',
    },
  },
  {
    id: 'major-19',
    name: '太陽',
    nameEn: 'The Sun',
    arcana: 'major',
    number: 19,
    scene: 'An enormous sun with a face beams down, its rays reaching in every direction; a naked child rides a white horse with arms spread wide, a long red banner streaming in the wind, and four sunflowers blooming atop the stone wall behind.',
    upright: {
      keywords: ['success', 'joy', 'vitality', 'openness'],
      core: "The brightest card in the deck. Under the Sun there are no shadows: the child rides the white horse with nothing to hide — this is the card of success, health and uncomplicated joy. Your work is having its moment of being seen, relationships return to open ground, body and mind are fully charged. Enjoy the light without apology — and like the sunflowers, keep turning toward the people and things that deserve it.",
      daily: "Let yourself shine a little today: wear the clothes you love, call the friend you've missed, and accept compliments without deflecting. Share the good news, do the thing you've wanted to do while the sun is up — your visibility is at a peak; don't waste it.",
      love: "Love is in glorious weather: if single, your charm is on full broadcast — make the generous first move. If together, a long-missed sweet spell is arriving; get out in the sun together and let things warm.",
      career: "Your results are surfacing where everyone can see them, and the applause is fully earned. It's a season for presenting, pitching, and claiming the stage — playing it open and straight will win you the most.",
      money: 'The financial picture is bright, and earlier cultivation is starting to pay: a bonus, a raise, or investment gains may all land. Budget a little for joy — and set a share aside in savings.',
      advice: 'Step into the light without apology, and let the right people see what is good in you.',
      past: "This brightness was earned: an honest, solid stretch of cultivation laid the base back then, and today's results and good spirits both grew up out of it.",
      present: "You're standing at your moment of highest visibility, and playing it open is the advantage. Show generously, share generously — don't let this sunlight go to waste.",
      other: "They're in a bright, open state right now: nothing much hidden, happy to come close without games, and glad to share the good mood around.",
      verdict: 'yes',
      verdictReason: 'The Sun is the clearest yes in the whole deck — the energy is radiant and abundant, and things are moving toward success and joy.',
    },
    reversed: {
      keywords: ['delayed good news', 'overcast', 'shaky confidence', 'overoptimism'],
      core: "The reversed Sun is only behind a cloud — it hasn't gone out. Good news may run late, the results may shine less than hoped, or you stand in the light feeling you don't deserve it. Or the flip side: optimism running ahead of details that needed handling. Either way, this remains a warm card at its core. The way to part the clouds is to face the small flaws honestly — and keep walking toward the bright side.",
      daily: "If you're feeling flat and unmotivated today, check the basics first: sleep, food, daylight. Get outside for a twenty-minute walk in the sun. Let the body light up first — the mood usually follows it home.",
      love: "The love is sound; the heat has just dipped, or things have gone flat. Don't leap to questioning the relationship — plan one stretch of time that belongs only to you two, and relight it.",
      career: "Your results are being seen later than they should, or the spotlight for the credit isn't landing on you. Keep building and market yourself in reasonable doses — the stage that's yours will be made up to you.",
      money: "Returns have shrunk or payments are running late, but the fundamentals aren't broken. Re-check any overly rosy projections, bring the numbers back to reality, and otherwise proceed exactly as planned.",
      advice: 'The good thing is merely late. Mind the details, and keep walking toward the light.',
      past: 'Some good things arrived late, or the results shone less than they should have. That cloud was never a disaster — it only blocked light that was rightfully there.',
      present: 'You feel flat and low-wattage right now, but the foundation is good. Keep the details and basics steady — the sun behind that cloud has been there the whole time.',
      other: "Their feelings are warm at the core; they've just been low on energy lately. The heat is temporarily behind a cloud — it hasn't actually turned cold.",
      verdict: 'leanYes',
      verdictReason: 'The reversed Sun is still sunlight at its core — the results are merely delayed or discounted. The direction stays favorable; add patience and a dose of realism.',
    },
  },
  {
    id: 'major-20',
    name: '審判',
    nameEn: 'Judgement',
    arcana: 'major',
    number: 20,
    scene: 'An angel leans from the clouds blowing a trumpet hung with a white banner bearing a red cross; below, grey-skinned figures rise from coffins floating on the sea, arms spread and faces lifted, snowy mountains in the distance.',
    upright: {
      keywords: ['awakening', 'calling', 'rebirth', 'reckoning'],
      core: "The trumpet sounds and the sleepers rise — Judgement is the card of being woken up. Past efforts and debts come due for settlement at once, and you hear it too: the call from deep inside, saying it's time to answer for the truer version of yourself. Take honest stock of the road here, forgive what needs forgiving — including yourself — and walk into the next chapter with the accounts finally cleared.",
      daily: "Today suits an honest retrospective: what's the one thing you've most wanted to change these past six months? Write it down — and answer the thought that keeps resurfacing in your mind. That recurring thought is, more often than not, the sound of the trumpet.",
      love: "An old flame may resurface, or the relationship reaches its moment of truth and reconciliation. Reassess with today's maturity — don't judge each other by the old ledger; forgiveness opens the new chapter.",
      career: 'Reviews, results, interview verdicts are about to land — and your accumulated track record will speak for you. If a call to change tracks has been sounding inside you, this is the moment to answer it seriously.',
      money: 'Time for a full reckoning: lay out your entire financial picture, clear the debts, keep the strong and cut the weak. Turn past lessons into new principles, and your financial constitution levels up from here.',
      advice: 'Answer the call that keeps sounding inside you — stop hitting the snooze button on it.',
      past: 'The trumpet actually sounded long ago: what you built and what you owed have been kept on the books all along, pushing you to precisely this moment of reckoning.',
      present: 'This is the hour of settlement and response: the thought that keeps resurfacing is the call itself. Take honest stock of the road behind you — then answer it.',
      other: 'That person is reviewing everything that has passed between you, and a voice inside presses them to respond — reconciliation, a declaration, or a fresh start.',
      verdict: 'yes',
      verdictReason: 'Judgement means the verdict is in and rebirth follows — past cultivation receives its fair answer. As long as you face it honestly, the answer leans firmly toward yes.',
    },
    reversed: {
      keywords: ['self-doubt', 'ignored calling', 'unsettled accounts', 'playing asleep'],
      core: "The trumpet blew, and you pretended not to hear. Reversed Judgement is often self-judgment run too hot — flogging yourself with old failures until you dare not accept a new invitation. Or the reverse: the reckoning you owe keeps getting shelved, and the accounts pile higher. No one can wake someone pretending to sleep — but in truth you're already awake. Pardon yesterday's self, and you can catch today's calling.",
      daily: "Count how many times 'I can't' crosses your mind today, and each time fire back one question: where's the evidence? Write one past success on a note and carry it with you — turn the volume of self-doubt down one notch.",
      love: "An old wound has you refusing to give love another chance, or relitigating the past has become your loop. Make peace with what happened first — then you'll have room to see the person in front of you.",
      career: "Opportunity is knocking and you want to hide, because your self-assessment runs too low. Don't reject yourself on the other side's behalf — hand in the work first. Scoring it is their job, not yours.",
      money: 'Avoiding the accounts only lets the anxiety compound. Set aside one quiet afternoon and lay out every number: reality is usually more manageable than the dread — then write the repair plan.',
      advice: 'Call off the self-trial — pick up the shelved reckoning and the shelved opportunity together.',
      past: 'An old account went unsettled: a review that should have happened was shelved, or a failure became a whip used on yourself — and the debt has carried into now.',
      present: "The calling has come knocking, and you're still playing asleep. Pardon yesterday's self, then pick up the shelved reckoning and the shelved opportunity together.",
      other: "That person is tangled in old accounts and self-doubt: they've heard the call, truly, but don't dare answer — so no clear response has come from them yet.",
      verdict: 'leanNo',
      verdictReason: 'Reversed Judgement shows hesitation and unfinished homework blocking the road — the timing is being delayed by your own hand. Clear the old accounts first, and the answer can turn.',
    },
  },
  {
    id: 'major-21',
    name: '世界',
    nameEn: 'The World',
    arcana: 'major',
    number: 21,
    scene: 'At the center of an oval wreath, a dancer draped in a flowing purple sash leaps on one foot, a short wand in each hand; at the four corners of the card, the heads of a man, an eagle, a lion and a bull appear above the clouds.',
    upright: {
      keywords: ['completion', 'fulfillment', 'achievement', 'new cycle'],
      core: "The dancer turns at the center of the wreath and the four watchers are in their corners — the major arcana's journey closes here, complete. The World marks the true completion of a cycle: credits earned, mission closed, destination reached — complete inside as well as out. Standing here, celebrate properly and give your thanks properly. The wreath is a circle: this ending is also where the next journey begins.",
      daily: "Bring one nearly-finished thing across the line today: hand it in, publish it, put the period on it — don't leave it parked at ninety-nine percent. And when it's done, give yourself a small ritual. Celebration is part of the journey too.",
      love: "The relationship reaches its blossoming stage: commitment, moving in, the next milestone — all are blessed. If single, a chapter of inner work is complete, and a whole self is what draws the right person.",
      career: "The big project lands cleanly, and your name is attached to results everyone can see. It's a season for closing, presenting, and collecting the harvest — and for sketching the next, larger stage.",
      money: 'A long-cultivated financial goal is within reach: the savings target hit, the loan paid off, the investment harvested in full. Tally the results — then set the tone for the next round of allocation.',
      advice: 'Walk the last mile all the way to the end — and then truly celebrate the completion.',
      past: 'A full cycle came round and closed — a completion whole inside and out. That finish is the source of the confidence and the position you hold today.',
      present: 'Harvest and wrap-up are right in front of you: walk the last mile, celebrate properly, give thanks — this spot is also the trailhead of the next journey.',
      other: "To them, this bond carries a sense of wholeness and solid ground: they feel it has reached a mature stage, and they're willing to walk toward the next milestone.",
      verdict: 'yes',
      verdictReason: 'The World is the ultimate signal of fulfillment and arrival — the conditions for a complete harvest are in place, and the answer points clearly to yes.',
    },
    reversed: {
      keywords: ['last mile missing', 'unfinished business', 'stalled closure', 'missing piece'],
      core: "There's a small gap in the wreath. The reversed World is the story of almost-but-not-quite: the thesis one chapter from done, the project stuck at the wrap-up, the relationship parked one step short. Sometimes conditions truly aren't ready — more often, part of you doesn't want it to end, or dreads the blank space after. Find the missing piece and set it in place: only a finished world lets you into the next one.",
      daily: "List everything sitting at ninety percent today, pick the one that matters most, and block out one uninterrupted stretch of time to close it. Finish just one, and you'll exhale a breath you've been holding for a very long time.",
      love: 'The relationship is missing its final step: together in practice but never named, or a past chapter still open somewhere in your heart. Find that unfinished thing and close it, facing it head-on.',
      career: 'The project has stalled in its closing phase, and the sense of achievement never lands. Pinpoint the concrete snag — resources, sign-off, or your own perfectionism — and break through them one at a time.',
      money: 'The financial goal is stuck at ninety percent, and the gap is usually the last stretch of discipline. Check for small chronic leaks in the budget — plug them, and the goal closes out cleanly.',
      advice: 'Find the missing piece and set it in place — and give the wrap-up a firm deadline.',
      past: 'Something stopped at ninety-nine percent: that one-step-short piece of unfinished business was never dealt with, and it has hung suspended into the present.',
      present: 'The task before you is closure: see whether the missing piece is conditions not yet ripe or a reluctance to end — fill it in, and the period can finally be placed.',
      other: "They're parked one step from the finish: they know where things stand, yet won't write the final line — some unfinished business inside still has nowhere to rest.",
      verdict: 'neutral',
      verdictReason: 'The reversed World hangs at the very last step, so the outcome is unwritten: fill the gap and it completes — leave it untouched and it stays suspended.',
    },
  },
]
