// English content: major-00 … major-10 (11 cards).
// The Fool (major-00) is the lead-written tone anchor — match its quality.
// name/nameEn/ids MUST mirror the zh files and registry; verdicts MUST match zh.
import type { TarotCard } from '../types'

export const major0010: TarotCard[] = [
  {
    id: 'major-00',
    name: '愚者',
    nameEn: 'The Fool',
    arcana: 'major',
    number: 0,
    scene: 'A young traveler steps toward a cliff edge, face tilted to the sky, a bundle on a stick over one shoulder and a white rose in the other hand, a little white dog leaping at his heels beneath a white sun and distant snowy peaks.',
    upright: {
      keywords: ['new beginnings', 'freedom', 'adventure', 'innocence'],
      core: "The Fool stands at the cliff's edge with a light pack and his face to the sun. This card marks the start of a journey: you don't need everything figured out before you set off — your curiosity and openness are assets in themselves. What lies ahead isn't so much risk as possibility that hasn't been given a shape yet. Walk on with an open heart, and the path will grow under your feet.",
      daily: "Today favors starting the thing you've been meaning to do. Don't wait until everything is ready — shrink the first step to something you can finish in fifteen minutes, and take it now.",
      love: "If you're single, someone new may catch your eye — enjoy getting to know them before weighing the pros and cons. If you're together, try something neither of you has done before and let things feel new again.",
      career: "A new project, role or field is worth raising your hand for. A thin résumé is not the problem — the learning curve is exactly this card's gift.",
      money: 'A small experiment with a new tool or approach is fine, but the Fool skips the fine print — do your homework before committing anything big.',
      advice: "Don't overthink it — take the first step; the course can be corrected along the way.",
      past: 'It all began with a leap of instinct: you set out on trust and nerve, and that daring is the seed of where things stand now.',
      present: 'You are standing at a fresh start with more freedom than you think; one small step matters more than a perfect plan.',
      other: 'They are in an eager, open state — curious about what could be, not thinking too far ahead, but the lightness is genuine.',
      verdict: 'leanYes',
      verdictReason: 'The Fool\'s energy is openness and setting out — for most questions it leans toward "go try"; how it ends depends on what you learn on the way.',
    },
    reversed: {
      keywords: ['impulsiveness', 'unprepared', 'hesitation', 'avoidance'],
      core: "Reversed, the Fool shows two faces: charging ahead with eyes closed when you know you should prepare, or standing at the edge so long that the step never comes. Either way, the departure is stuck. Be honest about which one you are — if you need to brake and do the homework, do it; if you've already thought it through, all that's missing is permission to go.",
      daily: 'Hold off on big decisions today, especially the "whatever, let\'s just do it" kind. Write down what you want to do and list three things you haven\'t thought through; setting out after that is not too late at all.',
      love: "Someone may want to keep things casual and unaccountable — or it may be you who isn't ready to commit. Slow the pace and look clearly before you dive in.",
      career: "Before taking on something new, check your bandwidth and get the terms clear; don't rush out of your current seat just for the novelty.",
      money: 'Watch out for impulse buys and hot tips from friends; the "rare opportunities" showing up now deserve a two-day pause and a second look.',
      advice: "Pause, fill in the three things you haven't thought through, then decide whether to go.",
      past: 'The start was rushed — you leapt without looking, or hesitated when it was time to go, and that loose beginning still shapes things now.',
      present: 'You are caught between charging and not daring to move, impulse and hesitation taking turns; fill in the missing thinking first.',
      other: "They haven't settled yet: part impulse to move, part hesitation to commit — either way, not ready to promise anything firm.",
      verdict: 'leanNo',
      verdictReason: 'The reversed Fool points to poor timing or thin preparation; forcing it now invites a stumble — pause and regroup first.',
    },
  },
  {
    id: 'major-01',
    name: '魔術師',
    nameEn: 'The Magician',
    arcana: 'major',
    number: 1,
    scene: 'A young man in a red robe over white raises a wand skyward with his right hand and points to the ground with his left, an infinity sign above his head; a wand, cup, sword and pentacle lie on the table, roses and lilies twining around.',
    upright: {
      keywords: ['creation', 'resources in place', 'drive', 'focus'],
      core: "All four tools sit ready on the Magician's table — a sign that you lack nothing: the skill, the tools, the contacts and the ideas are already in place, and the only missing piece is the act of putting them together. One hand points to heaven, one to earth: bring the vision in your head down into the real world. Right now your focus is the magic itself; the thing you want can be conjured with your own hands.",
      daily: "Today is made for building a first rough version of the idea you've been sitting on. Take stock of what you already have — you'll find the pieces are all there; what's missing is simply starting. Pick the one thing you most want to make real and give it a full, undistracted hour.",
      love: "The moment favors making a move. If you're single, show your charm and your wit without apology; if you're partnered, plan a small surprise — this relationship rewards your creativity.",
      career: 'Your expertise and your voice are being noticed — pitches, presentations and negotiations all tilt your way. Take the stage, let the results speak, and the initiative stays in your hands.',
      money: "An idea for new income deserves a serious look — you currently have what it takes to turn skill into money. And when you name a price, don't be shy: the value you deliver supports the number.",
      advice: 'Take stock of what you have and start now — turn the idea into something people can see.',
      past: 'This began when you built the idea with your own hands: that early proof that the skill and resources were real laid the foundation for where things stand.',
      present: 'The conditions are all in place; the only variable left is action. Gather your attention onto the one thing you most want to make real, and let focus work the magic.',
      other: "They're in fine form right now: full of ideas, resources in hand, eager to create something — and willing to put real thought into this relationship too.",
      verdict: 'yes',
      verdictReason: "The Magician means the conditions are set and the power to act is yours; if you're willing to do the work, things mostly bend the way you want.",
    },
    reversed: {
      keywords: ['bluffing', 'manipulation', 'half-learned skill', 'scattered focus'],
      core: "Reversed, the Magician's tools are still on the table — but the hands aren't really moving. Maybe the talk is polished and the follow-through isn't; maybe someone nearby is wrapping hollow promises in clever words. Or the talent is real but busywork has chopped it to pieces and the focus is gone. Sort out which it is — you overreaching, or someone performing — then pull your attention back to what truly matters.",
      daily: 'Watch today for the say-much-do-little pattern, whether in others or in yourself. Instead of another meeting or another round of talking through the idea, silence the notifications, actually finish one piece of it, and end the day with something made.',
      love: "Enjoy the sweet talk, but watch whether the actions keep pace with the words. Notice too whether you've been managing an image instead of showing up — being real is far more attractive.",
      career: "A dazzling pitch won't survive a missed delivery. Rather than opening new fronts, finish what you've already promised — and finish it solidly.",
      money: "Be extra wary of investment pitches and high-return schemes just now. Terms that sound too good almost always hide a cost you haven't seen yet.",
      advice: 'Talk less, build more — deliver one real result before discussing the next step.',
      past: 'In the beginning the words outran the work, or someone dressed a promise up in fine talk; that gap between saying and doing built into the present situation.',
      present: 'The task now is telling talk from execution: finishing one thing you already promised will steady the situation better than opening one more conversation.',
      other: "They say more than they've done so far: attention somewhat scattered, a gap between words and follow-through — the promises being made still need time to prove out.",
      verdict: 'leanNo',
      verdictReason: "The reversed Magician suggests the ability or the sincerity isn't in place yet, so things tend to stall at talk; verify the gap before you invest much hope.",
    },
  },
  {
    id: 'major-02',
    name: '女祭司',
    nameEn: 'The High Priestess',
    arcana: 'major',
    number: 2,
    scene: 'A woman in a lunar crown sits between black and white pillars marked B and J, a half-hidden scroll on her lap, an equal-armed cross at her chest, a crescent moon at her feet, and a veil embroidered with pomegranates behind her.',
    upright: {
      keywords: ['intuition', 'quiet watching', 'hidden currents', 'inner wisdom'],
      core: "The High Priestess sits before a veil, and what lies behind it is not yet meant to be seen. The answer right now isn't in more information — it's in the quiet voice you've already half heard. Part of this situation is still below the surface, and rushing to act would only scare it deeper. Grow still, let intuition speak, and when the time is right, what's been hidden will walk into the light on its own.",
      daily: "Listen and watch first today; don't rush to take a position. What goes unsaid in the meeting, what someone almost says and swallows — that's often the real point. Before bed, take ten minutes to write down your strongest gut feeling of the day, and check it against reality in a few days.",
      love: 'Some things in this relationship remain unspoken. Rather than pressing for answers, allow some quiet space; that faint feeling in your gut is usually closer to the truth than the surface story.',
      career: 'Decisions and personnel moves are still shifting below deck, so listening more and saying less is the safest play. Note down the clues you observe and hold your position for now.',
      money: "Some information isn't public yet, and buying in now is betting blindfolded. Shelve the financial decision until you've checked the details for yourself.",
      advice: "Watch quietly, trust the details your intuition picks up, and don't move before it's time.",
      past: 'The root of this was below the surface: things went unsaid at the time, and the faint voice you kept sensing turns out to have been right all along.',
      present: "The answer is still behind the veil, so don't force the move; watch quietly and let intuition speak — what's been covered will surface on its own.",
      other: 'They are carrying words not yet spoken: quietly watching and feeling things out, calm on the surface, with far more going on inside than they show.',
      verdict: 'neutral',
      verdictReason: 'The High Priestess says the answer is still behind the veil, neither yes nor no yet; rather than forcing a conclusion, wait for the hidden pieces to surface.',
    },
    reversed: {
      keywords: ['ignored intuition', 'secrets surfacing', 'too much noise', 'restlessness'],
      core: "The reversed High Priestess tends to appear when you already know — and choose not to listen: the room is too loud, other people's opinions too many, and your own voice gets drowned out. Or something that was concealed is starting to slip loose, rising toward the surface. Instead of asking the world for more answers, close the door and ask yourself: that feeling you keep pushing down — what has it been trying to say?",
      daily: "The noise will be loud today, so take other people's advice at a third of its volume. Find a stretch of uninterrupted time alone and lay out the question you've been avoiding — you'll find you already knew the answer.",
      love: "You may have been finding excuses for certain signs. Stop talking yourself into 'it's fine' — voice the doubt gently; an open conversation is far safer than stewing and guessing.",
      career: "Rumors are flying, so verify before you pass anything on. If a project feels quietly wrong, don't sit on the feeling — check it with someone you trust.",
      money: "A contract or the accounts may hold details you've missed; these are good days to reread them line by line. If something feels off, dig until you understand it.",
      advice: 'Turn down the volume of other voices and listen again to the answer you already know.',
      past: 'Back then you pressed down a feeling you knew was right, or a key piece of information was kept from you; that unheard intuition has carried into now.',
      present: 'Right now the noise is drowning your inner voice, and something hidden is close to surfacing; closing the door and asking yourself beats asking the world.',
      other: 'They are unsettled at the moment: perhaps holding back things not yet said, perhaps not even clear yet on what they themselves feel.',
      verdict: 'leanNo',
      verdictReason: 'The reversed High Priestess shows information obscured or intuition ignored — the ground for judgment is shaky, and a hasty yes risks misreading it.',
    },
  },
  {
    id: 'major-03',
    name: '皇后',
    nameEn: 'The Empress',
    arcana: 'major',
    number: 3,
    scene: 'A woman crowned with twelve stars reclines on cushions, her white gown patterned with pomegranates, a scepter in hand; a heart-shaped shield with the Venus symbol stands by the chair, forest and a waterfall behind, ripe wheat at her feet.',
    upright: {
      keywords: ['abundance', 'nurturing', 'creativity', 'sensual delight'],
      core: "The wheat at her feet hangs heavy with grain — this is a card of things that grow on their own. The care you've already put in is coming into flower, and it no longer needs forcing; keep watering it and give it time. This mother of the earth also asks you to be kind to your body and your feelings: eat well, sleep well, keep beautiful things around you. Creativity and good luck both grow out of a nourished state.",
      daily: "Be good to yourself today: eat a proper meal, walk somewhere green, make your space comfortable. You don't need to push harder — you need to return to a cared-for state, and inspiration and patience will come back on their own.",
      love: 'The relationship is entering a well-tended phase where giving and being loved come naturally. Single? Your charm is at a high — just be yourself. Partnered? Let in a little more physical tenderness.',
      career: "The projects you've cultivated are starting to yield, and the harvest will be richer than expected. When leading people, give space and nourishment — the team will grow more for you than you planted.",
      money: 'Finances feel easy and roomy, and a moderate treat for yourself is no sin. Long-term investing is gardening: the returns on steady contributions are quietly stacking up.',
      advice: "Stop hurrying it — keep watering, and let what's already planted ripen on its own.",
      past: 'This grew out of a season of good nurture: the careful tending and investment you gave earlier is now bearing the very fruit you see.',
      present: 'The task now is tending, not pushing: settle yourself, keep up the watering — what you planted is quietly coming ripe.',
      other: 'They are in a warm and generous state: willing to give and to care, holding this relationship with a nurturing heart — easy and safe to be around.',
      verdict: 'yes',
      verdictReason: 'This card carries the energy of harvest and nurture — things are heading toward flower and fruit; tend them along and the outcome is good.',
    },
    reversed: {
      keywords: ['overgiving', 'feeling depleted', 'creative stall', 'dependency'],
      core: "Caring for everyone until you forget yourself — that's the most common face of this reversal: a stuffed schedule, body and mind overdrawn, giving slowly turning into invisible resentment. Or the opposite: sinking too deep into comfort while the things that need to grow stay put. Tired soil grows nothing. Put nourishing yourself back on the calendar — you do not have to wring yourself dry to deserve love.",
      daily: "Practice saying the word 'no' out loud once today. When someone piles more onto you, check how much is left in your tank first. Keep one stretch of the evening entirely your own, doing nothing productive at all.",
      love: 'When the giving stays lopsided, quiet hurt slowly ferments into resentment. See to your own needs before you give more; being depended on is not the same as being loved — draw the line.',
      career: "Take care not to become the office's permanent mess-cleaner. Put the overload on the table and talk it through; whatever should be handed off, hand off.",
      money: 'Emotional spending slips easily right now. Before buying, ask yourself: is this a need, or a wish to be comforted? The second one has much cheaper remedies.',
      advice: 'Fill your own tank first, then decide how much you have to give away.',
      past: 'Earlier you gave until you forgot yourself, or lingered too long in comfort; that overdraft or that stall is exactly where the present came from.',
      present: 'What you lack most right now is your own nourishment: draw the boundary and refill the tank first — then things will have the strength to move forward.',
      other: 'They are somewhat worn out: perhaps quietly aggrieved from giving too much, perhaps sunk in their own comfort — with little spare energy for now.',
      verdict: 'leanNo',
      verdictReason: 'The reversal shows energy overdrawn or nourishment out of balance; forcing seeds into tired soil brings a poor harvest — rest and recover first.',
    },
  },
  {
    id: 'major-04',
    name: '皇帝',
    nameEn: 'The Emperor',
    arcana: 'major',
    number: 4,
    scene: "A white-bearded man in a red robe over armor sits squarely on a stone throne carved with rams' heads, an ankh-shaped scepter in his right hand and a golden orb in his left, with barren mountains rising under a red sky behind him.",
    upright: {
      keywords: ['order', 'authority', 'responsibility', 'solid foundations'],
      core: "The Emperor's throne is built of stone, and before he sat on it he set the rules for the whole realm. This card is about the power of structure: goals get landed not on passion but on systems — timelines, budgets, clear ownership. This is your moment for discipline and for stepping up, setting the chaos back piece by piece into its proper place. Build the frame first; freedom is what the frame provides.",
      daily: "Gather your scattered to-dos into one list today, set the priorities, then work the plan. Less improvising, more discipline — you'll find that the things making you anxious stop being frightening once structure catches them.",
      love: 'The relationship needs commitment and clear promises; anything ambiguous is ready to be defined. Partners should talk through roles and future plans; if single, you may be drawn to someone mature and steady.',
      career: 'It is time to build systems and shoulder responsibility — your leadership stock is high. Set the processes in place, and your expertise will be trusted with greater authority.',
      money: 'Discipline is the money luck itself: make the budget, set the stop-loss, execute the plan. Steady allocation beats flashes of brilliance, and long-term rules will protect you.',
      advice: 'Set the rules and follow them yourself first; carry the goal forward one structured step at a time.',
      past: 'The present was built on rules laid down early: someone took responsibility and raised the framework, and that is why the ground holds steady now.',
      present: "What's needed now is structure and ownership: sort out who answers for what, execute on schedule, and the frame will catch the chaos piece by piece.",
      other: 'Reason outweighs feeling in them right now: they value planning and responsibility, want things well arranged, and express care practically, not romantically.',
      verdict: 'leanYes',
      verdictReason: 'The Emperor reaches goals through discipline and systems — the path is workable, but success hinges on whether you will own it and keep executing.',
    },
    reversed: {
      keywords: ['overcontrol', 'rigidity', 'domineering', 'disorder'],
      core: "The reversed Emperor has two faces. One grips too tight: managing everything, deaf to input, squeezing the air out of everyone nearby. The other cannot hold the weight: responsibility goes unclaimed, and things scatter because no one will decide. Real authority comes from trust, not volume. Look at the fist you're making — should it loosen a notch, or reach out and catch what needs holding?",
      daily: "When something goes wrong today, don't rush to correct anyone. Ask yourself first: am I actually solving the problem, or do I just want things done my way? Practice handing one decision over to someone else, completely.",
      love: "Controlling and being controlled are both suffocating. Who gets the final say shouldn't be the only question — bring back 'we decide together,' and the relationship gets room to breathe.",
      career: 'Mind the power struggles with those above you; head-on collisions win nothing. If you lead others, try loosening your grip on the details and watching only the outcomes.',
      money: "Don't keep up appearances to prove a point, and don't let everything drift unmanaged either. Check whether the budget exists in name only, and set the rules once more.",
      advice: 'Loosen the fist one notch and swap orders for discussion — and stop dodging what is yours to carry.',
      past: 'Looking back, either the grip was too tight or no one was steering; that unbalanced authority left behind the tension or the mess you see now.',
      present: 'You are facing the calibration of power: release the details that should be released, catch the duties that are yours — adjust that before pushing on.',
      other: 'Control is their current theme: they may want to run everything, or may be dodging the weight entirely — either way the posture has gone a little stiff.',
      verdict: 'leanNo',
      verdictReason: 'The reversed Emperor shows structure out of balance — gripped too tight or carried by no one; forcing ahead invites pushback, so fix the ownership first.',
    },
  },
  {
    id: 'major-05',
    name: '教皇',
    nameEn: 'The Hierophant',
    arcana: 'major',
    number: 5,
    scene: 'A pope in a triple crown sits between two gray stone pillars, right hand raised in blessing, left hand holding a staff topped with a triple cross; two monks in embroidered robes kneel at the steps, and two crossed keys lie at his feet.',
    upright: {
      keywords: ['tradition', 'proper channels', 'mentorship', 'belief'],
      core: "The crossed keys at the Hierophant's feet open doors others have walked through before. This card points to the value of institutions and lineage: rather than improvising it all, ask a teacher, follow the standard procedure, borrow methods time has tested. It's also about belief — you need values you can rest inside. Following the rules now isn't compromise — it's standing on the shoulders of those who came before.",
      daily: "When you hit a wall today, don't grind at it alone — find the person who has already walked this road: a senior colleague, a teacher, even the official documentation counts. Follow the advice step by step just once, and you'll save yourself an enormous detour.",
      love: 'The relationship is moving toward something formal and blessed: meeting the family, going public, commitment — all natural next steps. For singles, a good match may come through elders or a trusted circle.',
      career: 'Playing by the system pays off now: apply for what can be applied for, sit the certifications, push through formal channels. A senior mentor in your field is worth more than you can measure.',
      money: 'Keep the finances conservative and orthodox: choose reputable institutions and instruments with a track record, and stay away from shortcuts of dubious origin.',
      advice: "Ask those who have walked this road, follow the standard procedure, and don't rush to blaze your own trail.",
      past: 'This road was walked in footprints already made: the teachers, the institutions, or the values handed down at home shaped who you are now.',
      present: "The matter at hand is best taken through proper channels: seeking advice from someone who's been here will spare you far more than forcing your own way through.",
      other: 'They value stability and the rules: inclined to build the relationship step by step, mindful of commitment and of how things look — serious and long-term at heart.',
      verdict: 'leanYes',
      verdictReason: 'The Hierophant favors what travels the proper road; as long as your question runs through legitimate channels, approval and blessing are well within reach.',
    },
    reversed: {
      keywords: ['questioning dogma', 'breaking convention', 'empty formality', 'going independent'],
      core: "Reversed, the Hierophant begins to wonder: are these rules still protecting anyone, or just formality now? Perhaps you want out of a system that no longer fits — changing tracks, leaving an organization, challenging the official line. That isn't necessarily bad; plenty of breakthroughs start with 'why does it have to be this way.' Just decide, before you walk out, which still-precious things you'll take with you.",
      daily: "Question one 'we've always done it this way' today: does this process still have a reason to exist? Keep what's justified, and propose changing what survives on inertia alone. Be a gentle reformer, not the one who flips the table.",
      love: "The way you two work may not match the template others expect — but the relationship belongs to you both, so don't rush onto anyone else's timeline. Do agree on your shared bottom lines first, though.",
      career: "The system's rigidity is starting to grind; push for reform through proposals, not collisions. If you're considering leaving to go solo, first confirm the real skills come with you.",
      money: "Don't invest in something because 'everyone's in it'; then again, the deliberately contrarian option isn't automatically smarter. Come back to judgments you have verified yourself.",
      advice: 'Question the rules that deserve questioning — but reform with proposals, not by flipping the table.',
      past: "Earlier you began doubting a set of rules that no longer fit; that loosening of 'the way it's always been' is what carried things to where they stand today.",
      present: 'You are standing between the system and striking out on your own: get clear on what to take and what to lay down — reform by proposal, not by storming off.',
      other: "They are questioning some settled frameworks: unwilling to be bound by convention, wanting to do things their own way, and allergic to being told the rules just now.",
      verdict: 'neutral',
      verdictReason: 'The reversed Hierophant is old frames coming loose; whether that ends well depends on leaving prepared versus rebelling for its own sake — the answer rests on how you do it.',
    },
  },
  {
    id: 'major-06',
    name: '戀人',
    nameEn: 'The Lovers',
    arcana: 'major',
    number: 6,
    scene: 'A naked man and woman stand apart on a plain — a serpent coils in the fruit tree beside her, twelve flames burn in the tree beside him — a mountain rises between them, and beneath a blazing sun a red-winged angel blesses them from clouds.',
    upright: {
      keywords: ['love and union', 'a choice of values', 'honesty', 'harmony'],
      core: "The angel spreads its wings above the clouds to witness two people being fully honest with each other. It is partly a relationship card: hearts in tune, mutual attraction, a willingness to hand over your real self. And partly a card of choice — the decision before you has no textbook answer, only which path lines up with your values. Choose with your heart, then commit completely — that is this card's blessing.",
      daily: "When a choice comes up today, set aside 'what will people think' and ask instead 'which option makes me more myself.' It's also a good day to say something true to someone who matters — honesty will open doors you didn't expect.",
      love: "A strong card for attraction and hearts in tune. If you're single, you may meet someone who makes you serious; if partnered, deeper honesty and commitment beckon — the relationship is moving into a new stage.",
      career: 'Partnership is the keyword of this stretch: teammates whose ideals match yours will double the results. Facing a career decision, take the path that lines up with your values.',
      money: 'Decisions involving shared money — a joint venture, splitting household costs — deserve full openness. When torn between two options, choose the one you genuinely believe in.',
      advice: "Follow your heart's true lean when you choose — then commit completely and don't look back.",
      past: 'It all began with a choice made in earnest: you listened to your own heart then, and that honesty and fit is the root of where things are now.',
      present: 'The point right now is aligning with your values: ask which option is more like you — and once chosen, pour yourself in and stop looking back.',
      other: 'Their feelings are sincere: drawn to you, willing to be open, and genuinely holding this relationship in an important place.',
      verdict: 'yes',
      verdictReason: "The Lovers stands for the heart's true direction and a harmonious union; as long as the choice comes from the heart, this card gives a clear blessing.",
    },
    reversed: {
      keywords: ['misaligned values', 'indecision', 'imbalance', 'avoiding the choice'],
      core: "The reversed Lovers often shows up in the 'you know it's wrong, but can't bear to admit it' place: lopsided giving, two people wanting fundamentally different things, or a decision dragged so long the options quietly expire. The angel is still there — just blocked from view by hesitation. Say the question you've been avoiding out loud: the real crack isn't the disagreement — it's refusing to face it honestly.",
      daily: "Stop hiding from that pending decision behind busyness today. Write down the worst outcome of each option, and you'll notice what actually stalls you isn't the options at all — it's not wanting to own the result.",
      love: 'You may already want different things, and dodging the conversation only widens the distance into a gulf. Lay the differences out honestly — that is the only way to repair, or to part well.',
      career: 'There are signals of misaligned values in a partnership; check first whether your goals still match. Keeping up surface harmony by force costs far more in the end.',
      money: "Clear up any fuzzy money arrangements with others early — verbal understandings are exactly what turn into tomorrow's disputes. Put it in writing.",
      advice: 'Put the long-avoided disagreement on the table; honesty is the only place repair can begin.',
      past: 'Back then a disagreement went unspoken, or a decision dragged on too long; that unaligned seam has run all the way through to now.',
      present: "You're facing the disagreement you've long avoided: lay the honest words on the table, and the relationship — or the choice — gets its chance to refocus.",
      other: "There's hesitation in them: they may sense that you two want different things but haven't said it, swinging between facing it and looking away.",
      verdict: 'leanNo',
      verdictReason: 'The reversed Lovers shows values out of alignment or a choice gone off target; the current state cannot carry a straight yes — get honest and realign first.',
    },
  },
  {
    id: 'major-07',
    name: '戰車',
    nameEn: 'The Chariot',
    arcana: 'major',
    number: 7,
    scene: 'A young warrior in a star-set crown stands in a stone chariot, crescent-moon faces on his shoulders, a wand in hand; a black and a white sphinx crouch before him, a star-embroidered canopy overhead, city walls and a river behind.',
    upright: {
      keywords: ['willpower', 'momentum', 'command', 'victory'],
      core: "The black and white sphinxes before the chariot wanted to pull in different directions — the driver's will makes them run side by side. You have those pulls inside you too: the part that wants to charge, the part that wants to hide, reason and emotion. This card says you can rein them all in and drive toward a single goal. The direction is set; what remains is focus and speed. Take the victory through action.",
      daily: 'Pick your single most important goal today and sprint at it with nothing else in view. Turn off the notifications, put the hesitation away, and give one unbroken stretch of time to the heart of it — your driving force is stronger than usual.',
      love: "Making the move brings progress; hesitating lets the chance slip away. If you're partnered and there's a shared goal worth fighting for, charging at it together will heat the relationship up.",
      career: 'This is the moment to attack: bid for that project, ask for that promotion, put your name down. Clear goals plus execution — you are in the kind of state that rolls right over obstacles.',
      money: 'Your drive to open up income is strong, and negotiations tilt your way. But keep both hands on the wheel: sprint, yes — think the route through before you hit the gas.',
      advice: 'Lock onto the goal and go full speed; leave every distraction for after you arrive.',
      past: 'A stretch of gritted-teeth charging carried you here: the goal you fixed and the fight you brought back then are the engine of the progress you see now.',
      present: "This is the sprint leg: the direction is already set, so tuck the distractions away and push — this victory is one that's taken with speed.",
      other: "They're full of drive right now: clear about the goal, pushing forward, quick to act on what they care about — though the tempo runs fast and a little urgent.",
      verdict: 'yes',
      verdictReason: 'The Chariot wins by will and action; as long as you grip the reins and charge, the answer leans firmly toward success.',
    },
    reversed: {
      keywords: ['losing control', 'direction lost', 'reckless', 'stalled momentum'],
      core: "Reversed, the two sphinxes start pulling their own ways: maybe you are chasing too many goals at once and the forces cancel out; maybe emotion has grabbed the wheel, and you are moving fast down the wrong road; or the whole chariot has simply stalled — you want to move, but nothing sparks. Flooring the pedal now will not help. Stop and refocus first: confirm where you are going, then decide what speed to take.",
      daily: "If today feels rushed and scrambled, stop for ten minutes, list everything you currently have in motion, and cut it — painfully — down to three or fewer. Set out again once the direction is clear; you'll find that slower turns out to be faster.",
      love: 'The friction may come from mismatched tempo: one of you flooring the gas, the other stamping the brake. Agree on where you are going first — then talk about the speed.',
      career: 'Progress is jammed, or too many horses are pulling the cart; stop forcing it. Go back and rank the goals, cut the tasks that fight each other, and the momentum will return.',
      money: 'The urge to win it back or rush the entry is the most dangerous one; when the direction is unclear, every step is a cost. Stop the loss, consolidate, and wait until you can read the road.',
      advice: 'Pull over and refocus first; cut the extra goals, then set out again.',
      past: 'Back then it was too many directions at once, or emotion took the wheel; the forces canceled each other out, and that is how the road bent to here.',
      present: "Don't stamp on the gas just now: cut the goals down to the few that matter most, refocus, and then launch — it will beat charging blind.",
      other: 'Their direction is in some disarray: head and heart pulling separate ways, urgent and listless by turns — unable to hold a steady tempo for now.',
      verdict: 'leanNo',
      verdictReason: 'The reversed Chariot shows the aim off target or the drive eating itself; pushing now costs double for half the result — regroup first and the odds improve.',
    },
  },
  {
    id: 'major-08',
    name: '力量',
    nameEn: 'Strength',
    arcana: 'major',
    number: 8,
    scene: "A woman in white, flowers in her hair and a chain of roses at her waist, an infinity sign above her head, bends to gently close a golden lion's jaws with both hands; the lion gazes up at her, tamed, with fields and far hills behind.",
    upright: {
      keywords: ['gentle strength', 'patience', 'courage', 'inner calm'],
      core: "The woman in the Strength card carries no weapon; what makes the lion lower its head is her calm and her gentleness. Real strength is not suppression — it is being on good terms with your own fear, desire and temper, and then carrying that composure out to meet the world's problems. The challenge in front of you barely responds to force: patience, empathy and steady courage will take you much further than muscle.",
      daily: "When a moment comes today that makes you want to snap or give up, take three slow breaths before you answer. Say your position in a voice that is gentle and firm — no shouting, no retreating — and you'll notice the most powerful person in the room is you.",
      love: 'Tolerance and patience are quietly warming this relationship. Their sharp edges usually come from insecurity; catch them with steadiness instead of clashing head-on, and you two will walk into deeper trust.',
      career: 'The thorny colleague or the gnarly case will yield to soft communication. This is your moment to show composure under pressure — and it is exactly why the big responsibilities will be handed to you.',
      money: 'Restraining desire is the money luck itself for now. When the shopping fever hits, shelve it for a day; hold your long-term positions with the same patience — time is on your side.',
      advice: 'Meet hardness with softness: steady your breath and your tone, and wear the difficulty down with patience.',
      past: "This stretch was carried on gentleness and patience: you didn't meet force with force, and that calm tamed the difficulty — and grew the backbone you have now.",
      present: 'The problem in front of you yields to soft, not hard: steady the breath and the tone and grind at it patiently — your composure is the greatest strength here.',
      other: 'They are gentle outside and firm within: patiently digesting their own feelings, and holding this relationship with a steady, long-haul heart.',
      verdict: 'leanYes',
      verdictReason: 'Strength affirms you have the inner means to master this; it can be done — but the winning is in patience and resilience, not a quick decisive strike.',
    },
    reversed: {
      keywords: ['self-doubt', 'forced bravado', 'fraying emotions', 'courage running low'],
      core: "Reversed, the lion isn't soothed — it roars louder and louder inside. Maybe setbacks have worn your confidence thin and you doubt you can hold on; maybe the brave face has been up too long — breezy on the outside, nearly out of power within. Admitting 'I'm tired, and a little scared' is not losing; it is the first step of strength coming back. Treat the lion as a teammate: soothe it first, then take the field.",
      daily: "Stop telling yourself 'just push through' today. Find someone you trust and say the recent pressure out loud — simply being heard slackens half of the tension. Save whatever strength is left for the things that truly matter.",
      love: "Insecurity makes people say the opposite of what they mean. Instead of testing where their limits are, just say 'I could use some reassurance' — showing the soft spot actually closes the distance.",
      career: "Self-doubt is making you swallow good ideas in meetings; prepare a small note and practice saying them. And don't carry an overload alone — asking for help is professionalism, not weakness.",
      money: 'Under pressure the wallet leaks — spending becomes an outlet. Deal with the feelings before you touch the money, and move any big financial decision to a steadier day.',
      advice: 'Admit the tiredness and the fear, settle your own feelings first, and the strength will follow it back.',
      past: 'Earlier the brave face stayed up too long, and setback after setback wore the confidence thin; that unsoothed lion has followed you all the way here.',
      present: 'First admit the tired and the scared: settle the feelings, say them to someone you trust — strength returns slowly once it has been heard.',
      other: 'They are actually straining: breezy on the surface, carrying more unease than they let on — needing soothing right now far more than questioning.',
      verdict: 'leanNo',
      verdictReason: 'Reversed Strength shows confidence and energy running temporarily short; forcing yourself onto the field invites a slip — restore your state, then take the match.',
    },
  },
  {
    id: 'major-09',
    name: '隱者',
    nameEn: 'The Hermit',
    arcana: 'major',
    number: 9,
    scene: 'An old man in gray robes stands on a snow-capped peak, head bowed and eyes closed, his right hand lifting a lantern with a six-pointed star glowing inside, his left hand resting on a golden staff, nothing around him but blue-gray sky.',
    upright: {
      keywords: ['introspection', 'solitude', 'seeking answers', 'wisdom'],
      core: "The Hermit climbed to the summit not to escape people, but because up there he can hear himself. The lamp in his hand lights only the next step — and this card says your answer won't come from more discussion or more data, but from quiet time alone. Step out of the noise and carry the question inward, shining the light on it slowly. Come down the mountain once you see clearly — one step then will be worth ten now.",
      daily: "Set aside some offline time for yourself today — a walk, sitting quietly, a meal alone all count. Carry the unresolved thing with you as you go; answers have a way of surfacing exactly when you're not hunting for them.",
      love: "The relationship needs settling space, and solitude isn't the same as drifting apart. If single, get clear on what you want before setting out; if partnered, quiet hours apart will actually bring you closer.",
      career: 'This stretch suits deep work and study rather than networking and exposure. Shut the door and dig into one hard problem — the depth you build in the quiet becomes expertise no one can replace.',
      money: 'A season where subtraction beats addition: audit the subscriptions and fixed costs, and cut what you no longer need. Research more than you trade; enter only what you understand.',
      advice: 'Withdraw somewhere quiet and think the question all the way through; come down only once you see clearly.',
      past: 'A quiet spell of settling shaped the present: you stepped back from the crowd then and thought it through, and the lamplit road has led all the way here.',
      present: "What's needed now is solitude, not more discussion: carry the question into the quiet and shine on it slowly — act after you can see clearly.",
      other: "Quiet is what they need right now: they've withdrawn inward to sort out their thoughts — not coldness, just wanting to think things through before they speak.",
      verdict: 'neutral',
      verdictReason: 'The Hermit gives no yes or no; it says the answer sits inside you, not yet lit — this question needs settling, not a conclusion forced out in a hurry.',
    },
    reversed: {
      keywords: ['isolation', 'refusing advice', 'overthinking', 'shutting people out'],
      core: "Reversed, the Hermit has turned solitude into an island: the door closed so long that 'needing no one' starts to feel like safety, or one thought circling deeper and deeper, further from the exit. Or the opposite: unable to be still at all, drowning the fear of solitude in noise. The lamp on the mountain is for lighting the road, not for hiding behind. Leave a crack in the door, and let someone you trust walk in.",
      daily: "Reach out today to a friend you trust but haven't spoken to in ages — any topic will do. Say the thing that's been circling in your head out loud just once; you'll be surprised how quickly it shrinks in your mouth.",
      love: "The heart has been shut long enough. Their knocking isn't meant to disturb you — it's an offer of company. Let them know what you're thinking, or the relationship will freeze over in the silence.",
      career: "Going it alone is starting to breed blind spots — the discussions you've been dodging hold exactly the pieces you're missing. Show up at one or two of them and hear the outside voices.",
      money: 'Too long buried in solo research narrows the judgment into a rut. Have a professional or an experienced friend check your reasoning once before you commit to the decision.',
      advice: 'Open the door a crack — say the thing you have long been turning over to someone you trust.',
      past: 'The door stayed shut too long, or one thought circled too deep; that stretch of isolation is why some pieces of the puzzle are still missing now.',
      present: 'Your task right now is opening a crack in the door: speak the bottled-up thing to someone trusted, and the blind spots finally get a chance to be lit.',
      other: 'Their door has been shut for a while: turning a worry over alone, spiraling the more they think — not quite ready yet to let anyone into their world.',
      verdict: 'leanNo',
      verdictReason: 'The reversed Hermit shows over-sealing, or thinking in circles without acting; holding this pattern only stiffens things — the lean here is toward slow down, toward no.',
    },
  },
  {
    id: 'major-10',
    name: '命運之輪',
    nameEn: 'Wheel of Fortune',
    arcana: 'major',
    number: 10,
    scene: 'A wheel marked with symbols hangs in the clouds: a serpent slides down its side, a red jackal-headed figure rises with it, a blue sphinx with a sword sits on top, and a winged man, eagle, lion and bull read at the four corners.',
    upright: {
      keywords: ['turning point', 'luck rising', 'cycles', 'riding the current'],
      core: "The sound of the Wheel turning tends to come just when you thought nothing would change: one phone call, one coincidence, one chance meeting, and the situation faces a new way. This card says the cycle is switching — and into the rising arc. You cannot control when the wheel turns, but you can decide whether you're present when it reaches the top: keep your work ready, so you can catch the chance when it arrives.",
      daily: "Stay flexible about off-plan changes today — a sudden invitation or an abrupt reshuffle may have a turning point hidden inside. If there's someone you've been meaning to contact or a chance you've been meaning to take, do it today; luck is working with you.",
      love: "The gears of fate are meshing: an unexpected meeting, or a turn in the relationship, could well arrive. Move with the change — don't rush to lock everything back into the original script.",
      career: 'A season of reorganizations and new openings: the change that seems to scramble your plans is often a door swinging upward. Stay visible, so the good luck can find you.',
      money: "Finances enter a tailwind stretch — unexpected income or opportunities may appear. But the wheel keeps turning: set aside reserves while the wind is good, and don't treat luck as the normal state.",
      advice: 'Catch the wheel while it is turning and ride it upward — and leave yourself margin for the next cycle.',
      past: 'An unplanned turn started all of this: that coincidence, that chance encounter, pushed the wheel onto its upward slope, and the momentum carries to now.',
      present: 'The wheel has turned onto its rising arc: stay flexible with change and keep your work ready, so the chance can be caught the moment it comes.',
      other: 'Their circumstances are shifting: the heart loosening as events move, open to new possibilities — and this relationship may be heading into a turn as well.',
      verdict: 'leanYes',
      verdictReason: 'The Wheel of Fortune brings an upward turn and the timing stands with you; but fortune runs in cycles — seizing the moment matters more than betting on forever.',
    },
    reversed: {
      keywords: ['bad timing', 'headwinds', 'resisting change', 'stuck in a loop'],
      core: "The reversed Wheel is the muddy downhill stretch: not a failure of effort — this stretch of road is simply hard. When things keep going wrong, the classic mistakes are heaving harder at the wheel, or blaming yourself for all of it. The cycle has simply reached its low, and the low's lesson is to conserve strength, build fundamentals, and keep this round's teachings. The wheel hasn't stopped — it will turn up again.",
      daily: "If nothing goes right today, lower the bar to 'bare minimum done' and don't arm-wrestle the headwind. Cancel whatever can wait and get to bed early — the best strategy for a slump day is simply letting it pass safely.",
      love: 'The relationship may be caught in a repeating loop — the same argument arriving in a new scene. Rather than blaming the timing, look for the pattern that has never actually been dealt with.',
      career: "Proposals blocked, timing off — store your energy instead of ramming the door. Use the shelved time to build skills and tidy the groundwork; when the wind shifts, you'll be the best-prepared one there.",
      money: 'The headwind rule is defend, not attack: postpone big spending and new investments, check the insurance and the emergency fund. Losing less is winning — wait for the page to turn.',
      advice: "In the low stretch, defend rather than attack; rest and wait for the wind to shift — don't force the wheel.",
      past: "Earlier you hit the cycle's low point: a stretch hard not for lack of effort but by the road itself — and it left the weariness you're carrying now.",
      present: 'You are in the headwind leg now: defend rather than attack, conserve strength, note what this round has taught you — the wheel will turn up again.',
      other: 'They are walking their own low stretch just now: most of their energy claimed by things going wrong, with little to spare for answering this relationship well.',
      verdict: 'leanNo',
      verdictReason: "The reversed Wheel shows the timing is not on your side and forcing it comes at a high cost; this isn't a forever no — it's a 'not right now.'",
    },
  },
]
