// English content for pentacles-08-14 (produced by content agents).
import type { TarotCard } from '../types'

export const pentacles0814: TarotCard[] = [
  {
    id: 'pentacles-08',
    name: '錢幣八',
    nameEn: 'Eight of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    rank: 8,
    number: 8,
    scene: 'A craftsman sits on a wooden bench, hammer and chisel in hand, carving a coin with full attention; six finished coins hang in a straight line on the post beside him, another rests at his feet, and a small town sits in the distance.',
    upright: {
      keywords: ['craft', 'focus', 'mastery', 'steady practice'],
      core: "The craftsman carves one coin at a time, and hangs each one up as he finishes it. This card is about the long road to real skill: not a burst of talent, but repeat, correct, repeat again. What you're doing right now may feel tedious, yet every round of practice is stacking up results you can actually see. Bring your attention back to the work in your hands — mastery is its own paycheck.",
      daily: "Pick one skill you want to get better at today and give it thirty uninterrupted minutes. Notifications off, one thing only — then tick it off on your calendar so you can watch the progress grow with your own eyes.",
      love: "Love takes the same care as a craft: remembering the small things your partner cares about, and doing them, builds more trust than a grand surprise. If single, tend your own life first — steady people attract.",
      career: "This is prime time to sharpen your expertise. Volunteer for work that lets you drill your core skill on repeat, and get your portfolio or track record in order — the skill will speak for you.",
      money: "Income follows skill level here. Instead of chasing quick money, invest in a course or credential that lets your craft raise your pay — and don't skip the basics like tracking your spending.",
      advice: 'Refine the craft, repeat it until it lives in your hands — the results will catch up.',
      past: "This position was hammered out one strike at a time: that earlier stretch of unglamorous, patient work is exactly what you're standing on today.",
      present: "The lesson is right there on the workbench — do this one thing carefully and thoroughly, and don't let noise beyond the work pull your attention away.",
      other: "They're head-down in their own work or study right now, grinding at it step by step. It isn't coldness — they want to get the thing in their hands right first.",
      verdict: 'leanYes',
      verdictReason: "The Eight of Pentacles is steady accumulation — things are moving the right way, but they need time and sustained effort, not one big leap.",
    },
    reversed: {
      keywords: ['going through motions', 'perfectionism', 'burnout', 'spinning wheels'],
      core: "Reversed, the chisel is still in your hand but the heart has left the room. Maybe the work has slid into box-ticking and the quality is slipping; or the opposite — you're so exacting about every detail that nothing ever ships. Both are stuck in the gap between doing and doing it well. Ask yourself first: do I still want to learn this? If yes, reset the standard. If no, it may be time for a different workbench.",
      daily: "Look at the task you keep botching or postponing today — don't just grit your teeth and push through. Find where it's actually stuck: wrong method, or tired heart? Treating the real cause beats brute force every time.",
      love: "Your relationship may be running on routine — dates that feel like clocking in. Don't complain it's boring; propose one small thing neither of you has done. If single, is busyness your way of avoiding people?",
      career: "Watch both extremes: shipping sloppy work that dents your reputation, or revising endlessly until the window closes. Align with your boss or client on what 'good enough' means, then decide how much to pour in.",
      money: "Burnout-driven treat-yourself shopping is the easiest way to bleed money right now. Set a small fun budget, and anything beyond it waits until you've slept on it.",
      advice: "Figure out whether it's won't-do or don't-know-how, then fix the method or change lanes.",
      past: "Somewhere along the way the effort lost its shape — phoned in, or polished past sense — and that off-balance way of working has carried through to now.",
      present: "You're at the going-through-the-motions crossroads: hands still moving, mind already gone. Sort out whether you're tired or the method is wrong before you continue.",
      other: "They're somewhat absent these days: the routine still runs, but the care behind it is loosening, with a weariness they can't quite name.",
      verdict: 'leanNo',
      verdictReason: "Reversed, the quality of effort is draining away; on the current approach the returns will be thin. Steadier to reset your state before pushing on.",
    },
  },
  {
    id: 'pentacles-09',
    name: '錢幣九',
    nameEn: 'Nine of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    rank: 9,
    number: 9,
    scene: 'A woman in a richly embroidered robe stands alone in a vineyard heavy with grapes, a hooded falcon perched on her gloved left hand; nine coins nestle among the vines, a snail crawls at her feet, and a manor rises in the distance.',
    upright: {
      keywords: ['harvest', 'self-reliance', 'graceful ease', 'earned rewards'],
      core: "The vineyard is hers because she tended it herself, and now she can stand in it with grace. This card is about abundance you earned on your own: financial breathing room, taste in how you live, and the quiet confidence of not needing to lean on anyone. Your earlier discipline is coming into fruit — enjoy it properly, and give yourself the credit. Solitude here isn't loneliness; it's ease.",
      daily: "Give yourself something today that matches the work you've put in: a meal eaten properly, a walk with no clock on it. While you enjoy it, don't scroll work messages — let body and mind actually register the signal that says 'I'm doing well.'",
      love: "Live your own life well first — that's this card's answer for love. Don't lower the bar just to be paired up; if you're together, keeping your own space and hobbies makes the bond healthier, not weaker.",
      career: "Past effort is entering its harvest season — a raise, work finally being seen, or a role with real autonomy. If you're negotiating now, you're holding more chips than you think.",
      money: "Your finances are on solid ground — a good moment to review your asset mix and put your money to work too. Buying quality isn't wasteful; buying to show off is.",
      advice: 'Accept what you earned with both hands, and plant another row for the next season of you.',
      past: "It all traces back to years of discipline: those days of tending the garden alone, planting today's breathing room one coin at a time.",
      present: "This is harvest time, and the real lesson is letting yourself enjoy it. Don't rush to find the next thing to be busy with — stand inside what you've grown first.",
      other: "They're living well and feeling full right now, centered on a life they built with their own hands — enjoying their independence, in no hurry to lean on anyone.",
      verdict: 'yes',
      verdictReason: "This is a card of results landing in hand — what you're asking about has the conditions to bloom, and the answer leans clearly toward yes.",
    },
    reversed: {
      keywords: ['financial dependence', 'keeping up appearances', 'overwork', 'isolation'],
      core: "Reversed, the vineyard still looks lovely, but the inside may be hollow. Maybe the income can't carry the lifestyle, and installments prop up the image; maybe your finances are tied to someone else — secure-looking, but with no real say; or your whole life has been mortgaged to earning, and the garden thrives with you nowhere in it. Take an honest inventory: which parts truly belong to you?",
      daily: "Spread out the past month's spending today and mark everything that was really 'for other people to see.' Pick one to cut this week, and move the savings toward debt or into savings — let substance take the seat that image was sitting in.",
      love: "Watch the balance: when one person depends on the other for money or daily life, it can slowly turn into leverage. If single, don't be dazzled by a glossy résumé — how they actually treat you matters more.",
      career: "The title and the substance may not match, or you may be trading endless overtime for a surface sense of achievement. Check honestly whether this effort is building an asset or just burning you down.",
      money: "Spending outrunning income is the warning light here. Cut subscriptions and impulse buys first — and if you're carrying revolving interest, killing it beats any investment you could make.",
      advice: 'Shrink the display, thicken the foundation — make the life genuinely yours first.',
      past: "The polish was held up by image or by leaning on someone, while the foundation never caught up — and that gap has stretched into today's strain.",
      present: "What confronts you is the gap between how it looks and what it rests on. Time to sort out which parts are truly yours and which are only borrowed light.",
      other: "They look composed, but inside they may be straining to hold it up — tied down by image, money or busyness, with less breathing room than they show.",
      verdict: 'leanNo',
      verdictReason: "Reversed, the shine sits on shaky footing; the current conditions can't yet carry the answer you want. Shore things up, then ask again.",
    },
  },
  {
    id: 'pentacles-10',
    name: '錢幣十',
    nameEn: 'Ten of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    rank: 10,
    number: 10,
    scene: 'A white-haired elder in a cloak embroidered with grapevines sits beside an archway, two white dogs nestled at his feet; under the arch a man and woman talk while a child tugs at her robe, and ten coins are arranged across the foreground.',
    upright: {
      keywords: ['family wealth', 'legacy', 'lasting stability', 'belonging'],
      core: "Three generations in one frame — even the dogs have their place. This is the Pentacles story reaching its full chapter: wealth that outlives one person. A family estate, an institution, foundations that can be handed down. What you're building or enjoying isn't only for yourself; it will shelter the people who come after. Lift your gaze — the decisions you make now deserve to be measured on a ten-year scale.",
      daily: "Do one thing today that paves the road ahead: sort out your insurance, have an honest money talk with family, or set up an automatic transfer into savings. And check in on an elder while you're at it — foundations are fed by small gestures like these.",
      love: "This relationship has a built-to-last quality: meeting the parents, merging finances, planning a home together are all supported. If single, your match may surface through family circles or old friends.",
      career: "Large institutions, family businesses and well-run organizations favor you now, and a senior mentor's backing is worth treasuring. When weighing career moves, put pensions and the long arc into the equation.",
      money: "A good season for long-horizon assets: property, retirement accounts, protection for your family are all the right direction. In this card money is a tool for passing things on, not a prop for showing off.",
      advice: "Make today's decision with ten-year eyes — leave room for your future self and your family.",
      past: "The root of this is groundwork laid by family or those before you; that long-accumulated shelter is what carried you to where you stand now.",
      present: "What's in your hands right now is bigger than your own affairs — it's something that can be passed on. Measure the choice in front of you on a long scale.",
      other: "Their mind is on the long game: family, security, foundations that can go the distance. Their thoughts are on a future that can be built together.",
      verdict: 'yes',
      verdictReason: "The Ten of Pentacles points to solid, lasting outcomes — what you're asking about rests on real foundations. A clear signal toward yes.",
    },
    reversed: {
      keywords: ['family disputes', 'shaken foundations', 'inheritance fights', 'gilded cage'],
      core: "Reversed, the house behind the archway starts letting in drafts. Maybe money has knotted the family — inheritance, who supports whom, who gave more; maybe a solid-looking institution can't be leaned on anymore; or the family's expectations have become a cage, security bought with freedom. This card isn't asking you to flip the table — just get the accounts clear and the boundaries drawn, so home can keep being home.",
      daily: "If money changes hands with family today, put it in writing — clear accounts between loved ones don't wound the relationship, they protect it. And go check one safety net you've been taking for granted; make sure it's still there.",
      love: "Differences between your two families may surface now. Don't let the elders' opinions steer the couple's decisions — stand on the same side as your partner first, then face outside pressure together.",
      career: "The organization's stability may be surface-deep — don't bet everything on a single employer. Watch the turf wars over resources too; keep your own work and records in order first.",
      money: "Slow way down on anything involving shared property, inheritance or joint ventures — read every clause. However close the person, the contract still gets signed.",
      advice: 'Turn vague verbal promises into clear black and white — boundaries are protection.',
      past: "The knot was likely tied at home long ago: an account never settled, a thing never said out loud — and it has been smoldering from then until now.",
      present: "Your task now is laying the vague agreements on the table — money and boundaries between family. Left unclarified now, it only compounds.",
      other: "They're preoccupied with family or practical entanglements — money, relatives, unresolved knots — and for the moment they can't free up a hand.",
      verdict: 'leanNo',
      verdictReason: "Reversed, there are cracks in the foundation and unresolved knots inside; pushing forward now invites complications. Mend within before moving out.",
    },
  },
  {
    id: 'pentacles-11',
    name: '錢幣侍者',
    nameEn: 'Page of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    rank: 11,
    number: 11,
    scene: 'A young man stands alone in a flowering meadow, holding a single coin up in both hands and studying it closely, as if trying to see inside it; behind him lie a freshly ploughed field and a stand of trees, with mountains in the distance.',
    upright: {
      keywords: ['new skills', 'practical start', 'good news', 'focused ambition'],
      core: "The Page holds the coin up close, the way a student studies a textbook they've just been handed. This energy is a practical beginning: a new course, a job opening, a modest sum worth researching — or a diligent young learner appearing around you, or that eager-student side of yourself waking up. The harvest won't be instant, but the direction is sound. Take this seed seriously, and it will be glad to sprout for you.",
      daily: "Do one small, concrete thing today for that idea that's been sprouting: look something up, sign up for an info session, ask someone who knows the field. The act of learning itself turns a vague notion into a path you can see.",
      love: "This connection is like a seed just planted — slow to grow but full of sincerity. Value the person willing to truly know you. Couples can learn something new together and keep a student's curiosity alive.",
      career: "Internships, field changes and invitations to study further all deserve serious consideration. If you're mentoring someone new, give a little extra — their steadiness will repay the whole team.",
      money: "Good money news may arrive — a small deposit, a new income channel. The amount won't be large, but it's exactly the right size to practice managing money with.",
      advice: 'Treat the interest like a course of study — learn it properly first, and the rewards will follow.',
      past: "It started as an earnest seed: a skill you genuinely studied, or a studious beginning made in good faith, and that laid the road you're on now.",
      present: "You're holding an opportunity worth studying. The task now is to learn seriously and look closely — turn the curiosity into proper coursework.",
      other: "They're like an earnest student, holding you — or the matter at hand — up close and studying it carefully. The pace is slow, but the sincerity is real.",
      verdict: 'leanYes',
      verdictReason: "The Page brings a promising start and good news — the direction is workable, but it's early days, and the results depend on the tending that follows.",
    },
    reversed: {
      keywords: ['short-lived zeal', 'procrastination', 'all talk', 'distracted'],
      core: "Reversed, the Page turns the coin over and over but never steps into the field. Plans sit in the bookmarks folder, the course was bought but never started, the savings pledge keeps breaking — wanting much, practicing little. Or someone nearby is all talk and no motion, dragging your progress with them. The dream doesn't need more inspiration. It needs an action list with dates on it.",
      daily: "Fish out the longest-shelved item on your dusty to-do list today and give it just fifteen minutes. Drop the bar to the floor and get the stalled wheel turning again — direction only matters once the wheel is moving.",
      love: "The flirtation may be stalled at 'let's see how it goes,' never landing. Instead of waiting, propose one concrete date. If you're partnered, check whether the small things you promised have quietly slipped.",
      career: "The learning has stalled, or the report keeps sliding — stop waiting to feel ready. Cut the big task into pieces you can finish today, ship a rough draft first and polish it after.",
      money: "Your money knowledge is stuck at the watching-videos stage while the cash sleeps in checking. Automate one small recurring deposit or investment — let the system do what willpower won't.",
      advice: 'Collect less inspiration, finish one more small thing — progress beats perfect.',
      past: "Most earlier plans stayed at the thinking stage — courses bought, not taken; words said, not done — and those shelved starts stacked into where things sit now.",
      present: "You're stuck at all-thought-no-motion: a pile of saved inspiration, and a first step never taken. Lower the bar as far as it goes and just start moving.",
      other: "They're still on the fence: interested, has even thought about acting, but the foot hasn't moved — the words haven't yet turned into anything concrete.",
      verdict: 'leanNo',
      verdictReason: "Reversed, the drive has scattered and the idea hasn't landed. Asking about outcomes now is premature — get moving first, then ask again.",
    },
  },
  {
    id: 'pentacles-12',
    name: '錢幣騎士',
    nameEn: 'Knight of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    rank: 12,
    number: 12,
    scene: 'A knight in full armor sits on a sturdy black horse standing perfectly still, holding a coin in both hands and gazing at it; oak leaves adorn his helmet and the horse\'s bridle, and neatly ploughed fields stretch behind him.',
    upright: {
      keywords: ['slow and steady', 'reliable', 'endurance', 'methodical'],
      core: "Every other knight is charging; this one has halted his horse and is studying the field, again and again. This energy is reliability itself: what he promises, he delivers — the pace may be slow, but he never fails to show up. He may be the unromantic but unshakeable person beside you, or the stance you need to take right now: don't chase speed, make every single step land solid.",
      daily: "Today suits the patient, routine work: reconciling accounts, clearing the inbox, finishing that form you've been dodging. Pick the one you least want to face, set a timer, and chew through it — nothing feels better than boring work done.",
      love: "Love here isn't sweet talk; it's showing up on time and doing what was said. Don't write off the slow-burn person as dull. If partnered, steady companionship builds more security than the occasional fireworks.",
      career: "You're the person people trust with the long, unglamorous assignments — and that reliability is being noticed. Roles built on steadiness — operations, quality, process work — especially favor you now.",
      money: "Recurring investments, forced savings — the boring-but-effective methods are your answer. No hot stocks, no tips from friends; time sides with discipline.",
      advice: "Follow the plan one step at a time. Slow is fine — stopping is the only real waste.",
      past: "This position was ground out slowly — by your own endurance, or by someone who did what they said and quietly held things up the whole way.",
      present: "Right now the contest is patience, not speed. Put your attention on finishing what's scheduled — and that steady person nearby is worth leaning on.",
      other: "They're the do-what-they-said kind, advancing steadily at their own pace right now. Not fast on their feet — but the heart has been there the whole time.",
      verdict: 'leanYes',
      verdictReason: "The Knight's pace is steady and sure — it will come together, but in the slow lane. If you can wait and keep at it, the answer leans yes.",
    },
    reversed: {
      keywords: ['stagnation', 'stuck in a rut', 'overwork', 'stubbornness'],
      core: "Reversed, the horse isn't steady — it can't move. Days run on autopilot until they go numb, work reduced to habit; or 'being careful' becomes the shield that says no to every change. Or the opposite — duty has you running so far past capacity that even stopping feels like guilt. Stability is a means, not the destination. When it starts caging you, it's time to renegotiate the terms.",
      daily: "Slip one small variation into the fixed route today: a different way to work, a different lunch spot, your routine tasks in a new order. A tiny shift is enough to remind your brain that you still have choices.",
      love: "The bond may be stable to the point of standstill — the same date on repeat for years. Break the pattern with one new proposal. If single, check whether 'letting fate decide' is really just not acting.",
      career: "Watch whether you've camped in the comfort zone so long your skills have stopped updating. And take the overwork signals seriously — if fatigue or discomfort persists, don't tough it out; get it checked early.",
      money: "Play it too safe and inflation quietly eats your buying power. With the principal protected, set aside a small slice to practice taking reasonable risk.",
      advice: 'Loosen one notch of the fixed rhythm and let change in through the smallest gap.',
      past: "The same rhythm ran for too long, and stability slid into stagnation without anyone noticing — that immovable horse has been standing there ever since.",
      present: "You're caught in an inertia that won't move — maybe you've stiffened up, maybe you've hit someone immovable. Loosen the smallest notch first.",
      other: "They're staying put for now — settled into how things are, or simply worn out — and not planning to change anything just yet.",
      verdict: 'neutral',
      verdictReason: "Reversed this is stagnation, not refusal — the matter hangs in place, neither advancing nor retreating. Willingness to change approach decides which way it tips.",
    },
  },
  {
    id: 'pentacles-13',
    name: '錢幣王后',
    nameEn: 'Queen of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    rank: 13,
    number: 13,
    scene: 'A stately woman sits on a stone throne carved with fruit and beast heads, gazing down at the coin cradled in her lap; roses climb into an arch overhead, greenery grows thick around her, and a hare leaps past in the lower right.',
    upright: {
      keywords: ['warm practicality', 'nurturing', 'abundance', 'homemaking'],
      core: "She cradles the coin in her lap like a life entrusted to her care. This energy is warm, practical tending: a home kept in order, money spent where it counts, the people around her fed, warm, and heard. She may be the person in your life who quietly keeps everything running — or the shape you're growing into: able to earn and able to care for, powerful in the quietest way.",
      daily: "Tend to whatever holds your life up today: cook a proper meal, put the messy room back in order, check in on the family member who's always the one giving. Settle the environment, and the heart settles with it.",
      love: "Warmth you can build a life on counts for more than sparks here — notice who remembers whether you're warm enough. If partnered, turn affection into concrete care; a bowl of hot soup beats a thousand words.",
      career: "Your gift for settling a team is exactly your value now — admin, HR, care work and education especially shine. Work arrangements that balance family and income also favor you.",
      money: "Live within your means without shortchanging the family — that's this card's philosophy. A good time to review the household budget and protections, so every dollar lands both warm and precise.",
      advice: 'Take care of yourself and your people first — abundance grows out of a settled home.',
      past: "This steadiness didn't come from nowhere: someone like her quietly kept everything in order, or your own years of practical care have been taking root.",
      present: "The task at hand is settling things — caring properly for people and place, or taking the hand that warm, practical person is holding out to you.",
      other: "Their heart is in a warm, practical place right now — thinking about how to look after you and everything around you, showing they care through what they do.",
      verdict: 'yes',
      verdictReason: "Nourishment and resources are both in place with this card — the matter has backing and solid ground under it. The answer leans firmly yes.",
    },
    reversed: {
      keywords: ['running on empty', 'self-neglect', 'control', 'scarcity mindset'],
      core: "Reversed, she has taken care of everyone — except herself. The caring may have become a one-way drain, quietly compounding into resentment; or money and looking-after may have turned into a way of controlling the family; or there's a hole in the sense of security that no amount of stockpiling fills. Giving with no return flow withers even the richest garden. Put yourself back at the top of the care list.",
      daily: "Do one thing for yourself today that you normally only do for others: eat a proper meal, sleep on time, turn down one request that's beyond your capacity. You are not anyone's support crew — you need looking after too.",
      love: "Check whether the giving in this relationship is badly lopsided. Say the resentment out loud instead of letting it harden into coldness. If single, don't go looking for a mother — or an ATM — in a partner.",
      career: "Beware of becoming the office's unpaid caretaker, with every stray chore landing on you. Learn to say 'that's not in my role' — your expertise only gets priced right once you do.",
      money: "Scarcity pushes people to extremes: hoarding bargains, or spending nothing on yourself at all. Before buying, ask 'is this a need or an anxiety?' — the answer tends to be honest.",
      advice: 'Put yourself back on the priority list — only people who care for themselves can keep caring.',
      past: "Much of the earlier giving went out and never came back: everyone looked after except yourself, and that depletion has been accumulating all the way to now.",
      present: "You're facing a lopsided caring arrangement. Time to put yourself back on the list — and to see clearly the control that's been dressed up as looking-after.",
      other: "They're carrying a lot of quiet fatigue and hurt: giving so much yet feeling uncaught. Right now, they're the one who needs some looking after.",
      verdict: 'leanNo',
      verdictReason: "Reversed shows the energy running at a loss, the foundation being drained. Stop the imbalance before advancing — a forced yes now breeds regret.",
    },
  },
  {
    id: 'pentacles-14',
    name: '錢幣國王',
    nameEn: 'King of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    rank: 14,
    number: 14,
    scene: 'The King sits on a throne carved with bull heads, his robe covered in grapevines and fruit, a scepter in his right hand and his left resting on a coin; an armored foot shows beneath the robe, and a castle rises behind him.',
    upright: {
      keywords: ['accomplishment', 'wealth', 'steady leadership', 'generosity'],
      core: "Grapes cover the King's robe and the castle stands right behind him — he has already proven himself. This energy is mature abundance: knowing how to earn, and better still, how to keep and to share. He may be the elder or boss around you worth seeking counsel from, or the seat you're moving toward yourself: let the track record do the talking, and let people feel steadier because you're there.",
      daily: "Run one decision today through a balance-sheet lens: is it adding an asset or a liability? Or arrange coffee with someone further down the career road than you — standing on shoulders saves years of walking.",
      love: "Mature, dependable, responsibility-carrying partners are favored now. If partnered, give security through concrete plans — real numbers on the table when you talk about the future is both romance and sincerity.",
      career: "Your expertise and judgment are in harvest season — time to negotiate a raise, take on bigger resources, or become a mentor. When deciding, remember your word now moves more than just you.",
      money: "The season for big-picture financial planning: asset allocation, tax, succession — bring in professionals to look with you. You're past the luck-chasing stage; steady is worth more than fast.",
      advice: 'Carry it with the strength you spent years building — and remember to share the harvest down.',
      past: "Today's confidence was bought with results: the steady stewardship that came before, or a reliable elder's backing, paved the way to this step.",
      present: "You're standing at the harvest, hand on the tiller. The task is to deploy resources well — hold the big picture steady, and remember to be generous.",
      other: "They're in a grounded, well-resourced state, thinking in realistic and long-range terms — and more used to showing they care through practical arrangements.",
      verdict: 'yes',
      verdictReason: "The King stands for proven strength and resources in hand — what you're asking about has ample backing beneath it. A solid, steady yes.",
    },
    reversed: {
      keywords: ['greed', 'rigid and old-guard', 'money as power', 'mercenary'],
      core: "Reversed, the King clutches his coin and forgets there's a world beyond the castle. It may be net worth mistaken for human worth, everything priced in money; a power-holder too rigid and old-guard to hear new voices; or someone leaning on wealth or status to pressure others. If this is you, beware winning the ledger and losing the room. If it's someone you face, don't play who's-bigger inside his rules.",
      daily: "Notice today whether 'is it worth it' keeps getting converted straight into money — a relationship, a favor, an afternoon. Pick one thing and do it purely because you love it, with no return-on-investment math attached.",
      love: "Be wary of a relationship steered by material terms — gifts are no substitute for listening. If someone keeps pricing your worth in money, state your bottom line plainly: love is not an acquisition.",
      career: "The person above you may be entrenched and forceful — head-on collision wins nothing. Translate your proposal into the language he cares about, risk and return, and keep your own exit in good repair.",
      money: "Guard your judgment against greed: returns too good to be sensible, leverage that bets the house — step back from both. And don't trade health or credit to save small change.",
      advice: "Don't let price drown out value — goodwill and credit are the assets money can't buy back.",
      past: "The knot mostly traces to profit coming first: someone wielded money as pressure, or clung hard to what they had, and the standoff was tied there.",
      present: "You're facing a situation ruled by interests or authority. Watch that you don't slip into the same arithmetic — and don't compete over whose pockets are deeper.",
      other: "They're weighing practical gain very heavily right now — position firm, hard to move, and unwilling to budge until the terms have been sized up.",
      verdict: 'no',
      verdictReason: "The reversed King is captive to profit and locked into his course — continuing this direction costs more than it gains. This one is a clear no.",
    },
  },
]
