// English content: pentacles-01 … pentacles-07 (7 cards).
// Meaning source: ../pentacles-01-07.ts (zh). Tone anchor: The Fool in en/major-00-10.ts.
// name/nameEn/ids MUST mirror the zh files and registry; verdicts MUST match zh.
import type { TarotCard } from '../types'

export const pentacles0107: TarotCard[] = [
  {
    id: 'pentacles-01',
    name: '錢幣一',
    nameEn: 'Ace of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    rank: 1,
    number: 1,
    scene: 'A hand reaches out from a grey cloud, holding a large golden coin in its open palm; below, a garden blooms with white lilies, a trimmed green hedge opens into an archway, and a path leads through it toward distant mountains.',
    upright: {
      keywords: ['new opportunity', 'abundance', 'solid start', 'tangible gain'],
      core: "A hand from the sky places a real, solid coin in front of you — not a daydream, but an opportunity you can actually touch: a job, an income, a plan that can land. The Ace of Pentacles is about a good beginning on the material plane. The seed is in your hand and the soil is ready. All that's left is to plant it and tend it day by day, letting it slowly grow into what you want it to be.",
      daily: 'Keep an eye out for concrete opportunities today: a job posting, an invitation to collaborate, a small savings plan you could start. Pick the most tangible one and take the first action before the day ends — send the résumé, or just open the account.',
      love: "Love has a real chance of settling into something steady and grounded. If you're single, someone practical and reliable may appear; if you're together, talk shared plans — saving up, moving in.",
      career: 'A new position, a new project or a raise is taking shape — and this one comes with real conditions behind it. Seize the moment to put your plan on the table; your odds are better than usual.',
      money: 'Financially this is a good seed: a new income stream or something worth building long-term may appear. What matters is getting started — put the money in motion so it can grow.',
      advice: 'The opportunity is already in your hand — take the first step today and put the seed in the ground.',
      past: 'Trace it back to the start — a very real opportunity was placed in your hands: that job, that money or that plan was the first seed of where things stand now.',
      present: 'A tangible opportunity sits right in front of you, and the conditions are in place. The point now is to plant it with your own hands — not to keep watching.',
      other: "Right now their mind is on practical things: they're holding a concrete opportunity or plan, and they genuinely want to start building on solid ground.",
      verdict: 'yes',
      verdictReason: 'The Ace of Pentacles is the most solid card of beginnings — the opportunity is concrete and the conditions are met, so what you ask about has an excellent base to land on.',
    },
    reversed: {
      keywords: ['missed opportunity', 'castles in the air', 'shaky foundation', 'delay'],
      core: 'Reversed, the coin has slipped from the palm: the opportunity is still nearby, but your grip on it isn\'t steady. Maybe the plan sounds beautiful but has no real numbers behind it, maybe you hesitated until the moment passed, or maybe the "great deal" simply doesn\'t hold up to scrutiny. Come back down to earth and lay out the costs, timeline and risks one by one — a real opportunity survives that kind of inspection.',
      daily: "Don't rush to sign anything today, especially a proposal that sounds too perfect. Spend twenty minutes writing down its actual numbers: how much goes in, how long until it pays back, what the worst case looks like. If you can't write them down, set it aside.",
      love: 'The bond may be living on lovely imagination without much real time together or real commitment. Rather than waiting for promises, watch whether their actions keep up with their words.',
      career: "A deal or offer that seemed locked in may shift, so don't speak too soon. Meanwhile, check whether your own plan has only a vision — and no executable steps.",
      money: 'Beware of "can\'t-lose" investments and hasty big purchases. Lean conservative with money decisions for now; keeping your cash flow steady matters more than catching every opportunity.',
      advice: "Lay out the numbers on this opportunity and check them one by one — if it can't survive the math, let it go.",
      past: 'The start was never caught cleanly: an earlier opportunity was lost to hesitation or wishful thinking, and that loose foundation has shaped things ever since.',
      present: 'The plan in your hands is hanging in mid-air, its numbers still unclear. Your task now is to lay out the costs, timeline and risks one by one and test them.',
      other: "They're a bit up in the air at the moment: the ideas sound lovely but haven't landed, and their grip on the opportunity in front of them isn't steady yet.",
      verdict: 'leanNo',
      verdictReason: 'The reversed Ace of Pentacles shows a shaky foundation or bad timing — what you ask about lacks the conditions to land right now, so shore things up first.',
    },
  },
  {
    id: 'pentacles-02',
    name: '錢幣二',
    nameEn: 'Two of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    rank: 2,
    number: 2,
    scene: 'A young man in a tall red hat dances on one foot, a coin in each hand, the two coins joined by a green ribbon looped into a figure eight; behind him the sea heaves, and two sailing ships ride up and down on the waves.',
    upright: {
      keywords: ['juggling', 'flexibility', 'balancing acts', 'dancing with the waves'],
      core: "Two coins pass back and forth inside a ribbon shaped like infinity, and however high the waves rise behind him, the young man keeps dancing. This is a portrait of you handling several things at once: work and family, two incomes, a stack of projects. The key isn't deciding what to drop — it's finding your rhythm. Manage time and resources with flexibility, and even a busy life can be busy with a beat.",
      daily: "Your schedule is probably packed today. Instead of grinding through all of it, spend five minutes first setting priorities: move what can wait to another day, explicitly, and leave yourself a pocket of air. That's how the rhythm lasts.",
      love: "Love is competing with your other roles for time. What your partner wants usually isn't a grand gift — it's a slot on your calendar. Block out a stretch this week that belongs to just the two of you.",
      career: 'Multiple tasks are running at once, and what\'s being tested is coordination, not brute force. Learning to say "I can get this to you Thursday" is exactly the workplace skill this card is here to teach.',
      money: "Money in, money out — your finances are a juggling act. Make a simple cash-flow sheet so you know when each ball comes down, and you won't be caught scrambling.",
      advice: 'Set your priorities and meet the busyness with rhythm, not by gritting your teeth.',
      past: 'Behind you lies a stretch of running several tracks at once: you took on many things together, and the coordination trained mid-juggle built what you have now.',
      present: "You're finding your rhythm among several balls in the air right now. The key isn't which one to drop — it's getting the order right so the busyness has a beat.",
      other: "They're maneuvering between several commitments, their time sliced thin; their head is still in the juggle, looking for a rhythm that keeps everyone happy.",
      verdict: 'leanYes',
      verdictReason: 'The Two of Pentacles shows a situation that is busy but manageable — with good coordination it holds, so what you ask about leans workable but needs flexibility.',
    },
    reversed: {
      keywords: ['overload', 'off balance', 'dropped balls', 'white-knuckling it'],
      core: "Reversed, the balls are starting to fall. The schedule runs past midnight, promises slip, the body protests with small ailments — all overload signals. The problem isn't effort; you've taken on more balls than two hands can throw. Take an honest inventory: what can be declined, delayed, or handed off? Catching one less ball isn't failure — it's the only way to keep the rest from hitting the ground.",
      daily: "Write out your entire to-do list today, circle one thing that can be declined or postponed — and then actually say the words to whoever needs to hear them. You'll find that the moment you say it out loud is far lighter than you imagined.",
      love: "Busyness has reduced the relationship to logistics — handoffs and schedules. Admitting you're overloaded and asking your partner to carry some of it will bring you closer than pretending everything's fine.",
      career: 'Parallel projects are starting to drag each other down, and slipping quality hurts more than a slipping deadline. Flag it early and reschedule — far better than pulling all-nighters to firefight later.',
      money: 'Watch for the robbing-Peter-to-pay-Paul cycle, especially using credit cards or loans to cover daily expenses. List out every debt first; facing it is safer than avoiding it.',
      advice: 'Deliberately put one ball down, and keep the most important ones from hitting the floor first.',
      past: 'It traces back to taking on too much: promises accepted one at a time quietly stacked up, and the overload began right there.',
      present: "The balls are dropping. What's needed now isn't more effort — it's honestly picking one thing you can decline, to protect the few that matter most.",
      other: "They're close to overload right now: too many stacked commitments, balls starting to drop — most likely the spirit is willing but the hands are full.",
      verdict: 'leanNo',
      verdictReason: 'The reversed Two of Pentacles shows the load has already exceeded capacity — adding more risks tipping everything over. This is a moment to subtract, not add.',
    },
  },
  {
    id: 'pentacles-03',
    name: '錢幣三',
    nameEn: 'Three of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    rank: 3,
    number: 3,
    scene: 'Under a church archway, a young stonemason stands on a wooden bench with tools in hand while a monk and a cloaked figure hold up architectural plans and confer with him; three coins are carved into the stone arch above.',
    upright: {
      keywords: ['teamwork', 'recognized skill', 'craftsmanship', 'division of labor'],
      core: "The mason's craft, the monk's resources, the designer's plans — three roles, each doing its part in the same cathedral. This is the card of getting something done well together. Your skill is being noticed, and people want to build the quality with you. Don't go it alone: spread the plans on the table, talk it through, make the roles explicit. The work will turn out better than anything one of you could build solo.",
      daily: "Today is a good day to call a small huddle: show what you're working on to a teammate or colleague and hear their angle. One concrete move — book fifteen minutes, bring the half-finished thing, and ask for two specific improvements.",
      love: 'A relationship is a joint construction project; it takes two people sharing the work. Finishing one small thing together — assembling furniture, planning a trip — lands better than ten sweet nothings.',
      career: "Your professional skill is catching the attention of managers or clients — this is the moment to build a reputation. Get every detail right, and don't be shy about letting people know which part is yours.",
      money: 'Joint ventures and partnership deals look promising — provided the profit split and responsibilities are written down in black and white. Money earned through honest craft accumulates, slowly and surely.',
      advice: 'Find the right people to build with, and agree on the division of labor and the standards before breaking ground.',
      past: 'Collaboration laid this foundation: someone shared the work and built the quality up with you, and that experience of good teamwork is what today stands on.',
      present: "Your skill is being seen, and this stage calls for building together. Spread out the plans and make the division of labor clear — that's the task at hand.",
      other: "Their focus right now is on doing the work well: they care about quality and clear roles, and they're willing to sit down, talk it through, and build brick by brick.",
      verdict: 'yes',
      verdictReason: "The Three of Pentacles shows both skill and collaboration in place — there's structure and there's support, so what you ask about has a high chance of coming together.",
    },
    reversed: {
      keywords: ['working in silos', 'phoning it in', 'unappreciated', 'mismatched standards'],
      core: "Reversed, the three figures stop talking: the plans are the plans, the stonework is the stonework, everyone in their own corner. Maybe no one made the standards explicit, maybe your care is taken for granted, or maybe you've started phoning it in — since nobody seems to care anyway. Go back to the plans: what exactly is the goal? Who owns which piece? Reconnect the conversation, and the work can still be saved.",
      daily: "If work feels stuck today, first check whether communication has gone dead. Pick the collaborator you're most out of sync with and set up a direct progress check — realign expectations, and the blockage often clears on the spot.",
      love: 'You two are investing in the relationship by different standards — one feels they\'ve given everything, the other feels brushed off. Say "here is what I need" in concrete terms; don\'t make them guess.',
      career: 'When effort goes unseen, slacking off gets tempting — but letting your quality slide ultimately damages your own name. Push for one proper chance to present your results before deciding whether to stay or go.',
      money: 'Partnerships and split bills are prone to mismatched assumptions right now — turn verbal agreements into writing early. And steer clear of suspiciously cheap goods of unclear origin and quality for a while.',
      advice: 'Reconnect the broken line of communication. Align on standards first — then talk about who does more and who does less.',
      past: 'The cause hides in broken communication: everyone worked in their own corner, standards never aligned, and the gaps nobody talked out have piled up ever since.',
      present: "The collaboration is running in silos, and your care isn't being seen. Your task is to reconnect the conversation — align on standards first, then move forward.",
      other: "They're a bit siloed from the people around them at the moment: feeling their effort goes unseen, saying less and less, their investment quietly cooling.",
      verdict: 'leanNo',
      verdictReason: 'The reversed Three of Pentacles shows collaboration breaking down and standards in disarray — on the current course quality will suffer, so what you ask about faces real headwinds.',
    },
  },
  {
    id: 'pentacles-04',
    name: '錢幣四',
    nameEn: 'Four of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    rank: 4,
    number: 4,
    scene: 'A crowned man sits on a stone bench, arms clutching a coin tight against his chest, another balanced on top of his crown, and one under each foot; behind him rise the rooftops and towers of a city.',
    upright: {
      keywords: ['holding ground', 'security', 'control', 'gripping tight'],
      core: "Four coins: one hugged to the chest, one on his head, two pinned under his feet — he won't let go of a single one. The Four of Pentacles is the card of holding what you have: you've accumulated something and you have the ability to keep it, and that stability is a real achievement. But hold the same posture too long and your hands are never free to catch anything new. Ask yourself: is this grip protection — or fear?",
      daily: "Take stock today of what you're guarding: savings, a position, the status quo of a relationship. Pick one and imagine loosening your control by ten percent — the answer may not be as scary as you think.",
      love: "Wanting to keep someone close is understandable, but the tighter the grip, the more they need air. Security has to grow from inside you; it can't be traded for through control.",
      career: "A secure position and steady performance — that's something you earned by defending it. But pure defense means missed growth. Every so often, allow yourself a calculated risk.",
      money: "Your saving discipline is excellent and your assets are safe. Still, check whether you've become overly conservative — inflation quietly eats cash that just sits there being hugged.",
      advice: 'Hold firmly what deserves holding — but keep one hand free to catch what comes next.',
      past: 'The present situation was guarded into existence: you held your gains tightly, and that caution brought stability — while quietly restricting the flow.',
      present: "You're clutching what you've built, afraid to loosen your grip. Figure out whether this is protection or fear — then keep one hand free for new possibilities.",
      other: "They're holding on tight right now: they treasure the security they have, are wary of any change, and would rather keep the status quo than take a chance.",
      verdict: 'leanYes',
      verdictReason: 'The energy of the Four of Pentacles is stability and keeping — if the question is "can I hold onto it," mostly yes, though a big breakthrough is unlikely.',
    },
    reversed: {
      keywords: ['letting go', 'feeling out of control', 'miserliness', 'fear of loss'],
      core: "Reversed, this card goes one of two ways. One: the grip tightens further — pinching pennies at the cost of health and relationships, living like a miser. Two: you finally open your hand — spending what should be spent, releasing excess control. The test is simple: if letting go leaves you lighter, that's progress; if it leaves you panicked, your security isn't rooted yet — and that fear deserves your care first.",
      daily: 'Watch your reactions to "losing" today: someone cuts in line, a plan gets changed, a little money slips away. If every one of these winds you up tight, take a deep breath and remind yourself — nothing that truly matters has actually gone anywhere.',
      love: 'Fear of loss can turn a relationship into surveillance — or, you may be learning to give each other room. Head toward the latter: trust is when you open your hand and they choose to stay.',
      career: "Job insecurity may be keeping you from delegating or from taking a vacation. Hand off a piece of the work — the sky will not fall, and you'll gain room to actually think.",
      money: 'Two extremes to avoid: revenge spending and total tightfistedness. Set a monthly "free to spend" allowance — a little humanity kept inside the discipline.',
      advice: 'Practice letting go once, deliberately — starting with the smallest, least painful thing.',
      past: 'The cause is tangled up with gripping too hard: past over-control of money or of a relationship — or one hasty letting-go — planted the unease you feel now.',
      present: 'To hold or to release — the tug-of-war is inside you. What needs care now is the fear of losing; practice loosening your grip, starting with the smallest thing.',
      other: "They're caught in the push-pull of fear of loss: wanting to hold on, afraid of holding too hard — the unease runs deeper than it looks from outside.",
      verdict: 'neutral',
      verdictReason: 'The reversed Four of Pentacles hangs between holding and releasing — the outcome depends on how and when you let go, so with the direction unsettled, the answer stays neutral.',
    },
  },
  {
    id: 'pentacles-05',
    name: '錢幣五',
    nameEn: 'Five of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    rank: 5,
    number: 5,
    scene: 'On a snowy night two ragged figures pass outside a church wall: one on crutches with a bell at his neck, the other barefoot in a shawl, head bowed; the stained-glass window above glows with light, five coins shining in the glass.',
    upright: {
      keywords: ['scarcity', 'hardship', 'illness', 'a door to knock on'],
      core: "Snow, rags, crutches — this card paints scarcity honestly: not enough money, a body acting up, or feeling locked out. The road is genuinely hard, and you don't have to pretend you're not cold. But look up: the lit window is right beside them. The light was there all along — hurrying with your head down, you just can't see it. What you lack may not be resources but one step: asking for help, pushing the door open.",
      daily: "Stop soldiering on alone today. Boil your most urgent difficulty down to one sentence and say it to someone who can hear it — family, a friend, a support channel at work. And if something has been physically wrong and you've been putting it off, book the doctor's appointment today.",
      love: 'Feeling unloved, or grinding through hard times together — the danger is silence on both sides. Saying "I\'m having a hard time" out loud lets the other person come closer, and the winter gets much shorter.',
      career: 'In a trough of job loss, pay cuts or being sidelined, holding the baseline counts as a win. Meanwhile, knock on doors: applications, training subsidies, introductions — there are more doors than you think.',
      money: 'When money is tight, stop the bleeding before planning the comeback: list the essential expenses, negotiate deferrals, look up assistance programs. Being willing to ask for help is itself the first step out.',
      advice: 'Look up and find the lit window — ask for help. And if your body is unwell, see a doctor without delay.',
      past: "Underneath this matter lies a stretch of real scarcity: the shortage, the illness, or the feeling of being shut out — that's what carried you to where you now stand.",
      present: "You really are walking in the cold wind, and there's no need to pretend otherwise. But the lit window is right beside you — your task is to look up and ask for help.",
      other: "They're not doing well themselves right now: money tight, or worn thin in body and spirit, head down and pushing through — they may not have much left for your side.",
      verdict: 'no',
      verdictReason: 'The Five of Pentacles shows resources and conditions clearly short right now — what you ask about is hard to achieve. Take care of yourself first and wait for the timing.',
    },
    reversed: {
      keywords: ['coming out of the cold', 'accepting help', 'recovery', 'first light'],
      core: "Reversed, the snow is starting to stop. Maybe a new job is taking shape, your health is turning a corner, or you're finally willing to take the offered hand. The worst stretch is passing — but recovery is gradual: keep the follow-up appointments, fill the money hole one payment at a time, rebuild confidence win by win. Don't rush back to your old pace at the first improvement; going slowly is what makes it stick.",
      daily: "This is a day for one small steadying act: answer that notice you've left sitting, book the follow-up appointment you're due for, pay back one small debt. Recovery is exactly this — concrete little actions, layered one on top of another.",
      love: "A frozen relationship is beginning to thaw, or you're finding the strength to be close to people again. Give it time — let trust come back the way a fever breaks, a little more each day.",
      career: "The turn after the trough is surfacing: interview invitations, new projects, a well-placed introduction. You don't need to be at full strength yet — catch the opportunity first and recover as you go.",
      money: "The tightest moment is passing, and there's finally a little room for small savings. Write down what this episode taught you — build a line of defense for your future self.",
      advice: "Take the hand that's being offered, recover step by step, and don't try to get there in one leap.",
      past: 'The coldest stretch is behind you: the hardship and gritting-through are how things got here — and they taught you to accept the hand someone offered.',
      present: "The snow is stopping and you're standing at the start of recovery. Put your attention on the small steadying acts, one at a time — don't rush back to your old pace.",
      other: "The hardest part is passing for them: they're slowly steadying, starting to accept help — the strength just isn't all the way back yet.",
      verdict: 'leanYes',
      verdictReason: 'The reversed Five of Pentacles signals winter nearing its end — the situation is improving and what you ask about should keep getting better, but it cannot be rushed.',
    },
  },
  {
    id: 'pentacles-06',
    name: '錢幣六',
    nameEn: 'Six of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    rank: 6,
    number: 6,
    scene: 'A merchant in a red robe stands holding a balanced scale in his left hand while his right hand gives coins to two cloaked beggars kneeling before him; town buildings and towers rise in the background.',
    upright: {
      keywords: ['generosity', 'mutual aid', 'resources in flow', 'fair giving'],
      core: "One hand holds the scale level, the other gives — a picture of resources flowing in balance. You may be the giver: offering help within your means while the scale stays level. Or the receiver: there's no shame in accepting help right now — pass it along when you have room to spare. Giving and receiving are upstream and downstream of the same river. Let money, time and goodwill keep moving, and everyone lives better.",
      daily: "Set one resource in motion today: donate a small amount, pass something you no longer use to someone who needs it, or spend a little time mentoring someone junior. And if you're the one who needs help — ask today; someone will catch you.",
      love: 'Giving and receiving need to flow both ways: give one-way forever and you burn out; receive one-way forever and guilt piles up. Swap roles today — let the one who usually gives be taken care of.',
      career: "Benefactors are near: a senior colleague's backing, an introduction to resources. When help comes, accept it graciously — and remember to reach back and pull someone else up later.",
      money: 'Money in and money out are finding balance — a good moment for donating, lending, or repaying. Any lending should work like that scale: terms stated up front, so both sides sit comfortably.',
      advice: "Give when you have room to spare, receive when you're in need — and let resources flow inside trust.",
      past: 'The source is a flow of resources: someone pulled you up at a critical moment, or your own past generosity paved the way for where things stand now.',
      present: "The river of giving and receiving flows right past you: extend a hand if you have room, speak up if you're in need. The task is keeping resources in motion.",
      other: "They're in a giving mood right now: they have room to spare, enjoy contributing and sharing — and they care whether the exchange between you stays fair and even.",
      verdict: 'leanYes',
      verdictReason: "The Six of Pentacles shows resources and goodwill flowing — people are willing to help, so what you ask about leans favorable, though it depends on others' cooperation.",
    },
    reversed: {
      keywords: ['strings attached', 'unequal exchange', 'debt pressure', 'false generosity'],
      core: 'Reversed, the scale tips. Giving becomes a means of control — "after everything I\'ve done for you…" — and receiving becomes a debt that can never be repaid. Or you\'ve been giving to the wrong people, or you\'re caught in a borrowing cycle. Examine the terms behind every gift: real help never demands your dignity or freedom in exchange. Anything that makes your voice smaller each time you accept it is not kindness.',
      daily: 'Take a hard look today at one give-and-take arrangement that quietly makes you uncomfortable: does that help come with invisible strings? If so, start keeping a record of what you actually give and receive — it will be your evidence when you draw the line later.',
      love: "Binding someone with what you've given, or staying in a relationship out of indebtedness — neither is what love looks like. Lay the ledger open and talk it through; that's the only way back to equal footing.",
      career: 'Beware of exploitation wrapped in "this is for your own good": double the workload traded for vague promises. Negotiate the terms explicitly — your expertise deserves a clearly marked price.',
      money: "Take inventory of debts, financial and personal alike: a repayment plan for what you owe, and ask gently but clearly for what's owed to you. New invitations to borrow or lend, politely decline for now.",
      advice: 'See the strings behind the help clearly. Draw the lines that need drawing, and put what you owe on a repayment plan.',
      past: 'Looking back, that help came with conditions attached: an unequal exchange, or a personal debt, has been pressing on things all the way to now.',
      present: "The scale is tipped right now, and you're inside an unequal exchange. First see the strings behind the help clearly, and get the terms out in the open.",
      other: "They're keeping a ledger in their head — what they've given and what's come back. They feel the exchange is uneven, and what they give comes wrapped in expectation.",
      verdict: 'leanNo',
      verdictReason: 'The reversed Six of Pentacles shows giving and receiving out of balance with murky terms — what you ask about risks leaving you at a disadvantage, so clarify the price first.',
    },
  },
  {
    id: 'pentacles-07',
    name: '錢幣七',
    nameEn: 'Seven of Pentacles',
    arcana: 'minor',
    suit: 'pentacles',
    rank: 7,
    number: 7,
    scene: 'A young farmer stands at the edge of a field leaning on his hoe, chin resting on his folded hands, gazing down at a lush tangle of vines beside him — seven coins ripening among the leaves.',
    upright: {
      keywords: ['awaiting harvest', 'taking stock', 'patience', 'midpoint review'],
      core: 'The farmer sets down his hoe and studies the seven coins on the vine — not slacking, assessing. This is the halftime pause after long effort: the results are visible now, but not ready to pick. The most valuable move now is taking stock: is this field still worth watering? Double down, hold steady, or move your energy elsewhere? Thinking it through before continuing matters more than grinding head-down.',
      daily: "Set aside half an hour today for a mid-course review: lay out the thing you've invested in most lately, write down what you've gained and how far the goal still is — then decide whether the next step is to keep investing, adjust, or wind it down.",
      love: "This relationship has hit an evaluation point: is it growing in the direction you actually want? Don't rush to a conclusion — look at the trend first. If it's getting better, it's worth continuing to water.",
      career: 'The project or career track is halfway grown — results are surfacing but short of expectations. Rather than fret, examine the method: adjust course, then dig back in, and the harvest will be better.',
      money: 'Investing is about the compounding that time delivers, and now is not harvest time. Reviewing the portfolio periodically is fine; trading in and out constantly just grinds the gains away.',
      advice: "Stop and take stock before pressing on: keep investing where it's worth it, and turn early where it isn't.",
      past: 'Behind you lies quiet cultivation: you kept watering, resisted picking early, and that day-after-day accumulation is exactly the fruit now visible on the vine.',
      present: "The results hang on the vine but aren't ripe, and you're at the midpoint review. This moment calls for taking stock — decide whether to reinvest or change course.",
      other: "They're like the farmer paused at the field's edge: quietly weighing whether this investment is worth continuing — in no hurry to act, and not yet at a conclusion.",
      verdict: 'neutral',
      verdictReason: 'The Seven of Pentacles answers "not yet": the results are growing but not ripe, so what you ask about needs more time under observation.',
    },
    reversed: {
      keywords: ['effort wasted', 'impatience', 'misplaced energy', 'quitting halfway'],
      core: "Reversed, a dull frustration sets in: after all this watering, the fruit is smaller than expected. Maybe the method was wrong, or the field — or you're just demanding results too soon. Tell the two apart: one calls for the courage to cut losses and move your energy where it can bear fruit; the other just needs more patience. Worst of all is skipping the assessment — complaining while mechanically watering on.",
      daily: 'Pick one thing today that has you thinking "why isn\'t this paying off yet" and run the numbers coolly: how much has gone in, what has it returned, and at this rate how long until the goal. Once the math is done, you\'ll know whether to persist or to turn.',
      love: "Impatience with the relationship's pace is building, and pushing harder only stiffens things. Get clear on what you actually want — then judge whether it's something they can't give, or simply not time yet.",
      career: "The feeling that effort and reward don't match wears you down. Check whether your energy is going where nobody can see it — shifting the point of leverage often beats doubling the effort.",
      money: 'For an investment underperforming expectations, the thing to rethink is the allocation — not averaging down. Taking the loss genuinely hurts, but it is cheaper than being stuck for years.',
      advice: 'Run the input-versus-output math honestly: cut the losses that need cutting, and wait calmly where waiting is enough.',
      past: 'It came to this because energy went to the wrong place: the method or direction chosen earlier was off, and the water poured in never returned its worth in fruit.',
      present: "A dull frustration is fermenting. Run the numbers calmly now — sort out whether to cut losses and turn, or whether you're just one stretch of patience short.",
      other: "A quiet frustration is building in them: their investment hasn't returned the response they hoped for, and they're wavering over whether to keep watering at all.",
      verdict: 'leanNo',
      verdictReason: "The reversed Seven of Pentacles shows effort and reward out of balance — staying on the same path risks laboring for nothing, and without adjustment the outlook isn't good.",
    },
  },
]
