// English content: swords-08 … swords-14 (Eight–Ten + Page/Knight/Queen/King, 7 cards).
// name/nameEn/ids MUST mirror the zh files and registry; verdicts MUST match zh.
import type { TarotCard } from '../types'

export const swords0814: TarotCard[] = [
  {
    id: 'swords-08',
    name: '寶劍八',
    nameEn: 'Eight of Swords',
    arcana: 'minor',
    suit: 'swords',
    rank: 8,
    number: 8,
    scene: 'A blindfolded woman bound in cloth stands among eight swords planted in the ground, muddy pools at her feet, a grey castle on a distant cliff behind her under a sullen sky.',
    upright: {
      keywords: ['trapped', 'self-imposed limits', 'helplessness', 'mental prison'],
      core: 'Look closely: the ropes aren\'t actually tied fast, and there\'s still a path beyond the blindfold. The prison the Eight of Swords describes is mostly built of thoughts — sentences like "I can\'t" and "I have no choice" keep you standing in place. Real constraints may exist, but what truly locks you in is giving up before you try. Loosen one belief and a foot can move; the exit is usually much closer than it looks.',
      daily: 'Count how many times you say "there\'s no way" today. Pick one of them and ask honestly: is it truly impossible, or just inconvenient? Find the smallest doable action — sending one inquiry email, say — and puncture that "impossible" with your own hands.',
      love: "Some of the hurt in this relationship may come from things you haven't dared to say. Don't assume rejection in advance — name what you need out loud, and the knots will loosen faster than you expect.",
      career: 'When work rules feel like a straitjacket, first sort out which limits are real and which are just habit. Asking one question — "could we make an exception?" — often opens more room than you thought existed.',
      money: "Financial pressure can make you feel pinned down, but options remain: list every fixed expense and find two you could negotiate or cut. That's where the untying begins.",
      advice: 'Rewrite "I can\'t" as "I haven\'t tried yet" — then try once, today.',
      past: 'This whole thing started with a string of "I can\'t"s: you closed the door on yourself back then, and that self-binding carried into the stuckness you feel now.',
      present: "You feel hemmed in on every side, but the bindings are actually loose. Put your attention on the one step you can still take, not on everything you can't.",
      other: 'They feel unable to move right now — caught in the belief that there are no options. In truth the knots aren\'t tight; they just haven\'t spotted the exit yet.',
      verdict: 'leanNo',
      verdictReason: "The trapped energy is still active and the current setup works against you — but the bindings aren't tight. If you're willing to move, the answer can still be rewritten.",
    },
    reversed: {
      keywords: ['release', 'regained perspective', 'breaking free', 'taking back control'],
      core: "Reversed, the Eight of Swords is the blindfold finally slipping off: you begin to see that you do have choices — and that half of those constraints carried your own signature. The work of this stage is ownership: stop blaming the stuckness on circumstances and take back the reins. A little embarrassment or regret may come with it. Don't camp out in self-blame; spend that energy walking the path you've just seen.",
      daily: "A good day to tackle something long postponed that's actually one push from done. You are freer than you think — pull out the item on your to-do list that makes you feel guiltiest and take its first step right now. The stuck feeling will loosen immediately.",
      love: "Now that you see the relationship for what it really is, you have the strength to decide: if you're repairing it, talk properly; if you're leaving, stop second-guessing. Either road beats circling in place.",
      career: "The deadlock is loosening — the people or processes that blocked you have developed cracks. Put forward the proposal you've been incubating; the timing is riper than you expect.",
      money: "The financial problem you couldn't bear to look at is now in plain view. If debts need consolidating, consolidate; if the allocation needs adjusting, adjust. Delay now costs more than action.",
      advice: "Control is back in your hands — make the decision you've been putting off.",
      past: 'There was a moment of clear sight back then: you realized most of the limits were self-made, and that untying is why you can move forward now.',
      present: "The task now is owning your choice: the blindfold has slipped. Don't turn back to blame circumstances — put your strength into the path you've just seen.",
      other: "They are slowly coming untied: starting to see that they do have choices, carrying a little regret, but their feet are already willing to move outward.",
      verdict: 'leanYes',
      verdictReason: 'The bindings are coming undone and sight is returning; things are loosening in a workable direction. As long as you act, the outlook leans positive.',
    },
  },
  {
    id: 'swords-09',
    name: '寶劍九',
    nameEn: 'Nine of Swords',
    arcana: 'minor',
    suit: 'swords',
    rank: 9,
    number: 9,
    scene: 'Someone sits up in bed in the deep of night, face buried in their hands; nine swords hang across the dark wall behind them, the quilt embroidered with red roses and zodiac signs, the bed frame carved with a relief of figures fighting.',
    upright: {
      keywords: ['anxiety', 'insomnia', 'overworrying', 'waking at 3 a.m.'],
      core: "Not one of the nine swords on that wall has actually fallen — the Nine of Swords doesn't picture disaster itself, only fear magnified in the dark. You keep replaying the worst-case script: manageable by day, chased through your own head by night. Remember: the energy worry burns doesn't make tomorrow any safer. Write the fear down, say it out loud, lay it out in the light — and it shrinks back to its actual size.",
      daily: "Don't make judgments in the middle of the night — the brain at that hour only serves the worst version of everything. Before bed, write your worries down and tell yourself morning will handle them. If insomnia and anxiety keep affecting your life, seek professional help — that is not overreacting.",
      love: 'The betrayal or breakup playing in your head mostly has no evidence behind it. Rather than stewing in guesses all night, ask your partner one concrete question directly.',
      career: "The fear of making a mistake drags your performance down more than any mistake would. Write your worries into a checklist and verify them one by one — you'll find most were already handled long ago.",
      money: "Bill anxiety bites hardest at night. Actually lay the numbers out and do the math once — it's usually less hopeless than imagined. If there really is a gap, asking for help early beats losing sleep alone.",
      advice: "Write the fear down on paper where you can see it — don't let it inflate endlessly inside your head.",
      past: 'This began in a punishing stretch of time: prolonged worry and sleepless nights wore you down, and that exhaustion still colors your judgment today.',
      present: "Right now you're being chased by magnified fears, worst of all at night. Sort out what's fact and what's imagination before drawing any conclusion.",
      other: "They've likely been wrestling with anxiety lately, mind racing at night — steady on the surface while the worst-case script plays on repeat inside. It's draining.",
      verdict: 'leanNo',
      verdictReason: 'Under a blanket of anxiety, most of what you see is distorted — this moment\'s pessimism can\'t be fully trusted. Settle body and mind first, and your odds come back.',
    },
    reversed: {
      keywords: ['nightmare ending', 'release', 'reaching out', 'first light'],
      core: "Reversed, the Nine of Swords is the end of a long night: you grow willing to voice the worries you've hidden away, or finally see the fear's true face is gentler than imagined. For some it runs the other way — anxiety pressed deeper, calm outside, wound tight within. Either way the direction is the same: give it an outlet. Talk to someone you trust; bring in a professional if needed. You needn't carry this alone.",
      daily: "Give that long-bottled worry an exit today — arrange a talk with a friend who truly gets it, or book a counseling session. The moment you say it out loud, you'll realize this weight passed the limit of what one person should carry alone quite a while ago.",
      love: "Once the pent-up unease is spoken, the relationship can finally exhale. Your partner may not be as fragile as you imagine — give each other one honest conversation.",
      career: "The peak of the pressure has passed. Look back and gather the lessons from this stretch — you'll find you held up better than you thought. Showing some vulnerability and asking for help costs you nothing.",
      money: 'The money anxiety is receding. While your head is clear, turn the repayment or savings plan into concrete written steps — replace looping worry with one step after another.',
      advice: 'Open up to someone you trust, or a professional — give the accumulated worry somewhere to go.',
      past: 'There was a dark stretch of gritting it out alone, until you asked for help — or saw the fear for what it really was — and things finally found an exit.',
      present: "You're at the tail end of the nightmare. The task is giving pent-up emotion somewhere to go: talk to someone, find a professional — stop carrying it alone.",
      other: "Their long night is nearly over: the worries they've stockpiled are looking for a way out, and they may be hesitating over whether to open up to someone.",
      verdict: 'leanYes',
      verdictReason: 'The darkest hour is passing and the pressure has found an outlet; things are slowly improving. Walk on with a willingness to ask for help, and the direction tilts optimistic.',
    },
  },
  {
    id: 'swords-10',
    name: '寶劍十',
    nameEn: 'Ten of Swords',
    arcana: 'minor',
    suit: 'swords',
    rank: 10,
    number: 10,
    scene: 'A figure lies face-down at the water\'s edge with ten swords in their back, draped in a red cloak; the sky is a great sweep of black, yet golden dawn breaks along the far horizon over a perfectly still sea.',
    upright: {
      keywords: ['rock bottom', 'ending', 'painful finale', 'nowhere but up'],
      core: 'Ten swords in one back — almost absurdly many. The Ten of Swords admits it: this really is over, and denial won\'t help. But look to the far edge: at the sky\'s blackest point, the horizon is already glowing. Its key message: this is the bottom — what could be lost has been lost, it won\'t get worse, and from the lowest point the only way is up. Give yourself permission to grieve, then turn and face that light.',
      daily: "If bad news arrives, breathe first: this is a full stop, not a chain of explosions. Give yourself some quiet time to absorb it, and do one small kind thing for your body tonight — a proper meal, an early night. Starting from zero tomorrow is, for this card, not an empty phrase.",
      love: 'If a relationship has truly run its course, forced patching only prolongs the pain. Letting go completely is what clears the space for the people and things that actually fit you.',
      career: "A project shutting down or a role disappearing lands hard — but it also clears a battlefield that had long been draining you. Take the lessons of this campaign with you and leave the rest where it fell.",
      money: "The loss has already happened, and the worst move now is scrambling to win it back. Accept it, cut it, protect the capital you have left — and keep everything strictly conservative through the rebuild.",
      advice: 'Acknowledge the ending and save your strength for rebuilding — from the lowest point the only way is up.',
      past: 'It began with a complete curtain-fall: something ended with a crash back then, and that blow cleared the battlefield and defined where you now start from.',
      present: "You're walking the valley floor — what could be lost is gone. This is the lowest point; what's left is uphill. First, allow yourself to grieve properly.",
      other: "They've just been through a total ending and are still at the bottom absorbing the blow. Deep down they most likely know: this time, the curtain has truly fallen.",
      verdict: 'no',
      verdictReason: 'This card declares the matter has reached its end — the road being closed is itself the answer. The good news: the dust has settled, and a new chapter can open.',
    },
    reversed: {
      keywords: ['recovery', 'rebirth', 'clouds lifting', 'refusing to let go'],
      core: "In reverse, the swords are being drawn out of your back one by one: the wounds remain, but recovery has truly begun. The card also warns of another possibility — clutching something that should have ended long ago, reopening the same wound over and over. The test is simple: when the memory surfaces, are you collecting lessons or reliving pain? The first is healing; the second means you must turn the page yourself.",
      daily: 'Recovery doesn\'t need to be dramatic. Pick one symbolic act today to declare the page turned: delete the files you no longer need, clear out one drawer, pack the old things into a box and seal it. Let the body move first, and the heart will slowly follow.',
      love: "The old wound is scabbing over — don't keep peeling it back to check. If the last relationship still casts a shadow, rebuild your sense of safety first; a new beginning can wait a little, and lose nothing.",
      career: 'The climb out of the valley has started, and your past defeats are turning into immunity. When you take on the next assignment, remember: you are not who you were then.',
      money: "The financial rebuild is showing progress — just hold your current discipline. Don't let a little stability tempt you into another big bet; what a recovery fears most is a second injury.",
      advice: "Let healing move at its own pace — don't restage a story that has already ended.",
      past: 'The most painful part already happened and ended. Some swords have been pulled from your back, and that valley time is the ground your recovery stands on.',
      present: "The current task is letting the wound heal at its own speed: don't reopen a story that has ended. Keep your attention on turning the page, not replaying it.",
      other: 'Their wounds are scabbing over: recovery has begun, though they still glance back at old matters now and then. Turning the page takes a little time of their own.',
      verdict: 'leanYes',
      verdictReason: "The worst is behind you and the energy of recovery is building. As long as you don't turn back and repeat the old pattern, things improve — slowly but surely.",
    },
  },
  {
    id: 'swords-11',
    name: '寶劍侍者',
    nameEn: 'Page of Swords',
    arcana: 'minor',
    suit: 'swords',
    rank: 11,
    number: 11,
    scene: 'A young person stands on rolling green high ground gripping an upright sword with both hands, glancing back over one shoulder; wind scatters the clouds overhead, a flock of birds crosses the distance, and the trees lean with the gusts.',
    upright: {
      keywords: ['curiosity', 'alertness', 'thirst for knowledge', 'observation'],
      core: "The Page grips his sword and glances back while the wind races the clouds — he is a quick, alert current of mental energy. He might be the young person near you who asks the most questions and hears the news first, or your own itch to learn stirring awake. This is the moment to gather information, learn something new, ask the sharp question. Reading the whole board before moving is exactly this card's strength.",
      daily: "Let curiosity lead today: sign up for the course you've been eyeing, trace a story back to its source, ask an expert one specific question. Information is your weapon right now — one more question, one layer deeper, and you're often a step ahead of everyone else.",
      love: "The testing-the-waters stage is exactly where you should be: talk more, ask more, understand before you invest. If you're partnered, open a topic neither of you has touched and let the conversation spark again.",
      career: "A chance to learn a new field has appeared, and a thin résumé is no obstacle. Your sharp eye will catch the details others miss — start by being a very good student.",
      money: "A fine time to study new financial ideas — but keep it to homework and small test amounts. Verify tips from multiple sources; never act on a single voice.",
      advice: 'Ask more, check more, listen more — gather the full picture before deciding your next move.',
      past: 'This started with a spark of curiosity: you, or someone quick-witted, asked one more question, dug one layer deeper — and that opened the situation you have now.',
      present: "You are in the intelligence-gathering phase: ask, listen, and read the whole board before making a move. The sharp-eyed voices around you deserve real attention.",
      other: 'They are in watch-and-inquire mode: curiosity running high, questions plentiful, wanting to see the situation clearly first — not ready to show their hand yet.',
      verdict: 'leanYes',
      verdictReason: 'Curiosity and alertness are a favorable opening — this is worth exploring. But it is still the scouting phase; the results must be earned by what you do next.',
    },
    reversed: {
      keywords: ['gossip', 'careless words', 'all talk', 'prying'],
      core: "Reversed, the Page swings the sword too loosely: words come fast, fact-checking comes slow, and the cleverness all goes into gossip and word-catching. When this energy shows up around you, it warns of rumors and words taken out of context. When it shows up in you, check whether the plan's been talked to death without one step landing. Sheathe some of that verbal sharpness and use the blade on the actual problem.",
      daily: "Before forwarding any news today, check the source once; treat secondhand opinions as reference only, not something to pass along. And take stock: of all the plans you've been talking about, which one could get ten minutes of actual work today? Start with that one.",
      love: "Watch out for words outrunning thought — one quick jab can cut deeper than you imagine. And don't feed your insecurity by prying into their privacy; direct conversation is the only thing that works.",
      career: 'Treat office rumors as background noise and don\'t become the relay. Catch up on the things you\'ve promised, fast — once the "all talk, no delivery" impression sets, it is very hard to shake.',
      money: 'Secondhand tips and insider whispers are the landmines of this stretch. Treat anything not in black and white with suspicion — the cost of verifying is always lower than the cost of being fooled.',
      advice: 'Verify before you speak; produce one small piece of real work before you talk plans.',
      past: 'In hindsight, the starting point hid a failure to verify: a rumor, a careless remark, or a plan that stayed all talk — and it seeded the confusion you have now.',
      present: 'You are in a moment of murky information. The task is to sheathe the verbal edge: verify first, produce something real first — then talk about the next step.',
      other: 'Their words outrun their actions right now: quick to hear news, quick to repeat it, verification lagging behind — plans mostly still living in their mouth.',
      verdict: 'leanNo',
      verdictReason: 'Careless words and distorted information have muddied the water — pushing forward now risks stepping into thin air. Get the facts verified first, then talk about results.',
    },
  },
  {
    id: 'swords-12',
    name: '寶劍騎士',
    nameEn: 'Knight of Swords',
    arcana: 'minor',
    suit: 'swords',
    rank: 12,
    number: 12,
    scene: 'A knight charges at full gallop on a grey-white horse, body leaning forward, sword raised high in his right hand; the wind tears the clouds into jagged streaks, roadside trees bend, and the horse\'s reins and trappings stream behind them.',
    upright: {
      keywords: ['drive', 'decisiveness', 'straight talk', 'swift strike'],
      core: 'The hooves barely touch the ground — the Knight of Swords is the fastest-moving energy in the whole deck. He may be that person whose drive is startling and whose speech is direct to the point of sharpness, or the "go now" surge in your own chest. Anything with a clear target and a closing window belongs to this energy. At full speed, remember to lift your head now and then and confirm the course hasn\'t drifted.',
      daily: "That long-stalled thing? Charge through it in one go today: if it needs a negotiation, book the meeting; if it needs a hard conversation, say the words plainly. Your momentum is peaking and speed is your edge. The only prep needed: five minutes before launch to confirm you've got the right target.",
      love: "A direct confession has better odds than usual right now — hesitating is what loses points. But amid the heat, leave the other person room to respond; courtship is not a cavalry charge.",
      career: 'The project worth fighting for, the proposal worth making — move on it this week. Execution is your most persuasive argument. Speaking bluntly is fine; just let people finish their sentences first.',
      money: "When you've sized up an opportunity, enter decisively — but speed is not the same as a heavy bet. Set your stop-loss before you charge, so the decisiveness rests on discipline, not adrenaline.",
      advice: 'Lock onto the target and sprint — right now, hesitation costs more than mistakes do.',
      past: 'It all began with a full-speed strike: you, or someone decisive, charged forward in one burst back then and pushed the situation to where it stands now.',
      present: 'This is the moment for a swift, decisive strike, and momentum is on your side. The only thing to guard is direction — confirm the target before you launch.',
      other: 'They are charging at their goal with everything they have: thinking direct, moving fast, nearly all of their attention fixed on the one thing they must get done.',
      verdict: 'leanYes',
      verdictReason: 'Drive and momentum are both on your side — a fast attack is favored. Success hinges on aiming true, so line up the target before you charge.',
    },
    reversed: {
      keywords: ['recklessness', 'losing control', 'combativeness', 'strong start, no finish'],
      core: "Reversed, the Knight either can't hit the brakes or mounted the wrong horse entirely: starting fights before the direction is clear, or realizing the words wounded only after they've flown. In someone else, it's a warning: don't be swept into rushed decisions by their momentum. In yourself, ask how many of these battles even need fighting. Sheathe the sword and think three seconds — it regularly saves a disaster.",
      daily: "Every 'strike back now' impulse gets shelved for ten minutes today: the message you were about to fire off unthinking, the retort already on your tongue. Once they've cooled, you'll mostly be glad you never sent them.",
      love: 'Racing to win an argument is the worst trade available — you win the point and lose the relationship. Handle the feelings before the facts, and don\'t let one quick tongue become a long crack.',
      career: 'Charging blindly ahead runs you into invisible walls. Map out who the stakeholders are and where the process actually sticks before you launch — and give your half-abandoned projects a proper ending too.',
      money: 'Impulse trades — chasing highs, dumping lows — are the cardinal sin of this stretch. Every "buy now or miss out forever" pitch deserves one extra day of thinking in the opposite direction.',
      advice: 'Count three seconds before you strike, and confirm this battle truly must be fought before you enter it.',
      past: 'The haste back then left recoil: a fight started without thinking, a sentence that shot out too fast — and the aftershocks have carried all the way to now.',
      present: "The skill to practice right now is braking: don't be swept along by your own momentum or anyone else's. Shelve it for ten minutes, then decide whether to act.",
      other: "They can't quite hit the brakes right now: words fly out too fast, decisions come too quick, and even they may not have thought the direction through.",
      verdict: 'leanNo',
      verdictReason: 'Runaway speed flips the cart — forcing ahead now yields half the result for twice the effort. Correct the course first, and your odds come back.',
    },
  },
  {
    id: 'swords-13',
    name: '寶劍王后',
    nameEn: 'Queen of Swords',
    arcana: 'minor',
    suit: 'swords',
    rank: 13,
    number: 13,
    scene: 'A crowned woman sits in profile on a stone throne, sword upright in her right hand, left hand extended forward; the throne is carved with butterflies and a cherub\'s head, low clouds gather beneath the seat, a lone bird flying high above.',
    upright: {
      keywords: ['clarity', 'reason', 'straight talk', 'independence'],
      core: "Her sword points straight up while the other hand extends forward — see clearly first, then decide what gets through. She has weathered storms and can no longer be swayed by tears or smooth talk: perhaps a mentor near you who cuts straight to the bone, or the version of yourself you need to summon right now. Feelings to the side, facts in the middle — her kindness lives not in her tone, but in her honesty.",
      daily: "A good day for anything that needs a cool head: negotiating terms, giving feedback, making trade-offs. Filter out the emotion and keep the facts before you speak — you'll find directness is actually the most efficient way to communicate. Being honest with people doesn't require barbs in your voice.",
      love: "Clear boundaries are not coldness. Spell out the standards you actually care about, and you'll filter out those who'd waste your time. If you're partnered, communicate with facts — not the silent treatment.",
      career: "Judgment and evaluation work is your home ground right now, and people who dare to tell the truth are especially valuable. Attach your reasoning to every opinion, and sharpness reads as professionalism.",
      money: "Time to let the numbers do the talking: audit each expense and investment against its actual return. The waste driven by sentiment gets cut — no more excuses on its behalf.",
      advice: 'Filter out the emotion, keep the facts, then state your judgment honestly.',
      past: 'A past storm scoured you clear-eyed: back then you, or someone plain-spoken, made the hard call on the facts — and that is how today\'s situation came to be.',
      present: "What's needed now is the Queen's clarity: filter out the emotion, set the facts in the middle, state your judgment honestly, and draw the boundaries clean.",
      other: "They are wide awake right now: seeing things through facts, boundaries sharp, few words but every one of them meant. Tears and smooth talk won't get far with them.",
      verdict: 'neutral',
      verdictReason: 'This card gives no emotional answers — it sends you back to the facts: if the evidence supports it, yes; if the evidence doesn\'t, no.',
    },
    reversed: {
      keywords: ['bitterness', 'coldness', 'old grievances', 'bias'],
      core: 'Reversed, the sword turns toward people: criticism grows barbs, reason becomes armor, and old wounds teach a person to wall off every approach with coldness. This may be someone near you growing harder and harder to reach — or it may be you, dressing emotional attacks as "I\'m just being honest." The sword should cut open problems, not relationships. Before drawing it, ask yourself what you\'re actually angry about.',
      daily: 'Every "I\'m just telling it like it is" gets a self-check today: is this to solve the problem, or to vent the feeling? Try trading criticism for a request — turn "you never listen" into "I need you to hear me out to the end."',
      love: "Old wounds have made defense your daily wear — spikes out the moment anyone comes close. Try saying one true thing inside a safe space. Softness will not make you lose.",
      career: 'Too much edge and colleagues stop telling you things — you become an information island. For now, ask more and judge less, and hold your conclusions one beat longer.',
      money: 'Purchases and investment decisions made out of spite or revenge are almost always regretted. When your blood is up, freeze every large decision until it cools.',
      advice: 'Put the sword down and hear the whole sentence out — save the sharpness for problems, never for people.',
      past: 'Trace it to the root and you find an old wound never resolved: it barbed the words and locked the heart tighter, and that hardness set into today\'s standoff.',
      present: "The task at hand is directing the blade: swords cut problems, not people. Before you speak, get clear on what you're actually angry about.",
      other: 'They wear their composure like armor: words barbed, hard to get near — and beneath that hardness, most likely, an old wound that never healed.',
      verdict: 'leanNo',
      verdictReason: 'Bias and old grievances are interfering with judgment — conclusions drawn now will mostly miss the mark. Untangle the emotion first, then come back to this question.',
    },
  },
  {
    id: 'swords-14',
    name: '寶劍國王',
    nameEn: 'King of Swords',
    arcana: 'minor',
    suit: 'swords',
    rank: 14,
    number: 14,
    scene: 'A king sits facing forward on a stone throne, sword upright and slightly tilted in his right hand, robed in blue; butterflies are carved into the throne\'s back, a row of trees stands behind him, and two birds cross the sky.',
    upright: {
      keywords: ['authority', 'fairness', 'reason', 'decisive judgment'],
      core: 'The King holds his sword dead straight, eyes fixed forward — he is the highest judge of the suit of mind. This energy may come from an elder or a boss who lives by rules and logic, or it may be the role now being asked of you: set the standards, make the ruling, carry the responsibility of saying "no." His reminder: fairness outlasts flattery, and a clear rule is itself a form of kindness.',
      daily: "Meet hard problems with structure today: write the problem down, list the options, criteria, and consequences, and rule on it like a judge. If someone needs a hard word or a rule laid down, do it now while your head is clear — say it once, completely, and don't let it fester into an open case.",
      love: "Running a relationship on reason isn't unromantic: laying out and aligning your expectations for the future beats a hundred rounds of mind-reading. If you're single, a mature, steady type may catch your eye.",
      career: 'Your professional judgment carries weight right now — the moment to make the final call, build the system, chair the negotiation. When responsibility lands on your shoulders, pick it up without flinching.',
      money: 'A fine time to put your finances under a system: set the budget, fix the rules, write down your entry and exit discipline — then follow it strictly. Big decisions run on data, not on feel.',
      advice: 'Set clear standards, then enforce them fairly — on yourself included.',
      past: 'This situation rests on a fair ruling: in the past you, or someone who lived by the rules, set the standard and made the call — and order flowed from there.',
      present: "It's your turn in the judge's seat: set the standards, make the decision, carry the weight of saying \"no.\" Fairness travels further than pleasing people.",
      other: 'They are standing in the arbiter\'s position right now: ruled by logic and principle, crisp in their yeses and nos, with sentiment set aside for the moment.',
      verdict: 'yes',
      verdictReason: 'Reason and order hold the high ground. Act on facts and rules, and this matter can be ruled in your favor.',
    },
    reversed: {
      keywords: ['tyranny', 'coldness', 'abuse of authority', 'inflexibility'],
      core: "Reversed, the King turns judgment into control: the rules bind everyone but himself, logic serves only his side, and cleverness presses people down instead of winning them over. With someone like this, protect yourself with everything in writing — don't wait for him to turn reasonable. If the rigidity is yours, the warning sign is people around you going quiet. That isn't agreement; it's giving up on being heard.",
      daily: "Before issuing an order or handing down a conclusion today, first ask the other person one question you genuinely want answered. The fastest way authority drains away is people deciding that speaking up is pointless. Leave a door open for others to talk, and your own judgment gets sharper for it.",
      love: 'Winning every argument while the relationship goes cold is the most losing victory there is. Today, practice saying it once: "you have a point."',
      career: 'Facing a superior who holds everyone to rules but himself? Keep records of every exchange and get every promise in writing. If you lead people yourself, watch for the "because I said so" reflex.',
      money: "Beware pitches wrapped in authority: titles, licenses, and expert cadence are not guarantees. Read the contract clause by clause — if the terms aren't equal, don't sign.",
      advice: 'Trade "my word is final" for "let me hear you out" — that is the only footing on which authority stands.',
      past: 'This traces back to a stretch of being steamrolled: an authority whose word was law shut the communication down, and that shadow still hangs over the present.',
      present: 'You are facing a rigid power dynamic — or becoming the tyrant yourself. The most urgent thing right now is keeping one door open for people to speak.',
      other: "They're running very forceful right now: holding all the reasons, rarely letting anyone finish a sentence — the door to communication is all but closed for now.",
      verdict: 'no',
      verdictReason: "Abuse of power and rigidity have sealed the road — advancing on unequal terms only puts you at their mercy. Not this round; step back and reposition first.",
    },
  },
]
