// English content for swords-01-07 (produced by content agents).
import type { TarotCard } from '../types'

export const swords0107: TarotCard[] = [
  {
    id: 'swords-01',
    name: '寶劍一',
    nameEn: 'Ace of Swords',
    arcana: 'minor',
    suit: 'swords',
    rank: 1,
    number: 1,
    scene: 'A hand reaches out of a cloud gripping an upright sword, its tip crowned with gold, palm and olive branches hanging from the crown, golden sparks drifting around the blade above a barren gray-blue mountain range.',
    upright: {
      keywords: ['breakthrough', 'truth', 'clarity', 'decisiveness'],
      core: "A sword breaks through the clouds and points straight at the sky — the fog splits open, and the heart of the matter is suddenly plain. This card marks a mental breakthrough: a new idea, a truth finally spoken, an overdue decision. Right now your mind is razor-sharp; you can see the knot that everyone else keeps circling. Spend that clarity where it counts — say it straight, do it straight, go straight for the point.",
      daily: "Your head is unusually clear today — a good day for anything that needs judgment: the fine print before you sign, the conversation where cards go on the table, the trade-off you've been stuck on. Pick one thing you've been fudging and state your position in a single sentence.",
      love: "It's time to say the thing out loud. If you're single, name your interest plainly instead of dropping hints; if you're together, lay the buried questions on the table — clarity draws you closer, not apart.",
      career: "Negotiations, pitches and decisions all run in your favor — your arguments hold up. If you have an idea for something new, raise it now; the sharper the angle, the stronger it lands.",
      money: "Money matters reward a clean decision: cancel what should be canceled, cut the loss that should be cut. Read the numbers clearly, then act — vague half-measures are where money keeps leaking.",
      advice: 'Say the one sentence that matters most — clear beats tactful for moving things forward.',
      past: 'Not long ago, a moment of seeing clearly — or saying it out loud — split the fog. That decisive truth-telling set the terms for where things stand now.',
      present: "Your mind is at its sharpest and the truth is lying in plain sight. Aim your attention at the one cut that matters; speak plainly, act directly, don't scatter.",
      other: 'Their head is clear and their position is set. They are carrying a conclusion they want to say out loud, and they would rather be direct than keep circling.',
      verdict: 'yes',
      verdictReason: 'The Ace of Swords is clarity and decision cutting through fog — its energy is clean and direct, and to a yes/no question it gives a crisp yes.',
    },
    reversed: {
      keywords: ['mental fog', 'miscommunication', 'misjudgment', 'overthinking'],
      core: "Reversed, the blade turns the wrong way: too many thoughts and no thread to pull, or words so sharp they wound someone and blur the point at once. You may also be gripping a 'truth' that is really only one side of the story. Don't rush to conclude or to speak. Write the tangled threads down one by one, and sort which are facts and which are your own inferences — sharpen the blade before you use it.",
      daily: "Words misfire easily today. Draft important messages first, let them sit ten minutes, then send. If you catch yourself circling the same thought for the third time without moving, stand up, take a walk, and think again somewhere else.",
      love: "One heated remark can do damage far out of proportion — when an argument flares, leave the room first. And beware of over-analyzing their messages: the storyline in your head is mostly not the truth.",
      career: "High risk of communication going sideways: write emails clearly before sending, get meeting conclusions confirmed in writing. If the direction is murky, don't force a call — gather more information first.",
      money: "Watch for smooth talk and numbers that look too pretty. Read every contract clause until you understand it, and don't rearrange your investments on a passing impulse.",
      advice: 'Sort your thoughts before you speak — separate fact from guess, and talk half a beat slower.',
      past: "Looking back, the starting point hid a misjudgment: words said too fast or a conclusion drawn too soon, and that crooked first cut has carried through to today.",
      present: 'Too many threads in your head, and the more you think the more it tangles. Separate facts from guesses first and slow your words half a beat — judgment will steady.',
      other: 'Their thoughts are tangled; what they say may come out rushed or garbled. The sharpness is probably not the real intent — they just haven\'t sorted it out yet.',
      verdict: 'leanNo',
      verdictReason: 'Reversed, it shows knotted thinking and muddy information — judgment is unreliable right now, and forcing a decision invites a miss. Pause first.',
    },
  },
  {
    id: 'swords-02',
    name: '寶劍二',
    nameEn: 'Two of Swords',
    arcana: 'minor',
    suit: 'swords',
    rank: 2,
    number: 2,
    scene: 'A blindfolded woman in white sits on a stone bench at night, arms crossed over her chest with a long sword in each hand, a rocky sea behind her and a crescent moon hanging in the upper right.',
    upright: {
      keywords: ['stalemate', 'dilemma', 'holding off', 'avoidance'],
      core: "The blindfolded woman holds two crossed swords to her chest; the sea is right behind her, but she cannot see it. You're stuck between two options — not from laziness, but from fear of choosing wrong. The standstill is self-protection, but the blindfold won't fall off by itself. The card isn't rushing you; it only says the facts won't multiply on their own — sooner or later you must take the blindfold off yourself.",
      daily: "If a two-way choice lands on you today, don't force an instant answer. Write down the three worst outcomes for each option — you'll find one side isn't nearly as scary as it felt. Then give yourself a firm deadline to decide.",
      love: "You may be wavering between two people, or between staying and leaving. Dodging the conversation only stretches the stalemate — first get clear on what you're actually afraid of losing.",
      career: "Two opportunities, or two camps of opinion, are locked in a standoff. Holding still for now is fine — but use the time to fill in the missing facts, and don't let watching turn into stalling.",
      money: "It's fine to shelve a major financial decision — you don't have enough information yet. Rather than forcing a pick, get a trustworthy third-party opinion first.",
      advice: 'Set a decision deadline, gather information hard until then — and when it arrives, choose.',
      past: 'Faced with a dilemma, you chose to hold still. Those blindfolded days of watching and waiting are why the matter has hung unresolved all the way to now.',
      present: "The task isn't to force a choice but to face it: the blindfold comes off by your own hand. Fill in the missing information, then give the decision a deadline.",
      other: "They're wedged between two options and holding still — not cold, just unable to see clearly yet. The silence is their way of protecting themselves for now.",
      verdict: 'neutral',
      verdictReason: 'The Two of Swords is a stalemate still hanging — the scale has not tipped, and the answer depends on when you choose to take the blindfold off and face it.',
    },
    reversed: {
      keywords: ['stalemate breaking', 'forced choice', 'information overload', 'torn both ways'],
      core: "Reversed, the blindfold is coming loose — maybe the stalling has hit its limit and events are forcing your hand, or information is flooding in and muddying things further. The longer you hug those swords, the more your arms ache; you already know what more delay will cost. Rather than let outside forces decide for you, pick a direction you can live with before you're pushed — the road you chose is easier to walk.",
      daily: "Someone may demand an answer today, or something long-shelved may suddenly come due. Instead of scrambling, take ten minutes in the morning to fix your bottom line: what you can concede and what you can't. Then when you have to declare yourself, you won't wobble.",
      love: "The long-avoided topic may get pulled open by the other person — there's no dodging it now. Instead of getting defensive, say your hesitation out loud; laying it open is the turning point.",
      career: "The room for fence-sitting is disappearing — stay silent much longer and you may lose both sides. Plant your feet on the side you know better, and be ready to explain why.",
      money: "The bill you've been ignoring, the option about to expire — they're closing in, and the cost grows the longer they sit. Today, put the most urgent one on the table and deal with it.",
      advice: "Choose before you're forced to — a road you picked yourself is one you can walk without regret.",
      past: 'The matter was stalled past its limit. The choice you kept sidestepping piled up into pressure, and that is how today\'s forced hand came about.',
      present: "The room to sit on the fence is closing, and you're being pushed to pick a side. While you still hold the initiative, get your bottom line clear first.",
      other: "They've stalled to the edge of what they can bear, pushed by events into facing it — deep down they already sense what further delay will cost.",
      verdict: 'leanNo',
      verdictReason: 'Reversed shows the stalemate stretched to breaking point — waiting passively ends badly here. Unless you act at once and by choice, this leans against you.',
    },
  },
  {
    id: 'swords-03',
    name: '寶劍三',
    nameEn: 'Three of Swords',
    arcana: 'minor',
    suit: 'swords',
    rank: 3,
    number: 3,
    scene: 'Heavy rain falls from a gray sky under low storm clouds; a bright red heart hangs in midair, pierced straight through by three long swords — no figures anywhere, only heart, swords, rain and cloud.',
    upright: {
      keywords: ['heartbreak', 'painful truth', 'grief', 'loss'],
      core: "Three swords through one heart, rain coming down — the pain is real, and you don't have to pretend otherwise. This card often arrives with a wounding remark, a cruel truth, or a crack in a relationship. But swords stand for seeing clearly, and the same thrust that pierces also ends the suspense. The rain will stop; the heart will heal. Your only task is to let yourself hurt properly, not to rush into being strong.",
      daily: "If a harsh word or a disappointing piece of news finds you today, don't strike back and don't grit through it. Find a safe outlet — write it down, tell someone you trust, cry it out. Grief that's allowed to move doesn't harden into an internal wound.",
      love: "A truth that hurts may surface: a fight, a disappointment, or a crack you can no longer deny. Once the pain has passed through, you'll see the real state of this relationship far more clearly.",
      career: "You may face cutting criticism, exclusion, or a partnership falling apart. Separate the feelings from the facts first — keep whatever in the criticism is usable, and let the rest go.",
      money: "There may be a loss that genuinely stings. Acknowledge it, take the lesson — and don't let the urge to win it back push you into something even riskier.",
      advice: 'Let yourself hurt — but set a stop-loss on the grieving, and carry away what you saw clearly.',
      past: "None of this can be traced without that piercing blow: a wounding remark or a crack that opened, and it is the source of how things feel now.",
      present: "You're walking the most painful stretch — don't rush into being strong. Let the feelings move, keep the facts you've seen clearly, and trust that the rain does stop.",
      other: "They're carrying a wound of their own right now — cut by some remark or some truth — and they're in a stage that needs quiet to digest the grief.",
      verdict: 'no',
      verdictReason: "The Three of Swords points to loss and rupture — things mostly won't go as hoped. What it offers isn't a good outcome but the chance to see clearly and begin again.",
    },
    reversed: {
      keywords: ['wound closing', 'letting go', 'clouds lifting', 'lingering ache'],
      core: "Reversed, the swords are being drawn out one by one — the worst of the pain has passed, and the wound is starting to close. You may notice that thinking of it no longer tightens your chest the way it did. But watch for the other pattern: pressing the pain down and calling it healed, so the old wound aches in the small hours. Recovery isn't forgetting — it's being able to say what happened, calmly.",
      daily: "Today suits an act of closure: box up the things you don't want to keep seeing, delete the messages you keep rereading, or write a letter you never send. Give the past a concrete place to rest, and you can walk forward.",
      love: "The old wound is leaving the stage, and you're finding room to trust again. If you catch yourself guarding against this person with the last relationship's script, remind yourself: they are not that person.",
      career: "The sting of the earlier setback is fading — you can step back in. List what the last fall taught you; those lessons are your protective gear this time.",
      money: "Don't let the shadow of an old loss steer today's judgment — over-caution and revenge-sized bets are both ghosts of the same wound. Come back to the plan itself.",
      advice: 'Give the wound a proper closing ritual — then walk on carrying the lesson, not the grudge.',
      past: "The deepest sword has already been drawn out. That heartbreak hurt as much as it hurt — and it also cut the suspense loose for you.",
      present: "The wound is in its closing stage, and the task now is a proper ending: lay the past to rest, take the lesson with you, but don't pretend it never hurt.",
      other: "Their worst pain is behind them and the wound is closing. It still aches now and then, but little by little there's room in them again.",
      verdict: 'leanYes',
      verdictReason: 'Reversed means the worst has passed and recovery is underway — things are moving in a slowly improving direction; it just needs time to finish closing.',
    },
  },
  {
    id: 'swords-04',
    name: '寶劍四',
    nameEn: 'Four of Swords',
    arcana: 'minor',
    suit: 'swords',
    rank: 4,
    number: 4,
    scene: "In a corner of a church, a knight's effigy lies on a stone tomb with hands pressed in prayer; three swords hang horizontally on the wall, a fourth lies flat along the tomb beside him, and a stained-glass window glows in the upper left.",
    upright: {
      keywords: ['rest', 'recuperation', 'pause', 'recharging'],
      core: "The knight has lain down and the swords hang on the wall — this is not surrender, it's repair. You've been campaigning too long without a break, and body and mind are signaling for downtime. The prescription is simple: retreat somewhere quiet, sleep, let your mind empty, decide nothing for now. Pausing won't put you behind; grinding on will. Rest enough and look again — the problem is usually half its old size.",
      daily: "Cut today's schedule to the bone — postpone what can be postponed, hand off what can be handed off. Keep twenty minutes at midday to close your eyes, and go to bed half an hour early. If your body has been sending signals, don't sit on them — book the checkup early for peace of mind.",
      love: "The relationship needs breathing room, and temporary quiet is not a change of heart. Rather than stacking up dates, recharge separately and come back to each other with something full to give.",
      career: "This is not the sprint window. Gather up what's in hand and avoid opening new fronts. Taking leave or slowing down is nothing to be ashamed of — burnout collects a much steeper bill.",
      money: "Play defense with your positions — staying out of the market is a move too. This stretch is for taking stock of what you hold, not for hunting new targets.",
      advice: 'Schedule a real stretch of rest on purpose — sleep first, and push every decision to later.',
      past: "You campaigned too long without pause on the last stretch. The fatigue that piled up unaddressed is exactly why a stop is now non-negotiable.",
      present: "What matters most right now isn't attack but repair: sleep well, switch off, put decisions on hold, and rebuild your strength before you take the field again.",
      other: "They're in a state that needs quiet recovery. The silence is recharging, not distancing — right now they simply don't have much energy to respond to the world.",
      verdict: 'neutral',
      verdictReason: "This card doesn't call good or bad fortune — it says the timing isn't ripe and rest comes first. The answer depends on your next step once your strength is back.",
    },
    reversed: {
      keywords: ['burnout', 'pushing through', 'stalled too long', 'forced restart'],
      core: "Reversed, the balance tips one of two ways: you're clearly exhausted but refuse to lie down, running on willpower until your body slams the brakes — or the rest has stretched into stagnation, and you've lain down so long you can't get up. To tell which, ask yourself: am I still recharging, or am I avoiding going back in? If the former, rest seriously. If the latter, set a comeback date — and when it arrives, move.",
      daily: "Check your fuel gauge today. If small things irritate you and you wake up still tired, that's the overload alarm — pushing on only breeds mistakes, and if it's bad, see a doctor early. If instead you've rested a long while but can't start, pick the smallest possible task and begin rehab there.",
      love: "One of you may be too drained to tend the relationship while the other feels shut out. Saying 'I need rest, not distance' protects trust far better than simply going quiet.",
      career: "Burnout is already showing in your output, and grinding on risks a serious mistake. Honestly reassess the load and talk to your manager if needed — that isn't weakness, it's stopping the bleeding.",
      money: "Financial decisions made tired go wrong easily — shelve anything major. If long stagnation has stalled your income, restart with small, steady inflows first.",
      advice: "If you're tired, admit it and truly rest; if you've rested enough, set a date and set out.",
      past: "When it was time to rest you pushed through instead — or the rest ran far too long. That lost balance has dragged your condition all the way to now.",
      present: "You're wedged between grinding on and going stale. Look honestly at the fuel gauge: if you need rest, really rest; if you're rested, pick the date and move.",
      other: "They may be running on empty and still pushing, or so long at rest they can't spin up. Overdrawn like this, slow replies aren't aimed at anyone.",
      verdict: 'leanNo',
      verdictReason: "Reversed shows energy overdrawn or stagnation overstayed — your current state can't carry the outcome you want. Restore yourself first; that's where the odds are.",
    },
  },
  {
    id: 'swords-05',
    name: '寶劍五',
    nameEn: 'Five of Swords',
    arcana: 'minor',
    suit: 'swords',
    rank: 5,
    number: 5,
    scene: 'By a windswept sea under churning clouds, a smug man in the foreground glances back, two swords in his arms and a third in his hand; two more lie on the ground, and in the distance two figures walk away toward the water, heads bowed.',
    upright: {
      keywords: ['hollow victory', 'conflict', 'hidden agendas', 'costly win'],
      core: "Someone won this fight and picked up the swords — but the losers trudge away and storm clouds boil at the horizon. How much is a victory like that worth? The Five of Swords doesn't ask who won; it asks what it cost. Maybe you came out on top and lost the room. Maybe you're the one who got run over. Either way, the urgent move is to cut your losses: on some battlefields, the one who leaves early is the real winner.",
      daily: "Sharp-edged standoffs come easily today. Before engaging, ask one question: if I win this round, what do I lose? If the answer is trust or a relationship, set down the urge to prove you're right — walking away is nothing to be ashamed of.",
      love: "An argument can slide into mutual wounding, and the line that wins the fight cuts the deepest. Call a ceasefire first, and get clear on whether what you want is to be right — or to be close again.",
      career: "A power struggle or a fight over credit is surfacing. Go head-to-head and even a win leaves a lasting grudge. Guard your own bottom line; beyond that, don't linger on the battlefield.",
      money: "Watch for zero-sum deals: a bargain that only works because the other side loses tends to come with aftershocks. Be alert to sharp arithmetic in partnerships and split bills too.",
      advice: 'Tally the full cost before you decide to fight — and if you can exit, exit first.',
      past: "That earlier clash left a crack. Whoever had the upper hand at the time, the trust that got spent is still on today's ledger.",
      present: "You're standing in a standoff that doesn't pay. Count the full cost before you take the bait — knowing when to leave the field is a way of winning too.",
      other: "They may still be submerged in the aftermath of that clash — keeping score, guard up. Right now they're not really in a state for a good-faith conversation.",
      verdict: 'leanNo',
      verdictReason: "In the Five of Swords even winning is a hollow win — the cost of the fight outweighs the spoils, so a truly good outcome is unlikely. It leans against you.",
    },
    reversed: {
      keywords: ['laying down arms', 'opening to truce', 'old grudge easing', 'ceasefire'],
      core: "Reversed, the sword can finally go back in its sheath — the conflict is loosening — maybe you're done burning energy on it, maybe the other side offered a way down first. But reconciliation doesn't finish itself: a grudge merely buried sprouts again elsewhere. While the ceasefire wind is blowing, talk out the knot that started it — or at least close the book privately. Don't let one old fight define everything after.",
      daily: "Today is right for tending a frozen relationship: a message saying 'I came in too hot last time,' a cup of coffee handed over — small moves loosen a standoff. If they're not ready yet, don't force it; setting down your own hostility is already enough.",
      love: "The cold war is showing signs of thaw, and whoever softens first is not the loser. Swap 'who was right' for 'what do we do next,' and the conversation becomes possible.",
      career: "A knot with a colleague or client has a real chance of untying — a first move of goodwill will be repaid. But after the verbal peace, still put the terms of cooperation in writing.",
      money: "A tangled money dispute is opening room to settle. Each side giving a step and ending it early usually beats grinding on. Get the agreed terms down on paper.",
      advice: 'Offer the way down, or take the one offered — let this war of attrition end today.',
      past: "That war of attrition had already begun to loosen — someone offered a way down earlier, or simply stopped engaging, and that left the opening you have now.",
      present: "The ceasefire wind is blowing right now. Move your energy from who was right to what happens next, and talk out the old knot while the opening lasts.",
      other: "Their hostility is loosening — they may be waiting for a way down. The wish to stop burning energy on this is plainer than what shows on the surface.",
      verdict: 'leanYes',
      verdictReason: 'Reversed marks conflict easing and a door open to truce — as long as one side is willing to lay the sword down first, things move toward calm.',
    },
  },
  {
    id: 'swords-06',
    name: '寶劍六',
    nameEn: 'Six of Swords',
    arcana: 'minor',
    suit: 'swords',
    rank: 6,
    number: 6,
    scene: 'A ferryman stands at the stern poling a small boat that carries a cloaked woman and a child nestled beside her; six swords stand in the bow, the water ripples beside the boat while ahead it lies calm, and low trees line the far shore.',
    upright: {
      keywords: ['transition', 'leaving the storm', 'growing calm', 'passage'],
      core: "The boat is pulling away from rough water toward a calm shore, six swords still in the bow — the sorrows come along, but the storm stays behind. This card is a necessary passage: a move, a job change, the end of a draining relationship, or simply the heart's quiet withdrawal. The crossing is hushed, even a little sad — but the direction is right. No need to hurry the arrival; just keep moving toward the calmer side.",
      daily: "Today suits the work of leaving and handing over: moving things, relocating, wrapping up a project that has run its course. If some reluctance lingers, let it be there — but don't stop rowing. You only need to get through the stretch just off the shore.",
      love: "The relationship is sailing out of turbulence toward steadier water, old quarrels receding behind you. If a relationship just ended, this quiet crossing is necessary — don't rush to reach a new shore.",
      career: "A good window for changing tracks or changing environments. Leaving a position that drains you isn't running away, it's cutting a loss. Hand over cleanly, and the water ahead runs smoother.",
      money: "Finances are easing from strained toward stable — a good time to shift risky positions gradually into safer ground. The improvement is incremental; don't expect one clean leap.",
      advice: "Keep moving toward the calm — don't turn back to tangle with the storm.",
      past: "You have already left that stretch of rough water. The earlier decision to pull out of a situation that drained you is why you can breathe now.",
      present: "The boat is mid-crossing — the direction is right, the shore just isn't here yet. Keep a steady hand on the pole and don't look back to tangle with the storm.",
      other: "They're in a quiet transition — the heart has withdrawn from the old turmoil and is edging toward steadier water, though it hasn't fully come ashore.",
      verdict: 'leanYes',
      verdictReason: 'The Six of Swords is the crossing away from the storm — things truly are improving, just quietly and slowly. A gradual, gathering yes.',
    },
    reversed: {
      keywords: ['unable to leave', 'old ties dragging', 'circling in place', 'resisting change'],
      core: "Reversed, the boat can't leave the shore. The anchor may be practical — contracts, money, obligations — or inner: reluctance, resentment, fear that out there is worse. So you complain about the waves yet won't board. Sort out which anchor has you: practical ones unhook item by item; inner ones need you to name honestly what you fear. The boat has been there all along; what's missing is your decision to leave.",
      daily: "No need to force letting go today — take inventory instead. Write down every reason you can't leave, and mark each one: practical constraint, or emotional knot? Just seeing where the anchors sit loosens the boat by half.",
      love: "An old flame or an old pattern keeps pulling you back — you know it drains you, yet leaving is hard. Deal with the fear of being alone first; only then can you see stay-or-go clearly.",
      career: "You want out but can't get out, or the transition plan keeps running aground. List the conditions leaving requires and prepare them one by one — stuck now doesn't mean stuck forever.",
      money: "Funds are pinned where you can't exit, or the switching cost is running higher than expected. Redo the math and move in stages — more realistic than forcing it all at once.",
      advice: "Find the anchor that's holding you, and start by untying the easiest rope.",
      past: "When it was time to leave the shore, the boat never sailed — practical conditions or an unwilling heart kept you in place, and that tether runs to today.",
      present: "You're half wanting to go, half held by the anchor. Sort out whether what binds you is reality or fear — then untie the ropes one line at a time.",
      other: "They want out of some situation but can't get free — held by practical constraints or a heart that can't let go. Their thoughts run heavy and back and forth.",
      verdict: 'leanNo',
      verdictReason: 'Reversed shows the crossing blocked and old ties still binding — the change you want is unlikely to sail soon. The moorings must come off before progress comes.',
    },
  },
  {
    id: 'swords-07',
    name: '寶劍七',
    nameEn: 'Seven of Swords',
    arcana: 'minor',
    suit: 'swords',
    rank: 7,
    number: 7,
    scene: 'Under a yellow sky, a man tiptoes briskly away from a camp, five swords bundled in his arms as he glances back over his shoulder; two swords remain planted behind him beside a row of tents, with a small cluster of figures in the distance.',
    upright: {
      keywords: ['stealth', 'strategy', 'deception', 'going it alone'],
      core: "The man tiptoes out of camp with five swords, two left behind — he couldn't carry them all, nor did he plan to be seen. Two readings: someone near you isn't playing straight — information withheld, credit walking off — or you're the one eyeing a shortcut past the direct conversation. Strategy isn't the sin — believing you won't be caught is. If a move can't stand daylight, plan what you'll say the day it's seen.",
      daily: "Keep an extra eye open today: get verbal promises down on record, check your valuables and accounts. And if you're planning to act first and explain later on something, pause — ask whether there's a route through the front door that also works.",
      love: "Watch the covered-over corners of the relationship — ambiguous messages, gaps between the story and the day. If you're the one hiding something, the truth will out — telling them yourself costs the least.",
      career: "Guard against ideas being lifted and information being siphoned — keep a written trail on key progress. Before playing clever, ask: when this move is laid on the table, can you stand behind it?",
      money: "A high-risk window for scams and smooth talk — verify the source of anything that sounds too good. Read contracts clause by clause, and never hand money to someone who will only promise out loud.",
      advice: "Put the important things in writing — and if the front door works, don't climb the wall.",
      past: "Looking back at the start, some of it didn't happen above board: information withheld or a shortcut taken, and that planted the situation you're in now.",
      present: "There's more going on under the table than on it. Keep an extra eye open and a record of everything — and before taking a shortcut, picture the day it's seen.",
      other: "They're holding something back — some calculation, or something inconvenient to say. Not necessarily malice, but they certainly haven't laid out the whole picture.",
      verdict: 'leanNo',
      verdictReason: 'The Seven of Swords is shrouded in concealment and calculation — there is more beneath the surface, so wishes are hard to grant now. Verify before you act.',
    },
    reversed: {
      keywords: ['coming clean', 'secrets surfacing', 'guilty conscience', 'giving back'],
      core: "Reversed, the man can't carry those swords much farther — the secret is running out of hiding places. The truth surfaces by itself, or someone's conscience gives out first. If you're the one hiding, this is the cheapest moment to confess — on your own terms, not caught. If you're the one in the dark, don't detonate the first clue; confirm the whole picture first. Rebuilding starts only once it's all on the table.",
      daily: "Today is right for clearing one thing off your conscience: own the mistake that needs owning, return what needs returning, explain the misunderstanding that needs explaining. Before you speak, prepare three sentences: what happened, where my responsibility lies, and how I plan to make it right.",
      love: "What's hidden is close to slipping out — better to speak first than be found out. If you're the one who was kept in the dark, hear the full version before deciding whether to forgive.",
      career: "Under-the-table maneuvers may come to light — if any part touches you, explain it early and on your own initiative. Handling one mistake honestly protects your credit far better than a perfect cover-up.",
      money: "Accounts left vague should now be opened and squared — clarifying them yourself protects your name. If you find you've been cheated, keep the evidence and go through proper channels.",
      advice: "While there's still time, lay it out yourself — coming clean first costs the least.",
      past: "What was hidden could not stay hidden in the end. The moment that secret broke the surface is what pushed the situation to where it stands today.",
      present: "The truth is standing at the edge of disclosure — telling it yourself beats being exposed. If you're the one in the dark, get the whole picture before you react.",
      other: "They're carrying something that's getting hard to keep hidden — the weight on their conscience is working on them, and may be wavering over whether to speak first.",
      verdict: 'neutral',
      verdictReason: "Reversed is the turning point where truth surfaces — the outcome is still open and depends on how things are handled once laid bare. Handle it honestly and there's a way through.",
    },
  },
]
