// English content: wands-08 … wands-14 (Eight through Ten + Page/Knight/Queen/King, 7 cards).
// name/nameEn/ids MUST mirror the zh files and registry; verdicts MUST match zh.
import type { TarotCard } from '../types'

export const wands0814: TarotCard[] = [
  {
    id: 'wands-08',
    name: '權杖八',
    nameEn: 'Eight of Wands',
    arcana: 'minor',
    suit: 'wands',
    rank: 8,
    number: 8,
    scene: 'Eight wands streak diagonally across a clear sky, green leaves still on their shafts, above an open green plain with a river and a small house on a distant hill — no human figure anywhere in the frame.',
    upright: {
      keywords: ['rapid progress', 'good news', 'momentum', 'falling into place'],
      core: "Eight wands fly across the sky at once — things are moving at a speed you rarely get. News you've waited ages for is about to land, and a stalled plan is suddenly in motion. This current doesn't need any more pushing from you; your job is to keep pace. Sort your priorities now, so that when the opportunity touches down, you're ready to catch it.",
      daily: "Today runs faster than usual — messages, replies and updates may flood in all at once. Rather than touching everything, pick the single most important one and answer it immediately. Clear it before the afternoon, and the rest will queue up behind that momentum on its own.",
      love: 'Things are accelerating — a slow flirtation may turn into a sudden confession, and long-distance couples get a chance to close the gap. Messages will come fast; reply fast too.',
      career: "This project is hitting its sprint — the approval or answer you've been waiting on arrives soon. Ride this tailwind and push through everything you've been putting off, in one go.",
      money: 'Money is moving quickly — payments land and deals close faster than expected. Act fast, but still take one minute to double-check the numbers before you commit.',
      advice: "Move with the speed — don't let a message that needs answering or a decision that needs making sit overnight.",
      present: "News and progress are rushing toward you right now, and the point is to catch them — set your priorities so no opportunity expires while it's sitting in your hands.",
      past: 'An earlier tailwind pushed everything to where it stands today: one timely reply, one decisive move, and the situation took shape fast.',
      other: 'They are moving quickly right now, and their attention is flying your way — a message may already be in transit, and that drive to move things forward is real.',
      verdict: 'yes',
      verdictReason: 'The Eight of Wands is one of the fastest cards in the deck — everything is running at full speed with the wind behind it, and the answer leans crisply toward yes.',
    },
    reversed: {
      keywords: ['delays', 'crossed wires', 'haste backfiring', 'rhythm out of control'],
      core: "Reversed, these eight wands either fly in chaos or refuse to land: the flight is delayed, the reply never comes, too many moving parts collide. The frustration comes from knowing things should be moving and they aren't. Instead of chasing and prodding, use this forced pause to check your bearings — sometimes a delay is protecting you from sprinting full speed toward something you haven't thought through.",
      daily: "Today may test your patience with messages left on read, last-minute reschedules and things stuck in transit. Breathe, and use the waiting to tidy your to-do list and clarify what comes first. Confirm anything you can confirm proactively — don't let a misunderstanding stay airborne another day.",
      love: "Messages are prone to time lags and misreadings right now — one sentence taken the wrong way can chill the whole room. If something bothers you, ask directly; don't write the script in your head.",
      career: "Progress is stuck in someone else's hands, and pushing won't unstick it. Finish everything on your side of the fence and keep a paper trail, so you can reconnect the moment things move.",
      money: "The odds of delayed payments or deals going sideways are up — leave extra slack in your cash flow. Any investment you're itching to jump into deserves a two-day wait and a second look.",
      advice: "When things won't move, don't force them — recalibrate first, and launch at full speed once the current returns.",
      present: "You're stuck in that maddening place where things should move but won't. Rather than pushing harder, use this forced pause to recalibrate where you're headed.",
      past: 'The root of this lies in a delay or a crossed wire: a reply arrived late, a message got misread, and the rhythm has been off ever since.',
      other: "Things are chaotic on their end: slow replies, plans knocked sideways. They haven't gone cold — their rhythm is just jammed by too much at once.",
      verdict: 'leanNo',
      verdictReason: 'The reversed Eight of Wands shows stalled timing and crossed signals — forcing it now gets little result, so this leans toward waiting a little longer.',
    },
  },
  {
    id: 'wands-09',
    name: '權杖九',
    nameEn: 'Nine of Wands',
    arcana: 'minor',
    suit: 'wands',
    rank: 9,
    number: 9,
    scene: 'A man with a bandaged head stands leaning on one wand, glancing warily over his shoulder, while eight more wands stand upright behind him like a fence, with rolling green hills in the background.',
    upright: {
      keywords: ['seeing it through', 'guardedness', 'the last mile', 'wounded but standing'],
      core: "The man here has been hurt and leans on his staff — but he's still standing, and the fence behind him is everything he's defended to get here. That's probably you too: you've held out a long time, worn down, maybe wondering if it's worth it. The message is blunt — you're closer to the finish than you think, and quitting now would waste it all. Save your strength for the key points; a little longer and you're through.",
      daily: "Today you may feel bone-tired and unusually guarded. Give yourself permission to slow down, but don't drop the lines that matter. Before bed, write down the one thing you absolutely must hold tomorrow — and let yourself off the hook for the rest.",
      love: "If you've been through rough patches as a couple, don't let old wounds make you defensive toward the person in front of you now. Same if you're single — old scars don't have to become new walls.",
      career: "The project is in its most draining final stretch, and you are the last checkpoint for quality. Tired as you are, give it one more look before it goes out the door.",
      money: "This is a season for defense over offense — protect the savings and positions you already have, and don't take unnecessary risks trying to win it all back in a hurry.",
      advice: 'Hold on through this last stretch, and spend your strength on the one line of defense that matters most.',
      present: "This is the most exhausted stretch — and the closest to the finish. Ration what strength remains for the key defenses instead of guarding everything at once.",
      past: "You defended your way here: none of that wear and those small wounds were wasted — they bought the fence that's still standing today.",
      other: "They've held out a long time and carry old wounds; right now they're warily guarding their own lines. Tired, yes — but they have no plans to leave their post.",
      verdict: 'leanYes',
      verdictReason: "The Nine of Wands is weary and wounded, but the direction is still holding on and pulling through — as long as you don't abandon the post midway, the answer leans yes.",
    },
    reversed: {
      keywords: ['utterly drained', 'over-defensiveness', 'wanting to quit', 'fighting alone'],
      core: "The reversed Nine of Wands is endurance bent out of shape: either you've built the walls so high nobody can get in, or you're so exhausted you want to drop everything. The long strain has blurred which threats are real and which are imagined. What you need most now isn't to push harder — it's to share the load. Open a small gate in the fence and let support in. You don't have to defend the whole city alone.",
      daily: 'Stop saying "I\'m fine, I can handle it" today. Pick the thing that has sat on your shoulders the longest, and either ask for help or simply postpone it. Then watch what happens: the sky doesn\'t fall, the world keeps turning, and you finally get to breathe.',
      love: "Too much armor keeps out the people who care about you. Try taking off one layer first — say out loud how tired you actually are, and what you actually need.",
      career: "Watch for burnout creeping up on you — the dip in output isn't your ability fading, it's your battery hitting empty. Start a conversation about rebalancing the workload.",
      money: "Anxiety-driven over-tightening, or being too exhausted to look at the accounts at all — both extremes hurt your finances. Start by restoring the smallest habit: tracking what you spend.",
      advice: 'Stop holding it alone — ask for help, rest first, and hand the watch to someone you trust for one night.',
      present: "You can no longer tell which threats are real — the walls keep rising and the watch keeps draining you. Open a gate and let support in.",
      past: 'The habit of carrying everything alone and never asking for help is the main thing that ground you down to this frayed, empty state.',
      other: "They're stretched close to breaking: walls built high, hard for anyone to approach — and underneath the guardedness is a deep, deep tiredness.",
      verdict: 'leanNo',
      verdictReason: 'Reversed, the battery is empty and the defenses are off balance — pushing on like this risks collapse. Rest and regroup first; for now this leans no.',
    },
  },
  {
    id: 'wands-10',
    name: '權杖十',
    nameEn: 'Ten of Wands',
    arcana: 'minor',
    suit: 'wands',
    rank: 10,
    number: 10,
    scene: 'A man clutches ten wands in both arms, leaning forward and trudging with effort, the bundle blocking his view, while tilled fields and village houses stand not far ahead.',
    upright: {
      keywords: ['heavy burden', 'carrying it all', 'overloaded with duty', 'the end in sight'],
      core: "He's carrying ten wands toward the village — nearly there, but the bundle blocks his view and bends his back. You may be doing the same: taking on far too much yourself. \"The capable get more work\" sounds like praise; in practice it's overload. This card doesn't dismiss your effort — the destination really is close — but it asks: must every one of these be carried by you? Set a few down, and you'll walk faster.",
      daily: "Spread out your to-do list today and honestly mark which items are your responsibility and which are other people's that you picked up along the way. Choose one to hand back or delegate — one less wand, and your shoulders lighten immediately.",
      love: "A relationship can't run on one person's shoulders. If the housework, the emotional labor and the planning all land on you, it's time to lay the division of labor on the table and talk about it.",
      career: "Your workload has hit its ceiling — take on any more and quality will be the first thing to break. Learning to say no and to delegate is the most important career lesson of this phase.",
      money: 'Loans, installments and favors owed add up to real pressure. List every debt you carry, then concentrate your fire on clearing the one with the highest interest rate first.',
      advice: "Take stock of every wand on your shoulders, and hand back the ones that aren't yours.",
      present: "You're carrying an armful of wands down the final stretch. The question isn't how much longer you can hold out — it's which of these you could set down first.",
      past: 'It all began with you reflexively taking things on, one after another — thinking "I can manage a bit more," while the weight quietly stacked up.',
      other: "They're trudging under an armful of responsibilities, so busy their view has narrowed to what's right in front of them — most of their energy goes into holding on.",
      verdict: 'leanNo',
      verdictReason: "The Ten of Wands is overload held together by sheer grit — continuing this way rarely ends well. Unless you lighten the load first, this leans no.",
    },
    reversed: {
      keywords: ['setting down the load', 'nearing collapse', 'sharing the load', 'letting go'],
      core: "Reversed, there are two roads. On one, you finally set a few wands down — cutting, delegating, saying no — and your shoulders can see the sky again. On the other, you grip everything until it spills from your arms, forced to let go by collapse. The card invites you to choose the first: putting things down on purpose is far more dignified than dropping them. List what can go, and start today.",
      daily: "The weight you've been accumulating feels especially heavy today. Instead of trying to finish everything, decisively cut one unimportant task and spend the freed time sleeping or walking. Rest isn't slacking — it's stopping the loss.",
      love: "If you've long been the one who carries everything in the relationship, the weariness is showing whether you admit it or not. Saying so honestly beats swallowing it in silence until you blow up.",
      career: "You're one step from burnout — or already weighing whether to step out of a role. Handing over and asking for help isn't failure; it's professional first aid.",
      money: 'Go through the subscriptions quietly draining your account each month and the bad debts you should have dealt with long ago — the reversed Ten of Wands is exactly the time for a financial declutter.',
      advice: "Set part of it down on your own terms — don't wait for your body or the situation to slam the brakes for you.",
      present: "You're standing at the fork between putting things down and breaking down. While you still have the choice, cut one thing and stop the loss yourself.",
      past: "That earlier stretch of overloaded endurance planted the cracks: what you couldn't bear to set down then is now starting to slip out of your arms.",
      other: "They're right at the edge of overload and are quietly working out what to drop. What they need most right now is simply room to breathe.",
      verdict: 'neutral',
      verdictReason: 'The reversed Ten of Wands hangs between letting go and breaking down — the outcome depends on whether you choose to lighten the load, so the reading stays neutral.',
    },
  },
  {
    id: 'wands-11',
    name: '權杖侍者',
    nameEn: 'Page of Wands',
    arcana: 'minor',
    suit: 'wands',
    rank: 11,
    number: 11,
    scene: 'A young man stands in a desert, both hands resting on a wand as tall as himself, gazing up at the fresh sprout at its tip, dressed in a yellow tunic patterned with salamanders and a hat with a red feather, pyramids visible in the distance.',
    upright: {
      keywords: ['budding passion', 'curiosity', 'fresh news', 'eager to try'],
      core: "The Page stares at the sprout on his wand, and his eyes say one thing: \"I want to try this.\" He might be someone around you — an eager newcomer just getting started — or a side of yourself: curiosity beginning to stir again. This energy isn't mature yet, but its value is exactly the nerve to ask and to leap. A message or invitation carrying a spark is on its way; catch it, and let it take you somewhere new.",
      daily: 'Watch for new ideas or out-of-the-blue invitations today — they look small but could be the doorway to your next adventure. Look at familiar things with beginner\'s eyes, and say "sure, let\'s try it" to at least one new idea.',
      love: "Someone younger — or young at heart, all playful energy — may come courting and bring a flutter you haven't felt in a while. If you're together, revisit the playfulness of when you first met.",
      career: "A good time to volunteer for a task you've never done, or to genuinely hear out a newcomer's suggestion. Junior doesn't mean uninsightful — and that includes you.",
      money: "Staying curious about new financial ideas is healthy — practice with small amounts and build experience, but don't rush your whole stake into territory you barely know.",
      advice: "Keep a beginner's enthusiasm, say yes to the new invitation, and learn as you go.",
      present: "Fresh news or a new invitation is right in front of you — whether from an eager someone nearby or the itch inside you, catch it first and sort the rest out later.",
      past: 'It started with a simple spark of curiosity: maybe an idea that caught your own heart, maybe an enthusiastic new face who carried in the flame.',
      other: "They're like a child whose curiosity is in full bloom — eager to try what's in front of them, straightforward and uncomplicated, riding high on the excitement.",
      verdict: 'leanYes',
      verdictReason: 'The Page brings sparks and fresh news — an exploratory kind of yes. The direction is good; it just needs time to grow up.',
    },
    reversed: {
      keywords: ['short-lived enthusiasm', 'hesitating', 'disappointing news', 'direction unset'],
      core: "The reversed Page still holds the wand, but his eyes have wandered: ideas get started and go nowhere, or you want to act but daren't raise your hand. He can also be the person nearby who talks big and never delivers. The passion isn't gone — it's stuck between fear of doing it badly and not bothering to persist. Cut the goal down until it's too small to fail, relight the flame, then talk about how far to go.",
      daily: "Take stock of the things you started recently and left sitting to one side. Pick one and work on it for just ten minutes today. Don't underestimate those ten minutes — a fire that's gone out is never relit by grand resolutions, only by small moves.",
      love: "The odds are high that a flirtation runs hot and cold — all spark, no commitment. Don't rush to invent excuses for them; watch what they do, not the sweet things they say.",
      career: "Proposals risk being all thunder and no rain, or the response comes back weaker than hoped. Finish one half-done thing first — credibility is worth more than ideas.",
      money: "Impulse buys that sit unused are your main money leak lately. Before the next new toy, ask yourself how long you played with the last one.",
      advice: 'Relight the fire smaller: commit to one thing at a time, and see it through.',
      present: "The task now is to check whether the flame is still alive — whoever is running hot and cold, them or you, watch the actions first before deciding how much to invest.",
      past: "A fire was started and left to sit: maybe your own short-lived enthusiasm, maybe someone's promise that trailed off — and it has hung unresolved ever since.",
      other: "Their heat flickers on and off: attraction mixed with hesitation, and what they say doesn't always keep pace with what they do. The direction isn't set yet.",
      verdict: 'leanNo',
      verdictReason: "The reversed Page's flame flickers — the news and the feelings are both still unstable, so for now the answer leans toward waiting and watching.",
    },
  },
  {
    id: 'wands-12',
    name: '權杖騎士',
    nameEn: 'Knight of Wands',
    arcana: 'minor',
    suit: 'wands',
    rank: 12,
    number: 12,
    scene: 'An armored knight grips a wand astride a reddish-brown horse rearing to charge, his surcoat printed with salamanders and a red plume streaming from his helmet, with desert and distant pyramids behind him.',
    upright: {
      keywords: ['full speed ahead', 'spirit of adventure', 'magnetic charm', 'up and go'],
      core: "Hooves in the air — the Knight doesn't even have a posture for hesitating. He may be someone around you — an action-first friend pulling you forward, an ardent pursuer — or the charge building inside yourself. This energy runs on speed and nerve: changing scenes, setting out, going all in — all land hardest done now. The one essential is a sense of direction: the horse runs fast, but the reins stay in your hands.",
      daily: "Your drive is at full charge today — perfect for anything that needs nerve: negotiating, pitching, confessing, signing up. Strike in the morning while the heat is highest, and spend three minutes confirming the destination before you set out, so you don't run fast down the wrong road.",
      love: "An ardent, direct pursuit may begin, moving fast enough to set your pulse racing. Enjoy the sparks fully — and watch whether this heat can last.",
      career: "Chances to travel, relocate or switch tracks are surfacing, and the action-takers have the edge right now. Move fast if you want it — but read every contract to the end before you sign.",
      money: "Money-making chances arrive fast, and the market moves just as fast. If you trade short-term, set your stop-loss and take-profit first — don't let adrenaline make decisions that belong to discipline.",
      advice: 'Ride the momentum and set out boldly — but confirm the direction before you open the throttle.',
      present: "The momentum is hot and this is the stretch of road built for the throttle. Grip the reins, confirm the direction, and run this section boldly.",
      past: 'The situation was pushed open by a surge of drive: maybe you upped and went on the spot, maybe an action-first someone pulled you onto the horse with them.',
      other: "They're at full blaze: passionate, direct, acting the moment the thought lands — when something interests them, they move toward it. Fast tempo, worn openly.",
      verdict: 'yes',
      verdictReason: 'The Knight rides at full gallop — the moment for action has arrived, and this card answers "should I go for it?" with a very crisp: charge.',
    },
    reversed: {
      keywords: ['bold but reckless', 'quitting halfway', 'short-fused', 'momentum broken'],
      core: "The reversed Knight has fallen from the horse or been forced to rein it in: a plan launched with fanfare stalls midway, or the charge slams into an unseen wall. He can also be the person nearby whose promises fly thick and whose temper catches at a spark. The lesson is trading fast for steady — the momentum survives; it just needs re-saddling. Find the root of the impatience first, then plan the next stretch.",
      daily: "Your irritability runs high today, and slow people and slow things will test you. Take an extra breath before you speak, drop one gear when you drive or ride — and type the rant into your notes app first, deciding tomorrow morning whether to actually send it.",
      love: "Beware passion that leaves as fast as it came, and words blurted in a hot moment that can't be taken back. Cooling down isn't falling out of love — it's leaving the relationship room to breathe.",
      career: "Rushed work breeds mistakes, and the urge to jump ship may just be an urge to escape where you are. Figure out whether you're drawn to the new thing or fleeing the old one — then hand in the notice, or don't.",
      money: 'The impulse to chase highs and dump lows is strong — much of what feels like "decisiveness" lately is really just impatience. Build in a cooling-off period; sleep on any big purchase before you swipe.',
      advice: 'Rein in and slow down first — find the root of the impatience, then get back on the road.',
      present: "The task at hand is trading fast for steady — whoever the impatient one is, you or someone beside you, slow down first; how to restart comes after.",
      past: 'Charging too fast left recoil: one hasty decision, or a plan that stalled mid-road, carried the situation into the bumpy stretch it is now.',
      other: "They're a little agitated right now: heat that arrived fast is cooling, or their horse got reined in mid-gallop — either way, their patience is running unsteady.",
      verdict: 'neutral',
      verdictReason: "The reversed Knight's momentum is broken but the ember survives — success hinges on steadying the impatience first, so for now the reading stays neutral.",
    },
  },
  {
    id: 'wands-13',
    name: '權杖王后',
    nameEn: 'Queen of Wands',
    arcana: 'minor',
    suit: 'wands',
    rank: 13,
    number: 13,
    scene: 'A queen sits enthroned with a wand in her right hand and a sunflower in her left, lions and sunflowers carved into the throne behind her, a black cat seated at her feet, against a pale yellow sky and distant hills.',
    upright: {
      keywords: ['radiant confidence', 'warm leadership', 'independence', 'brimming vitality'],
      core: "Sunflowers turn toward the sun — she carries her own. She may be someone around you: a warm, generous woman who brightens a room just by entering. More often she's calling up that confidence in you: you don't need anyone's permission to run your own show. The black cat at her feet says sharp intuition sits beneath the warmth; use charm and judgment together, and things go smoother than expected.",
      daily: "Today, be the one who glows: convene the meeting, greet people first, hand out the compliments. Your warmth will carry the whole room. Wear whatever makes you feel most alive, stand tall, and play today on home ground.",
      love: "Confidence is your best magnetism right now — staying true to yourself is exactly what draws the right person closer. If you're together, take the lead and plan a lively date.",
      career: "A good time to step up front — host, present, mentor the new hires. Your warmth is a team asset right now. Leadership doesn't have to be fierce; warmth commands respect too.",
      money: "You have the standing to call the financial shots — lead the household budget, or step up and negotiate that price yourself. When your gut flags a number, it's worth a second look.",
      advice: 'Trust your charm and your intuition — step into the light and run the show.',
      present: "It's your turn to step into the light, charm and intuition working together. If the person nearby who carries their own glow offers a hand, move toward them.",
      past: "This was once lit by a warm confidence: maybe a generous woman pulled you up, maybe it was you daring to take charge back then.",
      other: "They're in a confident, glowing state: warm, generous, sure of their own mind — they know what they want, and they enjoy lighting up the people around them.",
      verdict: 'yes',
      verdictReason: 'This queen is confident and luminous — resources and goodwill are both on your side, and the answer to "go for it" is a clear yes.',
    },
    reversed: {
      keywords: ['shaken confidence', 'envy and comparison', 'emotional swings', 'people-pleasing burnout'],
      core: "Reversed, the sunflower droops. You may be stuck comparing yourself to others and feeling not bright enough — or burning yourself to ash to keep up the image of being liked by everyone. Sometimes she also points to a controlling or score-keeping woman nearby. But the light source was yours all along; it's only temporarily covered. Stop the pleasing and the comparing, pull your energy back, and spend it on yourself.",
      daily: "Take your eyes off everyone else's highlight reel today and save some time for what you actually want to do. Cancel one invitation you accepted purely to save face, spend that hour recharging — and the light will come back on its own.",
      love: 'Possessiveness and comparison sneak into relationships easily right now, and interrogating and testing only push people further away. Settle your own insecurity first.',
      career: "Office comparisons and cliques are the biggest drain on you — keep your distance from the gossip. Put your energy back into the work itself; the results will speak for you.",
      money: 'Money spent on appearances, or on keeping up with someone else, is the least worth spending. Before buying anything lately, ask yourself: do I want this — or do I want to be seen with it?',
      advice: 'Pull back the energy you spend pleasing others, and fill your own tank first.',
      present: "Your light is being blocked by comparison right now — whether the shade comes from people around you or your own unease, turn your gaze back inward and recharge.",
      past: "Comparing and pleasing cast shadows over how this began: maybe you shortchanged yourself to be liked, maybe someone's score-keeping wore you down along the way.",
      other: "Their light has dimmed for now: likely caught in comparison and insecurity, holding the bright surface together while running rather empty underneath.",
      verdict: 'leanNo',
      verdictReason: "Reversed, her light is blocked by comparison and burnout — forcing a performance before you've steadied isn't in your favor, so this leans no.",
    },
  },
  {
    id: 'wands-14',
    name: '權杖國王',
    nameEn: 'King of Wands',
    arcana: 'minor',
    suit: 'wands',
    rank: 14,
    number: 14,
    scene: 'A king sits in profile holding a sprouting wand in his right hand, his throne and backdrop adorned with lions and salamanders, an orange cloak over his shoulders, and a small lizard on the ground beside the throne.',
    upright: {
      keywords: ['vision', 'charismatic leadership', 'decisiveness', 'building at scale'],
      core: "The King no longer leads the charge himself — he holds the whole board, and his vision makes people want to follow. He may be the elder or boss around you who dares to make the call and carry the weight. Or it may be time for you to set the tone. In his hands the fire has been tempered from impulse into direction: seeing far, deciding firmly, delivering on his word. Your stage is growing — answer it with scale.",
      daily: "Whatever's been left hanging today — you make the call. First picture where you want to be standing in three months, then work backward to today's trade-offs. Once you've decided, say it out loud, so everyone involved knows exactly where you're headed.",
      love: "A mature, dependable partner with a mind of their own may walk into your life. And in a relationship, the willingness to carry weight and make commitments moves people more than any romantic line.",
      career: "The timing is ripe for a promotion, a venture, or the helm of a major project — your judgment deserves testing on a bigger stage. When you lead, remember to delegate; don't do everything yourself.",
      money: "A good time for long-horizon financial moves: retirement planning, long-term investing, business capital. With your eyes on the far horizon, short-term swings stop being frightening.",
      advice: "Make today's decisions with a three-years-out view — then call it, decisively.",
      present: "The stage is getting bigger and this moment asks for scale — step up and set the tone, or take your cue from the far-sighted person at the helm beside you.",
      past: "The current situation was laid down by one far-sighted decision — the call may have come from an elder or boss at the helm, or it may have been yours.",
      other: "They carry themselves like a mature captain: far-sighted, broad-shouldered, a blueprint already drawn in their head — and what they say, they intend to deliver.",
      verdict: 'yes',
      verdictReason: 'The King is mature fire and command of the board — timing and capability are both in place, so you can answer this one with a bold yes.',
    },
    reversed: {
      keywords: ['autocratic', 'grandiosity', 'broken promises', 'fire running too hot'],
      core: "The reversed King has turned decisive into deaf to advice: the goals keep growing grander while the details — and the people — fall further behind. He may be the overbearing boss you're facing, or you, gripping the wand too tightly. Fire this hot scorches the people following you. Showing you can still listen now beats showing authority — swap \"because I said so\" for \"what do you think?\" and the respect comes back.",
      daily: "In today's meetings and discussions, practice being the last to speak. Hear everyone out, take notes, then synthesize. You'll find that stepping back half a pace costs you none of the lead — and lets you see the whole board.",
      love: "Steamrolling every decision leaves your partner with nothing to do but nod. Hand over half the decisions — that's when the relationship belongs to two people.",
      career: "Guard against the blind spots of ruling alone — and against higher-ups who paint big pictures and never deliver. Before any major decision, seek out the one person who will argue with you.",
      money: "Overconfidence is your most expensive cost right now. Avoid betting heavy on a single position and avoid spending to keep up appearances — pull your exposure in.",
      advice: 'Turn the volume down and the ears on — authority comes from decisions made after listening.',
      present: "The task now is reopening your ears — whether the stubborn one is the boss or you, listen all the way through before deciding, or the board can't turn.",
      past: "The root lies in a stretch of one-man rule: maybe a forceful decision-maker who wouldn't hear advice, maybe you gripping the wand too tightly yourself.",
      other: "They're in a forceful posture right now: talking big, setting the bar high, temporarily unable to take in other views — and the temper is running hot too.",
      verdict: 'leanNo',
      verdictReason: 'The reversed King is stubborn and deaf to counsel — bulldozing down the same road invites a crash. Unless the autocratic streak is corrected first, this leans no.',
    },
  },
]
