// English content for wands-01-07 (produced by content agents).
// name/nameEn/ids MUST mirror the zh files and registry; verdicts MUST match zh.
import type { TarotCard } from '../types'

export const wands0107: TarotCard[] = [
  {
    id: 'wands-01',
    name: '權杖一',
    nameEn: 'Ace of Wands',
    arcana: 'minor',
    suit: 'wands',
    rank: 1,
    number: 1,
    scene: 'A hand reaches out of a cloud, gripping a wand that is sprouting fresh leaves, a few leaves drifting in the air; below lie a river and trees, with a castle on a distant hill.',
    upright: {
      keywords: ['spark of inspiration', 'new opportunity', 'drive', 'creation'],
      core: "The hand from the cloud is offering you a wand that's still sprouting: an idea, a surge of drive, a chance that makes your heart beat faster. It hasn't taken shape yet, but it's bursting with life. What matters most right now isn't how complete the plan is — it's actually getting your hands on it while the heat is still there. A spark only becomes a flame once it's used.",
      daily: "That idea you've been itching to try — give it an outlet today. It doesn't have to be perfect: spend twenty minutes writing the concept down, looking one thing up, or saying it out loud to someone. Let the spark actually land.",
      love: "Attraction arrives fast and real. If you're single, go ahead and show your interest — don't let the moment go cold. If you're together, plan a spur-of-the-moment date and relight the heat between you.",
      career: "A new project, opening or business idea is breaking the surface — a starting point worth seizing. Rather than evaluating it over and over, build a small rough prototype and test the water.",
      money: "A promising new avenue is appearing — a side gig, a fresh income stream. The starting amount doesn't need to be big; what counts is running one real cycle and proving it works.",
      advice: 'Light the fire while the passion is hot — the details can be fixed as it burns.',
      past: "It all began with an idea that made your heart race. That do-it-now surge of energy back then is what carried the spark all the way to today.",
      present: "A freshly sprouted opportunity is in your hand right now. Landing it while the heat lasts matters more than waiting for the plan to be perfect.",
      other: "A new fire is burning in that person: they're eager about someone or something in front of them, and their moves may come fast and direct.",
      verdict: 'yes',
      verdictReason: "An Ace is the suit's purest energy, and the Ace of Wands is the green light at the starting line — the timing for action is ripe, so go for it.",
    },
    reversed: {
      keywords: ['fizzled passion', 'delays', 'short-lived enthusiasm', 'unclear direction'],
      core: "Reversed, the wand is in your hand but it won't light: maybe inspiration comes and goes, maybe circumstances keep blocking you, or maybe you started in a rush of excitement and left it on a shelf three days later. Before blaming yourself for lacking willpower, check whether this thing genuinely moves you. When a fire won't catch, sometimes the wood is simply stacked in the wrong place.",
      daily: "On a day with no spark, forcing yourself to burn only wears you out. Cut today's to-do list down to three items and finish the smallest one first — use a little dose of completion to restart the stalled engine.",
      love: "The temperature has dropped — a flirtation that never progresses, or time together that feels like routine. Instead of waiting for the other person to warm things up, get clear on whether you still want this.",
      career: "A plan gets shelved, a proposal goes unanswered — you can't get traction. Don't rush to change lanes yet; find the exact link that's stuck and fix one thing at a time.",
      money: "The urge to make quick money is especially dangerous right now — impulsive bets tend to be abandoned halfway, principal and all. Park any new spending plan for two weeks, then see if you still want it.",
      advice: "If the fire won't catch, tend the wood first — shrink the goal before the passion runs dry.",
      past: "The start was a little forced: enthusiasm came fast and faded fast, and that beginning that never caught fire is still sending ripples into the present.",
      present: "The fire in your hands won't quite light. Don't blame your willpower first — check whether the wood is stacked right, shrink the goal, and try again.",
      other: "That person's heat is cooling: the initial enthusiasm didn't hold, they can't quite summon the energy right now, and their replies have slowed as a result.",
      verdict: 'leanNo',
      verdictReason: "The reversed Ace of Wands shows blocked energy and unripe timing; forcing things forward now costs double for half the result — clear the blockage first.",
    },
  },
  {
    id: 'wands-02',
    name: '權杖二',
    nameEn: 'Two of Wands',
    arcana: 'minor',
    suit: 'wands',
    rank: 2,
    number: 2,
    scene: 'A man stands on a castle terrace, a small globe in his right hand and a wand steadied in his left, with another wand fixed to the wall; he gazes over a bay toward distant hills, and crossed roses and lilies are emblazoned on the wall.',
    upright: {
      keywords: ['looking ahead', 'planning', 'a choice', 'ambition'],
      core: "The world is already in his palm, yet his eyes are on what lies beyond the wall. The Two of Wands speaks of the view after the first success: you have a foothold now, and you must decide where the next step goes. Stay inside the safe city, or set out for a bigger map? This card urges you to lift your gaze and start planning in earnest.",
      daily: "Carve out half an hour to lay out everything you want to accomplish in the next three months. No need to act today — thinking the big direction through and writing a simple roadmap is the most productive step you can take.",
      love: "The relationship is at the door to its next stage — a confession, moving in together, or a longer promise. Get clear on what you want first, then invite them to talk about what the future looks like.",
      career: "A fork in your career has appeared: dig deeper where you are, or push outward into new markets and new territory. Both roads lead somewhere — the question is which one gets closer to the map you want.",
      money: "A good time for medium- and long-term financial planning: set a target amount and a timeline. Look far by all means, but keep part of your allocation as a safety floor.",
      advice: 'Write down where you want to be in three months, then work backward to the first step.',
      past: "You climbed the terrace and looked past the wall long ago. The planning and ambition of that time drew the base map for where things stand now.",
      present: "You're standing at the door of a choice: stay where it's safe, or push outward. Now is the time to think the direction through, then derive the first step.",
      other: "That person is gazing somewhere farther off: they're working out their next move and do have ideas about the future — they're just still weighing the direction.",
      verdict: 'leanYes',
      verdictReason: "The Two of Wands is the outlook that comes after standing firm — with the right direction it's worth pushing forward, but it's still in the planning stage, and results take time.",
    },
    reversed: {
      keywords: ['shrinking back', 'plans spinning idle', 'settling', 'hesitation'],
      core: "Reversed, the man is still on the terrace but his feet are glued in place: the plan gets revised round after round, yet he never dares step past the wall. Or the vision outruns the hands — a grand blueprint whose first step never happens. The world will not walk over to you. Instead of polishing the perfect plan again, admit what you're afraid of, and then, fear and all, do one small thing.",
      daily: "Stop opening that plan you've revised ten times. Pick the least frightening small step in it and simply execute — send the email, sign up for the class. Break the idle loop with an act.",
      love: "Avoid talking about the future and the relationship stays parked. If the two of you keep steering around the question of what comes next, find a relaxed moment this week and gently set it on the table.",
      career: "Stay in the comfort zone too long and opportunities file past outside the wall. You needn't quit or switch fields today — but at least ask around and take interviews, so you have choices again.",
      money: "Being overly cautious leaves your money lying flat while inflation quietly eats it. Review your idle funds and pick one risk-controlled way to put them to work.",
      advice: "First admit what you're afraid of — then take the smallest possible step past the wall.",
      past: "The plan was revised again and again, but the departure never came. That stretch of watching from inside the walls kept things parked in place until now.",
      present: "The task in front of you is the idle spin: there are blueprints enough already. What's missing is the small step you take anyway, after admitting the fear.",
      other: "That person has thought about moving forward, but their feet stay put: there's an unspoken worry inside, and for now they're staying inside the familiar safe zone.",
      verdict: 'leanNo',
      verdictReason: "Reversed, the view narrows and action stalls; things won't come true through waiting alone — the current tendency is circling in place.",
    },
  },
  {
    id: 'wands-03',
    name: '權杖三',
    nameEn: 'Three of Wands',
    arcana: 'minor',
    suit: 'wands',
    rank: 3,
    number: 3,
    scene: 'A man in a red robe stands with his back turned on high ground, overlooking the sea; his right hand rests on one wand while two more stand beside him, and a few sailing ships glide slowly across the water.',
    upright: {
      keywords: ['foresight', 'expansion', 'awaiting returns', 'progress'],
      core: "The ships have left the harbor, and he stands on the high ground watching his earlier moves unfold across the water. The Three of Wands brings the first echoes after action: a partnership starts to take shape, a proposal you sent out gets a response. Keep your gaze on the horizon — the world is bigger than you first imagined, and the next wave of chances to push your map outward is coming.",
      daily: "Seeds you planted earlier may send word today. Circle back to the things that went quiet after you sent them out — one follow-up message or one confirming call is often all it takes to get things moving again.",
      love: "A long-distance or rarely-together relationship is heading for a turn — patience will pay off. If you're single, widen your circle: the right person may be just outside familiar territory.",
      career: "The project is entering its blossoming phase, and earlier effort is starting to be seen. Position for a bigger stage — cross-team work, opportunities abroad. Go as far as your scope can stretch.",
      money: "Earlier investments and groundwork are gradually paying off — the direction is right. Don't rush to harvest all the gains; leave a portion sailing on. Compounding needs time.",
      advice: 'Climb higher for the full view, and lay two steps of groundwork for the next expansion.',
      past: "You sent your ships out one by one back then. Those positions you set up early are exactly where today's echoes are coming from.",
      present: "The ships are coming back in, one after another. Your job now is to stand a little higher, take in the whole board, and leave room for the next expansion.",
      other: "That person has already acted and is waiting for the echo: their attitude is steady, their eyes on the long game, willing to give things time to develop.",
      verdict: 'leanYes',
      verdictReason: "The Three of Wands shows groundwork bearing fruit and ships on their way home — things are moving in a good direction, and all that's missing is a little patience.",
    },
    reversed: {
      keywords: ['delays', 'obstruction', 'limited scope', 'hopes deferred'],
      core: "Reversed, the ships are nowhere to be seen: the deal is stuck on the other side's desk, the promised reply keeps slipping, or a hard look reveals the original plan underestimated the difficulty. Don't read the delay as failure — it's more of a reminder that some link needs to be renegotiated and rescheduled. Revising the timeline to match reality is far more powerful than waiting it out.",
      daily: "Today may bring slipped schedules or sudden changes of plan. Rather than anxiously refreshing your messages for a reply, check in proactively once — then spend the freed-up time advancing what you can actually control.",
      love: "The progress you hoped for keeps not arriving, and their responses are slower than you expected. Don't script the ending in your head — live your own life well, and when it's time to ask directly, ask.",
      career: "The promotion or project timeline has been pushed back; plans can't keep pace with changes. Find out exactly what's blocking things, adjust the route if needed, and don't burn time on a single contact.",
      money: "Expected income may land late, so build a buffer into your cash flow. For now, avoid spending — or doubling down with — money that hasn't actually arrived.",
      advice: "A delay is not a failure — revise the timeline into a version that matches reality.",
      past: "The original schedule was estimated too optimistically. One ship that never came home on time dragged every later arrangement out of order, all the way to now.",
      present: "You're waiting on an overdue echo. Instead of waiting empty-handed, check the status once yourself, and revise the timeline into something realistic.",
      other: "That person is also waiting on a result that hasn't come: progress falling short has left them in suspense, which is why their responses seem half a beat slow.",
      verdict: 'neutral',
      verdictReason: "The reversed Three of Wands means the direction may not be wrong, but the timing is off-beat; success hinges on how fast you adjust — no firm call yet.",
    },
  },
  {
    id: 'wands-04',
    name: '權杖四',
    nameEn: 'Four of Wands',
    arcana: 'minor',
    suit: 'wands',
    rank: 4,
    number: 4,
    scene: 'Four wands stand in the foreground, a garland heavy with flowers and fruit strung across their tops; two figures raise bouquets in celebration, with a crowd and a yellow castle building behind them.',
    upright: {
      keywords: ['celebration', 'stability', 'belonging', 'a milestone reached'],
      core: "The garland is up, and people wait at the gate with flowers to welcome you. The Four of Wands celebrates a stage brought to completion: a project delivered, a relationship grown steady, a new home — or simply the solid relief of finally catching your breath. Stopping to celebrate properly is not wasted time. Ritual carves \"we did it\" into the heart, and that becomes the confidence for the road ahead.",
      daily: "Today deserves a small celebration: book a good meal, raise a glass with your teammates, or just leave early and be with family. Close out what's finished with care, and the energy will flow into what comes next.",
      love: "The relationship has reached a stage that feels safe: meeting the family, moving in, making a promise — all suit this moment. If single, go to gatherings and weddings; good matches appear where it's lively.",
      career: "The project is wrapping up well and team morale is high — share the credit around and actually throw the celebration. A solid foundation is laid; it's a good time to launch the next phase.",
      money: "Finances are entering a relatively stable stretch. Pay what's due, save what you planned, and spend the rest with a clear conscience on family and home life — this is money worth spending.",
      advice: 'Celebrate this stop properly first, then hit the road with a full tank.',
      past: "A stretch of hard work came to a satisfying close some time ago. That solid finish, celebrated together, became the foundation you're standing steady on now.",
      present: "This is the moment of harvest and celebration. Close this chapter well and toast it with your people — that's how the energy flows into the next thing.",
      other: "That person is settled and relaxed right now: they feel grounded in how things are, they enjoy celebrating and sharing, and belonging matters a great deal to them.",
      verdict: 'yes',
      verdictReason: "The Four of Wands is a card of stability and shared joy — the foundation is built and your people are celebrating with you, a clear affirmative for most questions.",
    },
    reversed: {
      keywords: ['postponed celebration', 'shaky foundations', 'family tension', 'transition'],
      core: "Reversed, the garland still hangs — the party is just postponed: a move stuck halfway, a project dragging at the finish, or family a little tense over small things. Worth noting: at heart this is still a good card. The completion isn't cancelled, only running a few beats late. Turn your attention back to the foundations — home, family, core team. Shore up the base, and the celebration will come on its own.",
      daily: "If a small unresolved knot is sitting in your home or your team, today is the day to address it. A simple \"I was short with you the other day — that was on me\" often loosens the whole thing. If the space is a mess, tidy the space first; the heart settles with it.",
      love: "Under the stable surface hides a flicker of unease — maybe hesitation about commitment, maybe pressure from family opinions. Say the reservation out loud; only then can the relationship truly land.",
      career: "Team chemistry has loosened a little, or the milestone didn't come out as polished as hoped. Don't rush to assign blame — realign the process and the division of labor first.",
      money: "Household or housing costs are quietly creeping up — repairs, a move, that kind of expense. Re-inventory your fixed outgoings and leave slack for the months ahead.",
      advice: 'The celebration can arrive late — first tighten the loosened foundation, bolt by bolt.',
      past: "The last chapter closed a bit hastily: foundations that needed shoring and knots that needed untying got skipped, and the aftershocks have carried into now.",
      present: "The party is a few beats late but not cancelled. For now, turn back and settle your family and your team — re-tighten the foundation where it has loosened.",
      other: "That person is in a transition: their usual self on the surface but a little unsettled underneath, part of their attention pulled away by things around them.",
      verdict: 'leanYes',
      verdictReason: "Even reversed, the Four of Wands keeps its base tone of stability and completion — mostly just delayed or discounted, the direction still leans good.",
    },
  },
  {
    id: 'wands-05',
    name: '權杖五',
    nameEn: 'Five of Wands',
    arcana: 'minor',
    suit: 'wands',
    rank: 5,
    number: 5,
    scene: 'Five young men each brandish a long wand, the staves crossing and clashing in a scene that looks half brawl, half practice bout, against a flat open field and a pale sky.',
    upright: {
      keywords: ['competition', 'clashing opinions', 'a scramble', 'sparring'],
      core: "Five wands cross in mid-air, and you can't tell who's attacking and who's defending. The Five of Wands paints a scene where opinions fly: everyone in the meeting has a position, rivals line up across the market. Chaotic as it is, there's no real malice here — it's closer to a sparring match. Rather than rushing to shout down every voice, treat it as a chance to sharpen your ideas against the friction.",
      daily: "Today's discussions may throw extra sparks. Before the meeting, decide the one point you most want to hold — everything else can bend. Consensus beats being right, and remember: volume is not persuasion.",
      love: "Bickering over small things is more frequent, or a rival has appeared. Arguing isn't the problem — what matters is whether you understand each other better after. Don't let scorekeeping smother the feeling.",
      career: "Workplace competition is heating up — colliding proposals, resources being grabbed. Put your energy into making your own work better instead of tracking your rivals' every move.",
      money: "The market is unusually noisy, with every school of thought contradicting the next. Don't chase the hot names — return to your own discipline, and leave alone what you don't understand.",
      advice: 'Pick the one battle that truly matters, and let the rest of the noise blow past.',
      past: "This thing was born in a room full of talking-over: that free-for-all where everyone had an opinion is what ground out the shape it has now.",
      present: "You're standing in an arena of clashing opinions. Don't rush to overpower every voice — pick the one point that truly matters and hold it.",
      other: "That person's mind is a bit of a melee right now: several things compete for their attention at once, positions still pulling at each other, not yet in formation.",
      verdict: 'leanNo',
      verdictReason: "The Five of Wands runs on competition and tug-of-war — things must survive a scramble before they can succeed, and right now resistance clearly outweighs support.",
    },
    reversed: {
      keywords: ['avoiding conflict', 'inner battle', 'quiet attrition', 'truce'],
      core: "The reversed Five of Wands reads two ways: either the battlefield has moved inside — all civility on the surface, endless warfare and self-erosion within — or the dispute is winding down, everyone tired of fighting and ready to sit and talk. Either way, the key is the same: put the unspoken opinions on the table. Swallowing the argument is not the same as resolving it.",
      daily: "That thing you keep telling yourself to just let go — don't swallow it again today. Find a calm moment and say what you think plainly. It may be awkward for three minutes; keeping it in would drain you for three weeks.",
      love: "The surface is calm, but small grievances are stacking up underneath. Instead of guessing whether they've noticed, state your needs gently but directly. The relationship can withstand honesty.",
      career: "The team is dodging disagreements to keep the peace, and decision quality is slipping. Be the one who voices the dissenting view — the meeting room needs some healthy friction.",
      money: "Looking away from money disagreements grows bigger problems — who covers shared expenses, accounts left unclear. Set a time, lay the books open, and square them properly.",
      advice: "Pick up the sentence you've been swallowing, and say it well at the right moment.",
      past: "Some disagreements were never talked out back then — a truce on the surface, no peace underneath — and that swallowed tension has carried through to today.",
      present: "All is calm on the table, but the war goes on inside you. The current lesson is to take the words you swallowed and finally say them properly.",
      other: "That person looks calm but is battling inside: something unsaid is sitting in them, quietly wearing them down, while they keep steering clear of open conflict.",
      verdict: 'neutral',
      verdictReason: "The reversed Five of Wands sits between truce and attrition — the outcome hinges on whether you'll talk things out, and the energy itself points nowhere fixed.",
    },
  },
  {
    id: 'wands-06',
    name: '權杖六',
    nameEn: 'Six of Wands',
    arcana: 'minor',
    suit: 'wands',
    rank: 6,
    number: 6,
    scene: 'A rider crowned with a laurel wreath sits on a white horse draped in green, another wreath tied to the wand in his hand, while an escort of people around him raise their wands and press forward together.',
    upright: {
      keywords: ['victory', 'recognition', 'triumph', 'public acclaim'],
      core: "The laurel is on your head and the crowd is carrying you forward. The Six of Wands is a triumph fully earned: the pitch won, the exam passed, the effort finally acknowledged out loud. Accept the applause graciously — you deserve it. And remember: the rider sees farthest and falls hardest. Share some of the glory with the people who steadied you along the way, and the applause will last longer.",
      daily: "Today is the day to put your results on display: deliver the work, publish the numbers, report progress in the meeting. Don't worry about seeming too bold — right now you carry your own credibility. Let the right people see what you've done.",
      love: "Your relationship deserves to be blessed — it's ready to go public, ready to meet the friend group. If you're pursuing someone, a confession has strong odds: you score higher in their eyes than you think.",
      career: "Good news is on its way — a promotion, an award, a deal landed — and your name is being remembered by the people who matter. While momentum is high, actively claim the stage you want.",
      money: "Income stands to rise on the back of your performance: a raise, a bonus, a profit share are all in play. Negotiate with confidence — you're holding real chips.",
      advice: 'Step onto the podium graciously, and thank the people behind you by name.',
      past: "You once won a beautiful victory. That success, witnessed by everyone, is the source of the confidence and standing you carry now.",
      present: "The applause is heading your way right now. Receive it graciously, and while the momentum is high, show your results to the people who matter.",
      other: "That person is in top form, confidence online: they've just tasted real recognition, they carry themselves brightly, and they're happy to be seen.",
      verdict: 'yes',
      verdictReason: "The Six of Wands is itself the card of victory and acclaim — things are moving toward success that gets seen, and you can expect it with an easy heart.",
    },
    reversed: {
      keywords: ['unrecognized merit', 'missing applause', 'self-doubt', 'hollow fame'],
      core: "Reversed, the laurel sits crooked: maybe you did ninety percent of the work and someone else took the credit; maybe the recognition you're owed keeps not arriving, and you've begun to wonder if you're not good enough. Or the opposite — fame arrived faster than skill, and it feels hollow. Take some judging power back: applause can run late, but you know what you did, and no one can take that from you.",
      daily: "The sting of going unseen — don't rush to demand justice for it today. Write your contributions down in concrete terms: what you did, what it produced. Keep the record and bring it out at the right moment; it beats arguing on the spot by a mile.",
      love: "You feel your effort isn't being treasured, or that you're always the one burning hotter. Pause and watch what they actually do rather than listening to explanations — whether it's worth it, you already know.",
      career: "Credit diluted, your name missing from the promotion list — discouragement is natural. Compile your wins into a visible record, and keep an eye on outside opportunities. More than one place will value you.",
      money: "It looks good on paper but less lands in your pocket than expected — a shrunken bonus, murky profit splits. For now, get every money-related promise in writing.",
      advice: 'On the days applause runs late, log your victories one by one, in your own ledger.',
      past: "The recognition that should have been yours went missing back then. The swallowed frustration of diluted credit still colors how you see yourself today.",
      present: "You're in the gap where the applause is running late. Log your wins carefully, one by one — and don't hand the power to judge yourself to anyone else.",
      other: "That person has been discouraged lately: they feel their efforts haven't been properly seen, they sit in self-doubt, and a little recognition would hold them up.",
      verdict: 'leanNo',
      verdictReason: "The reversed Six of Wands shows recognition delayed and fame outrunning substance — the glory you hope for now comes discounted; hold steady and wait for your moment.",
    },
  },
  {
    id: 'wands-07',
    name: '權杖七',
    nameEn: 'Seven of Wands',
    arcana: 'minor',
    suit: 'wands',
    rank: 7,
    number: 7,
    scene: 'A man stands at the edge of high ground, gripping a wand with both hands and striking downward, as six wands thrust up at him from the slope below with no attackers in sight; on his feet are two mismatched shoes.',
    upright: {
      keywords: ['holding your ground', 'defense', 'one against many', 'resilience'],
      core: "One person on the high ground, holding off six wands thrusting up from below. The Seven of Wands is a title defense: you reached this position first, so the challenges naturally follow — doubting voices, competitors, an avalanche of demands. But the position is yours, and so is the advantage; fighting from above is the stronger side of the field. Plant your feet and hold the one line that matters most.",
      daily: "Today may feel like being attacked from all sides: messages, doubts, surprise tasks arriving at once. Don't rush to answer each one — pick the single challenge that truly threatens the foundation and defend it fully. The rest can wait; the sky won't fall.",
      love: "This relationship may be facing outside noise — elders' opinions, other people's comparisons. If you're sure you want this person, say so plainly. Your steadiness is the best line of defense.",
      career: "Your position or your proposal is being challenged. Don't doubt yourself — it means what you built carries weight. Prepare your case and answer the doubts head-on; backing down is how ground gets lost.",
      money: "Someone may be eyeing your resources, or urging you to abandon a strategy that's been working. Hold your existing positions and your discipline — don't break formation over a few stray voices.",
      advice: "Stay up on your high ground — don't come down. Hold the line that matters most.",
      past: "You claimed this position a step ahead of everyone, and the challenges came because of it. That hard fight to defend the hill defined the current state of play.",
      present: "Doubts and competition are surging up the slope, but the high-ground advantage is still yours. The task now is to stand firm and hold the bottom line.",
      other: "That person is playing defense: their stance is firmly planted but wound a little tight, and outside opinions get parried first, considered later.",
      verdict: 'leanYes',
      verdictReason: "The Seven of Wands carries pressure, but the defender holds the high ground and the better odds — as long as you don't abandon the position, the outcome tends your way.",
    },
    reversed: {
      keywords: ['outnumbered', 'defensive fatigue', 'urge to quit', 'breached boundaries'],
      core: "Reversed, the high ground still stands but its defender is nearly spent: demands from every direction have you running ragged — or you're grimly holding a position you should have released long ago. Ask yourself one honest question: is this hill still worth defending? If yes, go get reinforcements and repair the line. If not, retreat isn't losing — it's saving your strength for the right battlefield.",
      daily: "If you're so tired you're running on reflexes, take yourself off duty for an hour today. Kill the notifications, catch some sleep, then sort your battles into \"must hold\" and \"can release\" — you'll find the second pile is bigger than you thought.",
      love: "If you're always the one defending this relationship while they stand by watching, the line will eventually collapse from exhaustion. Hand half the garrison duty over — and if you can't hold, say so plainly.",
      career: "Workload and criticism are pressing down together, and toughing it out only grinds you down. Asking for help is no disgrace — narrow the front line and secure the core mission first.",
      money: "There's a breach in your financial defenses — overspending, or too many hands reaching out. Stop the bleeding first: cut unnecessary fixed expenses and stop promising money to others.",
      advice: "Retreating when it's time isn't defeat — save your strength for battlefields worth defending.",
      past: "That stretch of holding the line alone burned through too much strength. The cracks in the defenses appeared back then, accumulating into the exhaustion of now.",
      present: "You're propping up a line that's close to collapse. The task in front of you is sorting what must be held from what can be released — retreat does not equal defeat.",
      other: "That person is worn down from holding on: carrying pressure from every side alone, defenses nearly spent, wavering over whether to keep toughing it out.",
      verdict: 'leanNo',
      verdictReason: "The reversed Seven of Wands is a slipping line and spent strength — grinding on rarely ends well; regrouping or cutting losses first is the practical move.",
    },
  },
]
